### ISSUE TITLE
tortoise.exceptions.OperationalError: (1054, "Unknown column '?' in 'field list'")

### ISSUE THREAD

**Issue by apan-git** [tortoise/tortoise-orm#1013]
I'm going to use random fetch
```python
await table.filter(state='001').annotate(id=F('?')).order_by('id')
```
Got an error

tortoise.exceptions.OperationalError: (1054, "Unknown column '?' in 'field list'")

Tortoise - ORM 0.17.8 not supported yet?

**Comment by long2ice** [comment]
Just use `Rand` function

**Comment by apan-git** [comment]
Import from where, I can't find Rand()

**Comment by long2ice** [comment]
See https://github.com/tortoise/tortoise-orm/releases/tag/0.18.0, if other version, just custom function

**Comment by apan-git** [comment]
Thank you very much. I installed through PIP but didn't find 0.18.0, but I did find the method defined in the documentation
