### ISSUE TITLE
Tests doesn't fail on 0.18.0

### ISSUE THREAD

**Issue by KAINeDEZZ** [tortoise/tortoise-orm#1017]
I'm using tortoise 0.18.0 and writing tests for my project, i've tryed to fail one case but all tests was passed successfuly.
```
class JustTest(test.TestCase):
    def test_tests(self):
        self.assertEqual(1, 2)
```
![image](https://user-images.githubusercontent.com/50314713/147241734-3fba69ea-e0b9-4f86-93f6-192bef286dc1.png)

I tryed to install tortoise 0.17.8 and this test has fail
![image](https://user-images.githubusercontent.com/50314713/147241549-854f1795-bb51-4644-bc14-911e91eb9a70.png)

My `conftest.py`
```
import pytest
from tortoise.contrib.test import finalizer, initializer

@pytest.fixture(scope="session", autouse=True)
def initialize_tests(request):
    db_url = "mysql://root:root@localhost:3306/tg_sniffer_test"
    initializer(['aerich.models', 'sniffer.models'], db_url=db_url)
    request.addfinalizer(finalizer)

```

**Comment by long2ice** [comment]
Fixed alreadly
