### ISSUE TITLE
bulk_update with json field syntax error in postgres

### ISSUE THREAD

**Issue by amirotin** [tortoise/tortoise-orm#1022]
**Describe the bug**
Syntax error is raised when using bulk_update on models with JSON field.
```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\SkyNet\lib\site-packages\tortoise\backends\asyncpg\client.py", line 36, in translate_exceptions_
    return await func(self, *args)
  File "C:\ProgramData\Miniconda3\envs\SkyNet\lib\site-packages\tortoise\backends\asyncpg\client.py", line 180, in execute_query
    res = await connection.execute(*params)
  File "C:\ProgramData\Miniconda3\envs\SkyNet\lib\site-packages\asyncpg\connection.py", line 318, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg\protocol\protocol.pyx", line 338, in query
asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "{"
```

Generated query using bulk_update is:
`UPDATE "points" SET "extras"=CASE WHEN "point_id"=1 THEN {'test': 1} WHEN "point_id"=2 THEN {'test': 2} END WHERE "point_id" IN (1, 2)`

While using regular update query is different:
`UPDATE "points" SET "extras"='{"test": 1}' WHERE "point_id"=1`

The problem is in quotes

**To Reproduce**
```
class Points(Model):
    point_id = fields.IntField(pk=True)
    extras = fields.JSONField()

await Points.create(point_id=1, extras={'test': 1234})
await Points.create(point_id=2, extras={'test': 1234})

p1 = await Points.get(point_id=1)
p2 = await Points.get(point_id=2)

p1.extras = {'test': 1}
p2.extras = {'test': 2}
await Points.bulk_update([p1, p2], fields=['extras'])
```

**Expected behavior**
JSON code should be quoted in CASE statement

**Comment by long2ice** [comment]
Try latest source code

**Comment by amirotin** [comment]
installed last source with command `pip install git+https://github.com/tortoise/tortoise-orm`
nothing changed unfortunately - same query without quotes

**Comment by amirotin** [comment]
bulk_create is working correctly - json code is quoted

**Comment by long2ice** [comment]
Try develop

**Comment by amirotin** [comment]
> Try develop

this command fetched revision af2aab8 - which is last on develop
`Resolved https://github.com/tortoise/tortoise-orm to commit af2aab8d4f52cb0d1b986865195c00b74def6b36`
