### ISSUE TITLE
Choices for fields in tortoise ORM

### ISSUE THREAD

**Issue by RohanJnr** [tortoise/tortoise-orm#1027]
**Is your feature request related to a problem? Please describe.**
Fields that require specific values, for example, values from an HTML select tag. This would be similar to [django choices](https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices)

**Describe the solution you'd like**
https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices should be similar to.
Currently, it can be done with validators, but having this as a field option would be nice.

**Comment by long2ice** [comment]
What about `EnumField`

**Comment by RohanJnr** [comment]
Oh, right, that can be used. I totally forgot about that. Thanks!
