### ISSUE TITLE
Postgres JSON field error when using orjson package

### ISSUE THREAD

**Issue by amirotin** [tortoise/tortoise-orm#1030]
**Describe the bug**
When using orjson package there is error with bytes output. orjson returns bytes instead of string, while JSON fields exptected string.
Problem is with Postgres, maybe other databases have same issue

**To Reproduce**
install **orjson** package (will be used by tortoise orm automatically)

```
class Accounts(Model):
  settings = fields.JSONField()

acc = Accounts(settings={'mode': 'auto'})
await acc.save()

tortoise.exceptions.OperationalError: invalid input for query argument $6: b'{"mode":"auto"}' (expected str, got bytes)
```

**Expected behavior**
Json saved value expected

**Additional context**
**orjson** returns bytes instead of string in **dumps** and **loads** functions. Possible solution is to wrap function call with **str** or **.decode('utf-8')**

I know that we can override **JSON_DUMPS** and **JSON_LOADS**, but since orjson is used automatically if installed - better to fix it inside tortoise code

**Comment by long2ice** [comment]
Try latest source code

**Comment by amirotin** [comment]
> Try latest source code

I'm already on last commit in devel branch

**Comment by long2ice** [comment]
Isn't it? https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/fields/data.py#L59

**Comment by amirotin** [comment]
Sorry, my bad. I've override **JSON DUMPS** in my code to find the problem, that's why issue stayed after switching to source code version
