### ISSUE TITLE
Because of KeyError in connection pool.

### ISSUE THREAD

**Issue by tufbel** [tortoise/tortoise-orm#1037]
I use mysql with the ` minsize == 1   maxsize == 5`.
There were a lot of `500` when I sent 100 HTTP requests in a second.
```
 File ".../tortoise/models.py", line 717 , in _init_from_db.

KeyError: xxx
```
But when I change the configuration to ` minsize == 10   maxsize == 10`, the number of errors decreased. 
How else to fix this bug?

**Comment by long2ice** [comment]
Did you close connections frequently?

**Comment by tufbel** [comment]
> Did you close connections frequently?

No, I didn' t. I only set minsize and maxsize at initialization. What is the cause of this bug?

**Comment by long2ice** [comment]
Not clear
