### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cursor

### ISSUE THREAD

**Issue by rogercorrea** [tortoise/tortoise-orm#105]
**Describe the bug**
 I'm trying use Tortoise and Sanic but I always found error when I'm running the code and calling the model.All().

**AttributeError: 'NoneType' object has no attribute 'cursor'**

Why does this error occur?

I'm using Python 3.7.2 and Sanic.

`import asyncio
import uvloop
import aiotask_context as context
from sanic import Sanic
from sanic.response import json
from tortoise import Tortoise, run_async
from tortoise.models import Model
from tortoise import fields

class TbEstados(Model):
    id = fields.IntField(pk=True)
    nome = fields.TextField()
    uf = fields.TextField()
    codigoUf = fields.IntField(null=True)
    regiao = fields.IntField(null=True)

    class Meta:
        table = 'TBEstados'

    def __str__(self):
        return self.name

sanic = Sanic(__name__)

@sanic.route("/")
async def test(request):
    result = await TbEstados.all()
    return json(result)

async def run():
    await Tortoise.init(
        db_url='mysql://user:pass@ip:3306/database',
        modules={'models': ['__main__']}
    )

    await Tortoise.generate_schemas()

async def main():
    await run()

if __name__ == "__main__":

    run_async(main())
    
    asyncio.set_event_loop(uvloop.new_event_loop())
    server = sanic.create_server(host="0.0.0.0", port=8000)
    loop = asyncio.get_event_loop()
    loop.set_task_factory(context.task_factory)
    task = asyncio.ensure_future(server)
    try:
        loop.run_forever()
    except:
        loop.stop()`

**Comment by abondar** [comment]
Could you please provide traceback for given error?
