### ISSUE TITLE
Packet sequence number wrong - got 0 expected 1

### ISSUE THREAD

**Issue by draklowell** [tortoise/tortoise-orm#1058]
**Describe the bug**
Sometimes my app stops working and in logs I see this:
tortoise.exceptions.OperationalError: Packet sequence number wrong - got 0 expected 1

**Additional context**
My app is multitask but I think it must be ok.

**Comment by wangchengpei** [comment]
@draklowell Hi, have you solved the above problem?

**Comment by abondar** [comment]
That seems to be problem with pymysql
https://github.com/PyMySQL/PyMySQL/issues/422

Seems like it can happen if you have multithread application

Please write if you have any evidence that it is indeed tortoise problem here
