### ISSUE TITLE
About delete/update and DeleteQuery/UpdateQuery

### ISSUE THREAD

**Issue by asyncins** [tortoise/tortoise-orm#106]
**Describe the bug**
Delete does not return Anything

**To Reproduce**
```
res = await Projects.filter(id=id).delete()
```
res is NoneType, not DeleteQuery

**Expected behavior**
tortoise-orm documents write: `
Delete all objects in QuerySet.
Return type: | DeleteQuery
`
**Additional context**
update() too

**Comment by abondar** [comment]
Hi
Current behaviour working as expected, it just documented in confusing way.
`.delete()` indeed returns `DeleteQuery`, but `.delete()` is not coroutine, it's regular method.

In your case 
```res = await Projects.filter(id=id).delete()```
you are getting `DeleteQuery` and start awating it immediately, executing it by it.

May be we should fix documentation to make it more obvious, thanks for the note.

If you are expecting to get something as result from delete query you can refer to our other discussion #68
