### ISSUE TITLE
How i can add unique key with two fields

### ISSUE THREAD

**Issue by Bobsans** [tortoise/tortoise-orm#108]
I need to add unique key to model with 2 fields. Django offers a design `_meta.unique_togetter`. How i can do it with Trotoise?

**Comment by grigi** [comment]
Hi

Tortoise doesn't support compound indexes yet. You can simulate this by creating a compound unique index in your DB over those two tables.

I'm also tagging this as a feature request :-)

**Comment by Bobsans** [comment]
thanks :)

**Comment by grigi** [comment]
Hi @Bobsans v0.11.6 #112 should have added this feature.
Please test :-)

**Comment by Bobsans** [comment]
Yes. It's works.
