### ISSUE TITLE
`bulk_update` errors when setting `null` for a smallint column on postgres 

### ISSUE THREAD

**Issue by Rongronggg9** [tortoise/tortoise-orm#1086]
**Describe the bug**
When `bulk_update` setting null for a smallint column, error occurs:
```
column "aNullableSmallInt" is of type smallint but expression is of type text
HINT:  You will need to rewrite or cast the expression.
```
This bug seems to only exist on PostgreSQL. SQLite works fine. (MySQL not tested.)

**To Reproduce**
```py
class Table(Model):
    id = fields.IntField(pk=True)
    aNullableSmallInt = fields.SmallIntField(null=True)
```
```py
for t in ts:
    t.aNullableSmallInt = None
await Table.bulk_update(ts, ('aNullableSmallInt',))
```

**Expected behavior**
No error occurs.

**Additional context**
tortoise tries to execute
```pgsql
UPDATE "Table" SET "aNullableSmallInt"=CASE WHEN "id"=1 THEN null WHEN "id"=2 THEN null END WHERE "id" IN (1,2)
```

**Comment by long2ice** [comment]
Current you can use `t.aNullableSmallInt = Cast(None, "smallint")`, later will do it automatically
