### ISSUE TITLE
Tortoise ORM is based on mysqlclient or PyMySql?

### ISSUE THREAD

**Issue by Achilles0509** [tortoise/tortoise-orm#1092]
There are 2 popular `MySQL` adapters for `Python` that are currently maintained.
- `mysqlclient`
- `PyMySql`

As my experience `PyMySql` is slower than `mysqlclient` because `mysqlclient` is based on  `C` library.

`Tortoise ORM` is based on `mysqlclient` or `PyMySql`?

**Comment by long2ice** [comment]
[asyncmy](https://github.com/long2ice/asyncmy)

**Comment by Achilles0509** [comment]
According to [benchmark](https://github.com/long2ice/asyncmy#benchmark) result in `asyncmy` repository, `asyncmy` is faster than `aiomysql`.
But in `tortoise-orm` documentation mention about `aiomysql` first, then `asyncmy`.
Is there any special reason?

![image](https://user-images.githubusercontent.com/79822851/160174015-c8bf1286-c5f4-46f0-8b56-e9a624ba1c17.png)

**Comment by Achilles0509** [comment]
And it seems basically `tortoise-orm` is based on `PyMySql` i.e. pure Python approach instead of use `C` library.
It will make the `ORM` slower.

I know `C` libraries do not work with `monkeypatch` using `gevent`, `eventlet`.
`C` libraries are problem with `asyncio` too?
