### ISSUE TITLE
Docs at readthedocs.io are outdated

### ISSUE THREAD

**Issue by janusheide** [tortoise/tortoise-orm#1096]
**Describe the bug**
The read the docs docs are not up to date, so if they are not getting updated any longer, maybe better to just take them down?

**To Reproduce**
https://tortoise-orm.readthedocs.io/en/latest/#

**Comment by long2ice** [comment]
Sure but I have no permissions, need @abondar help

**Comment by l1f** [comment]
is there anything new here yet?

**Comment by bhch** [comment]
Yeah, docs definitely need to be updated. A lot of the new features, such as `bulk_update`, `ArrayField`, etc. I didn't know existed until I saw the changelog.

**Comment by Ivoz** [comment]
I think @grigi might also be able to help if they're around

**Comment by Cikmo** [comment]
if [https://tortoise-orm.readthedocs.io/en/latest/](https://tortoise-orm.readthedocs.io/en/latest/) isn't going to be updated, it should probably be deleted. At the moment the first google result for "tortoise orm docs/documentation" is readthedocs, and so are most other tortoise related google searches. If [https://tortoise.github.io/](https://tortoise.github.io/) is the replacement, make it the only one.

**Comment by grigi** [comment]
Sorry, I was stuck in an immigration hell and completely lost track of everything. I sent you an invite to your gmail @long2ice
