### ISSUE TITLE
How to remove the not-null constraint, so that the model allows the value None in the foreign key

### ISSUE THREAD

**Issue by Fallern** [tortoise/tortoise-orm#1099]
tortoise.exceptions.IntegrityError: null value in column "group_id" of relation "users_tg" violates not-null constraint - exception. Here's the code models.

![image](https://user-images.githubusercontent.com/48813221/162132053-c8f8604d-9c64-4a5f-9c1f-0103065d8b17.png)

When trying to insert the "UseTg" model in the "group" field into the model, the value None causes an error, how to fix it.
![image](https://user-images.githubusercontent.com/48813221/162131885-12677d58-45c1-4078-a8ac-19288965a2f6.png)

**Comment by long2ice** [comment]
Check the fk in your db
