### ISSUE TITLE
cannot import name 'Q' from 'tortoise.query_utils'

### ISSUE THREAD

**Issue by sagar-arya** [tortoise/tortoise-orm#1106]
I am trying to make use of Q from query_utils. When I try to do it, I get 
`cannot import name 'Q' from 'tortoise.query_utils'`
error

using tortoise-orm: 0.19.0
Has anyone faced this issue?

**Comment by long2ice** [comment]
See https://github.com/tortoise/tortoise-orm/releases/tag/0.18.0 changelog
