### ISSUE TITLE
OperationalError after retrieving row from db by id, manually assigning the value from IntEnum to the relevant attribute of the model instance and calling `save()` on it.

### ISSUE THREAD

**Issue by croshchupkin** [tortoise/tortoise-orm#113]
Basically, subj. To repro, please use the following code:
```
# models.py
from enum import IntEnum

from tortoise import Model, fields


class ContactTypeEnum(IntEnum):
    home = 1
    work = 2
    other = 3


class Contact(Model):
    id = fields.IntField(pk=True)
    phone_no = fields.CharField(30, null=False, default='')
    type = fields.IntField(required=True, default=ContactTypeEnum.other)
```
Then run the script:
```
from tortoise import run_async, Tortoise

from models import Contact, ContactTypeEnum


async def run():
    await Tortoise.init(
        db_url='sqlite://db.sqlite3',
        modules={'models': ['models']}
    )
    await Tortoise.generate_schemas()

    await Contact.create(phone_no='222', type=ContactTypeEnum.work)

    breakpoint()
    contact = await Contact.get(id=1)
    for name, value in {'phone_no': '1111', 'type': ContactTypeEnum.other}.items():
        setattr(contact, name, value)
    await contact.save()


if __name__ == '__main__':
    run_async(run())
```
I get the following exception: tortoise.exceptions.OperationalError: no such column: ContactTypeEnum.other. But before the update, the new model instance was saved successfully.

**Comment by croshchupkin** [comment]
After having stepped through the code for a bit, it seems, that pypika constructs the following SQL query: ```UPDATE "contact" SET "phone_no"='1111',"type"=ContactTypeEnum.other```

**Comment by croshchupkin** [comment]
I assume that the query will work fine if I do int(ContactTypeEnum.other) - but I just find it strange that the entity is created without issue while the update has problems.

**Comment by croshchupkin** [comment]
After digging around some more, I think this is most likely not a bug, but a "feature" of Enum's default `__str__`. This can be tweaked by creating the enum like so:
```
class ContactTypeEnum(IntEnum):
    home = 1
    work = 2
    other = 3

    def __str__(self):
        return str(self._value_)
```

**Comment by grigi** [comment]
Creates are done using parametrized queries, updates/selects are not yet.
related to #81

**Comment by grigi** [comment]
Could you add this as some failing tests that are marked with `@test.expectedFailure` that does insert/update and filter on an enumfield?
The same feature also blocks dealing with binary blobs.

**Comment by croshchupkin** [comment]
Ok, I'll try to do this later today.

**Comment by croshchupkin** [comment]
Some Travis builds are failing for the pull request, but I'm not exactly sure why...

**Comment by grigi** [comment]
I had a look, and it is because the linter complained about import order:
```
flake8 tortoise/ examples/ setup.py conftest.py
tortoise/tests/test_update.py:2:1: I001 isort found an import in the wrong position
Makefile:27: recipe for target 'check' failed
make: *** [check] Error 1
```
I tried to document some basic guidelines here: https://tortoise-orm.readthedocs.io/en/latest/CONTRIBUTING.html#style

But basically all it means is that an import at line 2 of test_update.py isn't according to the isort (https://github.com/timothycrosley/isort) spec.

Basically run `isort tortoise/tests/test_update.py` or `make style`.

It will update imports to be grouped and sorted:
```py
from tortoise.tests.testmodels import Event, Tournament, Contact, ContactTypeEnum
```
to
```py
from tortoise.tests.testmodels import Contact, ContactTypeEnum, Event, Tournament
```

**Comment by REVIMI** [comment]
@croshchupkin You are trying to save something other than INT to IntField

```
In [2]: type(ContactTypeEnum.work)                                                                                                                                                                                             
Out[2]: <enum 'ContactTypeEnum'>

In [3]: type(ContactTypeEnum.work.value)                                                                                                                                                                                       
Out[3]: int
```
It's normal behavior. The only change that is required is to provide a readable exception.

P.S. You can use something like an EnumField used in the test suite:
```
class Contact(Model):
    id = fields.IntField(pk=True)
    type = EnumField(enum_type=ContactTypeEnum, default=ContactTypeEnum.other)
```
