### ISSUE TITLE
pydantic_model_creator cannot create two interfaces for the same model

### ISSUE THREAD

**Issue by StevenLianaL** [tortoise/tortoise-orm#1130]
Prototypes = pydantic_model_creator(models.Prototypes)
NewPrototype = pydantic_model_creator(models.Prototypes, exclude=('id', 'created'))

When pydantic_model_creator is called a second time for Prototypes, pydantic_model_creator directly returns the result of the first call stored in **_MODEL_INDEX**.

`_MODEL_INDEX={'app.models.Prototypes.leaf': <class 'abc.app.models.Prototypes.leaf'>}
`

Code Position: tortoise/contrib/pydantic/creator.py  397 line
`    # Here we de-dup to ensure that a uniquely named object is a unique object
    # This fixes some Pydantic constraints.
    if _name in _MODEL_INDEX:
        return _MODEL_INDEX[_name]
`

**Comment by long2ice** [comment]
Just pass `name` param manual
