### ISSUE TITLE
Allow querying / updating of database columns not present on a Tortoise MODEL class.

### ISSUE THREAD

**Issue by alexf-bond** [tortoise/tortoise-orm#1136]
It would be helpful in my use case to be able to query or update columns not actually present on the model.  Pypika for instance allows you to specify any tables / columns and join across them in the database.  

**Describe the solution you'd like**
It'd be nice to have this flexibility shifted up into Tortoise itself so I can make use of QuerySets across the code and not have to shift to pypika to query columns not present on a model.

I'm sure there was a design decision to now allow this / too much overhead involved in supporting it.  I know there is probably alot of property resolution happening when constructing / executing Tortoise queries that would have to be re-worked.  But I'd be happy to dig deeper into my particular situation.  

Thanks!

**Comment by long2ice** [comment]
Can you show the use case?

**Comment by alexf-bond** [comment]
Just decided to use PyPika directly @long2ice.  Seems to be easier in a lot of cases.
