### ISSUE TITLE
Virtual fields (has_db_field=False) being includes in generated sql

### ISSUE THREAD

**Issue by alexf-bond** [tortoise/tortoise-orm#1138]
**Describe the bug**
We have a model defined which contains 4 fields with `has_db_field=False `set.  When performing a `.all()` on the model the virtual columns are included in the select columns resulting in a `tortoise.exceptions.OperationalError: column "xxxx" does not exist` exception.

**To Reproduce**
Define a model with an arbitrary virtual column and attempt to query with a filter:

```
class TestModel(Model):
    name = fields.CharField(max_length=255, null=True)
    created_at = fields.DatetimeField()
    virtual_column_a = fields.UUIDField(has_db_field=False, null=True)
    virtual_column_b = fields.UUIDField(has_db_field=False, null=True)


results =  await TestModel.filter(
  Q(name="alex")
  & Q(date_created__lte=datetime.now())
).all()
```

**Expected behavior**
Would expect the virtual columns not to be included in the generated sql column select list.  What's the purpose of this flag if it's still included in select statement and db creation when testing?

**Additional context**
`tortoise-orm = "=0.18.1"`
`asyncpg 0.25.0`
`pypika-tortoise 0.1.3`
`postgres`

**Comment by alexf-bond** [comment]
What is the usecase for this flag then?

**Comment by alexf-bond** [comment]
Ended up using PyPika directly, closing.

**Comment by achalagarwal** [comment]
@alexf-bond 

#### Here's my two cents after a quick superficial check of the codebase (so I could be wrong):

I can see that `has_db_field=False` prevents the field from being added to `fields_db_projection` and that is needed to generate the correct query (i.e. ignoring the specific field in the select columns)

However, at one place, the above condition is being violated. Specifically in `_search_for_field_attributes` we always update ` fields_db_projection[key] = value.source_field or key` regardless of the `has_db_field value`.

Fixing that could solve the issue at the root for you.

BTW, I am quite curious about how you solved it using PyPika. Care to share? 🙏🏽
