### ISSUE TITLE
Enum Values

### ISSUE THREAD

**Issue by sagar-arya** [tortoise/tortoise-orm#1140]
**Is your feature request related to a problem? Please describe.**
I have an enum field that looks like this
```
class UserType(int, Enum):
    ALPHA = 1
    BETA = 2
  

class User(models.Model):
    id = fields.IntField(pk=True)
    user_type = fields.IntEnumField(UserType)

```
When I do a query using
```
 result = await User.filter()
```
It would be better if we get response
`[{"id":1, "user_type": "ALPHA"}]`
rather than
`[{"id":1, "user_type": 1}]`

Not sure if this is already available.
Would be a great help if I can get a help on this

**Comment by long2ice** [comment]
use str enum instead

**Comment by waketzheng** [comment]
@sagar-arya You can add a computed field:
```py
from enum import IntEnum

class UserType(IntEnum):
    ALPHA = 1
    BETA = 2 


class User(models.Model):
    id = fields.IntField(pk=True)
    user_type = fields.IntEnumField(UserType)

    def user_type_name(self) -> str:
        return self.user_type.name

    class PydanticMeta:
        computed = ['user_type_name']
```
