### ISSUE TITLE
Cannt import name connection

### ISSUE THREAD

**Issue by mr-far** [tortoise/tortoise-orm#1145]
`Traceback (most recent call last):
  File "C:\Users\danil\Desktop\Py-cord\lwbot\LWbot\cog.py", line 2, in <module>
    from core import config, lib
  File "C:\Users\danil\Desktop\Py-cord\lwbot\LWbot\core\lib.py", line 5, in <module>
    from tortoise.models import Model
  File "C:\Users\danil\AppData\Local\Programs\Python\Python310\lib\site-packages\tortoise\models.py", line 25, in <module>
    from tortoise import connections
ImportError: cannot import name 'connections' from 'tortoise' (unknown location)`

How can i fix it?

**Comment by andyfcx** [comment]
Check your installation: `pip list | grep tortoise`
maybe you misinstalled a package called `tortoise` (https://pypi.org/project/tortoise/), it's not this orm.
Reinstall all.

**Comment by mr-far** [comment]
> Check your installation: `pip list | grep tortoise`
> 
> maybe you misinstalled a package called `tortoise` (https://pypi.org/project/tortoise/), it's not this orm.
> 
> Reinstall all.

Yea, I installed `tortoise` instead of `tortoise-orm`

**Comment by mr-far** [comment]
`tortoise` was installed instead of `tortoise-orm`
