### ISSUE TITLE
Is there any way to use master db when select

### ISSUE THREAD

**Issue by hyeongguen-song** [tortoise/tortoise-orm#1158]
I use router for separate master/slave db
but replication lag makes some trouble with me

As a title, Is there any way to use master db when select
(or plan for this feature)

**Comment by long2ice** [comment]
Just use `using_db` or transaction

**Comment by hyeongguen-song** [comment]
> Just use `using_db` or transaction

`using_db` can use with `Model.filter()`?

**Comment by long2ice** [comment]
`Model.filter().using_db()`

**Comment by hyeongguen-song** [comment]
@long2ice thx ..!
