### ISSUE TITLE
Queries by different tasks produce different instances of Model objects for same rows

### ISSUE THREAD

**Issue by davidmcnabnz** [tortoise/tortoise-orm#1180]
Hi there,

I need a way to ensure that if multiple tasks in an asyncio thread each perform queries on tables, and end up with row objects (instances of models.Model subclasses) representing the same rows, then all row objects produced from Tortoise queries, representing the same underlying table/row, will be singletons.

Usage scenario is a server with dozens or hundreds of worker tasks in the same process, all retrieving row objects, all updating these and saving these back. There will be multiple cases where 2 or more tasks can be working on the same table/row object, and each task needs to be able to hold an object for several seconds at a time without causing other tasks to wait on locks.

I've noticed that if 2 or more tasks perform a query and get an object for the same table/row, then each task will be given a whole different instance of the table class. This of course is a huge integrity issue.

So given a (hypothetical) scenario like

```
class Foo(models.Model):
    id = models.IntField(pk=True)
    # other fields follow, not important here
    
class Bar(models.Model):
    id = models.IntField(pk=True)
    foo = models.ForeignKeyField('mymodels.Foo', related_name='bars', null=True)
    # other fields follow, not important here
```
I need a way to ensure that if:
1. task 'alice' does a query on table 'Foo' and gets Foo instance 'foo' (id=54), then
2. task 'bob' does a query on table 'Bar' and gets a Bar instance 'bar' (id=33), then
3. task 'bob' awaits on bar.foo to get the related Foo instance 'foo' (id=54), then
4. task 'alice' iterates over its 'foo.bars' and among these ends up with a Bar instance 'bar' (id=33)
5. task 'charlie' does queries on both 'Foo' and 'Bar', and ends up with a Foo instance (id=54) and a Bar instance (id=33)

Then:
1. the instance of Foo with id=54 held by tasks alice, bob and charlie is the exact same Python object, and
2. the instance of Bar with id=33 held by alice, bob and charlie is the same object (not different Bar instances)
3. there is no delay to alice, bob or charlie in their queries resulting from underlying locks

Is this possible in Tortoise ORM? If so, can someone please point me to a straightforward example?

**Comment by abondar** [comment]
This is not possible for tortoise, and I think this is too narrow case to implement such thing

In your case I recommend to build your own repository of objects, that will be facade before your tables
As long as you are within one process you should be able to manage it quite easily

**Comment by davidmcnabnz** [comment]
Thanks for that, Andrey. In fact, I've made some earlier progress on such a 'repository' of objects, via a table of weakrefs classified by Model subclass. This is working well on the whole, but I need to sort a couple of memory leak issues, as well as a credible way to briefly lock specific columns for very short update periods. 

Although it would have been nice to get this functionality within Tortoise, I appreciate your confirmation that this won't be supported, since it validates the approach I'm taking.

Thanks again :)
David
