### ISSUE TITLE
Complete documentation for ArrayField

### ISSUE THREAD

**Issue by deadaf** [tortoise/tortoise-orm#1187]
Disclaimer: This is my first issue ever on github so kindly correct me if my format is incorrect.

I see that tortoise-orm now supports `ArrayField` with the `0.19.0` update but I couldn't find the documentation regarding that anywhere,
neither in https://tortoise.github.io/ nor in https://tortoise-orm.readthedocs.io/en/latest/

Also since the documentation isn't completed yet or maybe I couldn't find ArrayField in docs, can you please attach an example snippet of ArrayField in use?

**Comment by HelgeKrueger** [comment]
I was also looking for this. The code for array field is at: https://github.com/tortoise/tortoise-orm/blob/main/tortoise/contrib/postgres/fields.py

The documentation should probably be at: https://tortoise.github.io/contrib/postgres.html

If there is no objection to it, I can create a pull request adding the:

```
.. autoclass:: tortoise.contrib.postgres.fields.ArrayField
```

to https://github.com/tortoise/tortoise-orm/blob/main/docs/contrib/postgres.rst
