### ISSUE TITLE
Is it possible to use relative paths for models?

### ISSUE THREAD

**Issue by Cikmo** [tortoise/tortoise-orm#1203]
I am using tortoise for a package, but I can't seem to find a good way to import the models from the submodule of the package. Is this not possible? Only way I could see it working, is with the use of relative imports, but this gives me the error `TypeError: the 'package' argument is required to perform a relative import for '.models'`.

Some help would be much appreciated.

**Comment by jaxlo** [comment]
I ran into the same problem. I would love to spend some time on a pull request for this. I'm just not sure where to get started
