### ISSUE TITLE
Add a description property on field

### ISSUE THREAD

**Issue by rockstar** [tortoise/tortoise-orm#124]
Many ORMs have the ability to add a description of what the field is. This allows consumers to build automated documentation tooling based on the declarative model api.  Consider the following:

```
class Employee(Model):
    """An employee of Super Mega Corp."""

    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=1024)
    cleared = fields.BooleanField(default=False, description="Whether the employee has read the employee handbook and signed the company NDA and is cleared for work.")
```

We could then look at `Employee.cleared.description` and get prose about what the field is for.

**Comment by grigi** [comment]
It certainly can be done, and should be easy to do as well :-)
