### ISSUE TITLE
"'TransactionWrapper' object has no attribute 'schema'" with asyncpg

### ISSUE THREAD

**Issue by rodalmeida** [tortoise/tortoise-orm#1241]
**Describe the bug**
When running queries within a transaction we do randomly get a 
`'TransactionWrapper' object has no attribute 'schema'`
This is happening on the latest version 0.19.2

```
AttributeError: 'TransactionWrapper' object has no attribute 'schema'
  File "tortoise/queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "tortoise/backends/base/executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
  File "tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
    return await func(self, *args, **kwargs)
  File "tortoise/backends/asyncpg/client.py", line 129, in execute_query
    async with self.acquire_connection() as connection:
  File "tortoise/backends/base/client.py", line 220, in __aenter__
    await self.ensure_connection()
  File "tortoise/backends/base/client.py", line 216, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "tortoise/backends/asyncpg/client.py", line 40, in create_connection
    if self.schema:
```

After looking at the code it seems like the issue was introduced with this commit https://github.com/tortoise/tortoise-orm/commit/9709355cbe6029631af1d8126bc075b7ae943bed# in the following line https://github.com/tortoise/tortoise-orm/blob/1c0dbbf69245dcead3d87a837ff203b15fdb80c2/tortoise/backends/asyncpg/client.py#L170

this (I think) should return `return ConnectionWrapper(self._lock, self._parent)` instead, as `self` is just the wrapper.

**Comment by blazing-gig** [comment]
@rodalmeida Hey, could you help with the code that's causing this issue ? And also include a snapshot of the python version, asyncpg version etc that you're using ? It would help in debugging/reproducing the issue. Any additional info would help as well. Thanks.

**Comment by rodalmeida** [comment]
hey @blazing-gig, sorry for the late reply on this, I am going to close this because our main issue was having multiple threads sharing the same connection, so connections were being closed when still in use.
