### ISSUE TITLE
Cannot import name 'ClickHouseQuery' from 'pypika.dialetcs'

### ISSUE THREAD

**Issue by Alex1995markson** [tortoise/tortoise-orm#1300]
**Describe the bug**
When I starting my FastApi application happened this  bug
Cannot import name 'ClickHouseQuery' from 'pypika.dialetcs' 

Python 3.10 , postgres 13.0
My dependencies is 
tortoise-orm ="0.19.2",
PyPika =  "0.48.9"

**To Reproduce**
Staring command:
python manage.py runserver

And in cli:
 from tortoise import fields, models
  _**File "/Users/sasamacenko/Library/Caches/pypoetry/virtualenvs/web-pmt-backend-3n8ek4Wi-py3.10/lib/python3.10/site-packages/tortoise/__init__.py", line 11, in <module>
    from pypika import Table
  File "/Users/sasamacenko/Library/Caches/pypoetry/virtualenvs/web-pmt-backend-3n8ek4Wi-py3.10/lib/python3.10/site-packages/pypika/__init__.py", line 34, in <module>
    from pypika.dialects import (
ImportError: cannot import name 'ClickHouseQuery' from 'pypika.dialects' (/Users/sasamacenko/Library/Caches/pypoetry/virtualenvs/web-pmt-backend-3n8ek4Wi-py3.10/lib/python3.10/site-packages/pypika/dialects/__init__.py)**_

**Expected behavior**

**Additional context**
If i delete lines in virtualenviroment of pypi-package pypika  (file __init__.py)

from pypika.dialects import (
    ClickHouseQuery, delete this
    Dialects, delete this
    MSSQLQuery,
    MySQLQuery,
    OracleQuery,
    PostgreSQLQuery,
    RedshiftQuery, delete this
    SQLLiteQuery,
    VerticaQuery,
)

All works, but I suppose this not right way

**Comment by provinzkraut** [comment]
Any updates on this?

**Comment by Alex1995markson** [comment]
> Any updates on this?

What do you mean? Do you have the same problem?

**Comment by SchmiedmayerStephan** [comment]
Had the same problem, I think it was because I installed pypika while using tortoise.
Deleting the poetry environment and installing from scratch worked for me.

**Comment by jiangying000** [comment]
official pypika may overwrites [pypika-tortoise](https://github.com/tortoise/pypika-tortoise), makes the import error

**Comment by jiangying000** [comment]
> official pypika may overwrites [pypika-tortoise](https://github.com/tortoise/pypika-tortoise), makes the import error

In my case

chroma -> official pypika
tortoise -> Tortoise pypika

pypika from chroma overwrites pypika from tortoise

**Comment by abondar** [comment]
@henadzit @waketzheng may be we should rename module in pypika-tortoise, so it doesn't clash with original pypika? As we are not really presenting it as drop-in replacement

**Comment by waketzheng** [comment]
Agree! I prefer `pypika_tortoise` as it can be installed by `pip install pypika_tortoise`.

**Comment by henadzit** [comment]
@abondar @waketzheng sounds like we need to do it.

**Comment by waketzheng** [comment]
OK, let me do it.

**Comment by licongy** [comment]
> > official pypika may overwrites [pypika-tortoise](https://github.com/tortoise/pypika-tortoise), makes the import error
> 
> In my case
> 
> chroma -> official pypika tortoise -> Tortoise pypika
> 
> pypika from chroma overwrites pypika from tortoise

I'm experiencing the same thing, when will the renamed pypika_tortoise be released?
Also, changing from chroma to weaviate would be a good idea to solve the problem

**Comment by henadzit** [comment]
@licongy there are a few PRs that we would like to get in as part of the next release but we should be able to release soon, hopefully, this week.
