### ISSUE TITLE
some problems in use tortoise create Database 

### ISSUE THREAD

**Issue by JieZhaoAllen** [tortoise/tortoise-orm#132]
**Describe the bug**
Question 1：
When I used aiomysql to create my database ，i use this setting:
DB_URL = 'mysql://root:123456@localhost:3306/test?charset=utf8'  
although I set charset = utf8, but it's useless. After creating the database, the encoding of the database is not utf8.

Question 2：
When I use  '_create_db = False' , if I don't have a name is 'test'  table in mysql, I fail to create it.

**Comment by grigi** [comment]
Re question 1, it seems that we filter the parameters when passing it to the DB driver. Consider it a bug we need to fix.

Re question 2, Could you please provide some more info?

**Comment by grigi** [comment]
Please test if v0.11.11 resolves "question 1" for you.
