### ISSUE TITLE
Reconnect to Postgres

### ISSUE THREAD

**Issue by shaloba** [tortoise/tortoise-orm#134]
First of all I know this issue probably asyncpg related but still want to raise it here since this package relay on it. so if you have any idea how to recover this issue i will be grateful 

**Describe the bug**
ORM is not reconnect

**To Reproduce**

1. connect to postgres instance
2. restart postgres
3. try to execute query within the existing python process 
4. see exception

**Expected behavior**
1. reconnect when postgres instance is up

**Additional context**
Trace-back1

```
Traceback (most recent call last):
  File \"/usr/lib/python3.6/asyncio/selector_events.py\", line 714, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/models.py\", line 277, in create
    await instance.save(using_db=kwargs.get('using_db'))
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/models.py\", line 221, in save
    await self._insert_instance(*args, **kwargs)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/models.py\", line 210, in _insert_instance
    ).execute_insert(self)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/backends/base/executor.py\", line 77, in execute_insert
    instance.id = await self.db.execute_insert(query, values)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/backends/asyncpg/client.py\", line 22, in wrapped
    return await func(self, query, *args)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/tortoise/backends/asyncpg/client.py\", line 108, in execute_insert
    stmt = await connection.prepare(query)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/asyncpg/connection.py\", line 403, in prepare
    return await self._prepare(query, timeout=timeout, use_cache=False)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/asyncpg/connection.py\", line 408, in _prepare
    use_cache=use_cache)
  File \"/home/shlomy/PycharmProjects/playground/venv36/lib/python3.6/site-packages/asyncpg/connection.py\", line 329, in _get_statement
    statement = await self._protocol.prepare(stmt_name, query, timeout)
  File \"asyncpg/protocol/protocol.pyx\", line 163, in prepare
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation"}
```

Trace back 2
```
connection is closed", "level": "error", "logger": "app.controller", "timestamp": "2019-05-23 12:30:55", "exception": "Traceback (most recent call last):
    result = await orm_class.filter(id__in=kwargs['devices_ids']).all()
  File \"/usr/local/lib/python3.7/site-packages/tortoise/queryset.py\", line 442, in _execute
    self.query, custom_fields=list(self._annotations.keys())
  File \"/usr/local/lib/python3.7/site-packages/tortoise/backends/base/executor.py\", line 28, in execute_select
    raw_results = await self.db.execute_query(query.get_sql())
  File \"/usr/local/lib/python3.7/site-packages/tortoise/backends/asyncpg/client.py\", line 22, in wrapped
    return await func(self, query, *args)
   File \"/usr/local/lib/python3.7/site-packages/tortoise/backends/asyncpg/client.py\", line 115, in execute_query
    return await connection.fetch(query)
  File \"/usr/local/lib/python3.7/site-packages/asyncpg/connection.py\", line 420, in fetch
    self._check_open()
  File \"/usr/local/lib/python3.7/site-packages/asyncpg/connection.py\", line 1147, in _check_open
    raise exceptions.InterfaceError('connection is closed')
asyncpg.exceptions._base.InterfaceError: connection is closed"}
```

**Comment by grigi** [comment]
Hi Shaloba, thank you for reporting.
We had to handle an equivalent issue for MySQL, so we should handle it as well.

**Comment by shaloba** [comment]
@grigi  thanks for the reply, I understood that "asyncpg" library support reconnecting when using connection pool. 
Do you have ETA by chance for this issue ?

**Comment by grigi** [comment]
I was already busy with it right now, just cleaning up.

**Comment by grigi** [comment]
Please test v0.11.12 as that should fix the issue (I tested manually using the quart example and doing dastardly things to the postgres service).

PS: Would still like to figure out how to automate these various kinds of issues in a reliable way…

**Comment by shaloba** [comment]
@grigi Thanks for the quick fix!

I tested the disconnection scenario with new version: **0.11.12**

The client seems to recover from the disconnection **but** the first query returned empty list and the seconds one return list containing the results from the DB

my guess is that when the client noticed the connection lost he reconnect but not running (or waiting for the connection to fully established again) and that is why the first query after the reconnect return empty result. 

Can you please verify this one ? 

Thanks :)

**Comment by grigi** [comment]
My sample doesn't have the same behaviour :disappointed: 

@shaloba Could you give me a very simple example that gives your behaviour, and what your environment is? e.g. py3.6 or py3.7, version of mysql/maria db.  Is the DB over a network or on the localhost?

Then I'll try and replicate it.

**Comment by shaloba** [comment]
@grigi  sure! 

The situation is very simple: 
I have an REST API SERVER (aiohttp) that get request to retrieve users by account ID (I have couple of users in the DB).

I created two python environments: 
1. running tortoise 0.11.8
2. running tortoise 0.11.12

I send 2 HTTP requests (one for each HTTP server running the different tortoise versions) to retrieve the users for certain account. 
#2 request get 500 since "ConnectionNotExist" error raised 
#1 request return me empty list on the first try but the users on the second one (i tried this scenario couple of times to be sure this is the behavior and got the same result each time)  

Python: version 3.6
asyncpg==0.18.3
tortoise-orm==0.11.12

postgres: PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit


Hope the information will be helpful

Thanks!

**Comment by grigi** [comment]
Thanks. I feel a bit embarrased about the MySQL/MariaDB comment. I just got so used to all the bug reports to be about those…

Still, very interesting about duplicate responses.

Looking at the code, it may be because there is a shared lock. Whereas this really is a separate thing to be locked. (e.g. the connection is already owned by a transaction).
This could result in a cursor-on-connection race condition…

Hmm, let me first see about duplicating the issue. (This will take a while for me to spend time on this, my wife is sick so I'm doing double duty with the kids, and we have a large project going live next week. It is perfectly fine to ping here if nothing happens.)

**Comment by shaloba** [comment]
@grigi  
I update my comment . unfortunately the error raised on the **save**  and **create** methods as well

thanks for the care about this issue! hope your wife will feel better !!!

**Comment by shaloba** [comment]
@grigi do you have maybe ETA for this one ? 
thanks :1st_place_medal:

**Comment by grigi** [comment]
@shaloba Does v0.11.13 fix the issue for you?
