### ISSUE TITLE
pymysql.err.InterfaceError: (0, 'Not connected') occurred when I was trying to delete data.

### ISSUE THREAD

**Issue by tufbel** [tortoise/tortoise-orm#1350]
I connected to mysql using Tortoise.init(config=DATABASE_CONFIG), and the rough parameters of DATABASE_CONFIG are as follows:
```python
DATABASE_CONFIG = {
	"connections":{
		"default":{
			"engine": "tortoise.backends.mysql",
			"credentials":{
				"host": "...",
				...
				"minsize":8,
				"maxsize":16,
				"pool_recycle":60,
			}
		}
	}
}
```
When I use it normally, there is no problem, but when my program runs for a long time and executes `MyModel.filter().delete()`, an error of `pymysql.err.InterfaceError: (0, 'Not connected')` occurs. I still get this error even after calling the deletion interface multiple times, but the error disappears after I call it enough times.

How can I solve this problem?

**Comment by shdows** [comment]
I have also encountered this issue. How can I solve it?
