### ISSUE TITLE
register_tortoise() is not compatible with lifespan in fastapis>=0.95.0

### ISSUE THREAD

**Issue by wu-clan** [tortoise/tortoise-orm#1371]
**Describe the bug**
when use lifespan with register_tortoise() in fastapi >= 0.95.0, register_tortoise() is not work

**Comment by wu-clan** [comment]
Hi, @waketzheng 

Here is the tortoise source code: https://github.com/tortoise/tortoise-orm/blob/e78d04cd3e7428c78d1dc7a862b45e73f6d48866/tortoise/contrib/fastapi/__init__.py

Here is the fastapi lifespan: https://fastapi.tiangolo.com/advanced/events/

I just tested my code and there seems to be no more exceptions, but it's recommended to update register_tortoise() to lifespan

**Comment by i701** [comment]
> https://tortoise.github.io/examples/fastapi.html
> 
> This example worked with `fastapi-0.95.1` and `tortoise-orm-0.19.3`
> 
> You may need to describe the bug with detail code @wu-clan

Does this example still work without getting missing `created_at` and  `updated_at` fields error?

**Comment by abondar** [comment]
Added lifespan support in 0.21.0

**Comment by FatXiaoBai** [comment]
我也发现了，register_tortoise放在lifespan里面启动fastapi不报错，就是在数据库操作的时候，直接返回default_connection for the model，放在lifespan外就可以正常工作
