### ISSUE TITLE
Allow `ForeignKeyField(on_delete=NO_ACTION)`

### ISSUE THREAD

**Issue by nc7s** [tortoise/tortoise-orm#1393]
**Is your feature request related to a problem? Please describe.**

I'd like to keep some rows when those their foreign key referenced were deleted, either for inspection or for later reuse.

**Describe the solution you'd like**

Allow that. I'm happy to implement, if you think it's feasible.

**Comment by divadsn** [comment]
You mean https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/fields/base.py#L32?

**Comment by bnoctis** [comment]
Yep, I've used the similar DO_NOTHING in Django (although NO_ACTION seems more formal).
