### ISSUE TITLE
Support for COMMENT

### ISSUE THREAD

**Issue by Baysul** [tortoise/tortoise-orm#148]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Make it so the `description` parameter is used to COMMENT on columns when `Tortoise.generate_schemas` is called, or have a separate field entirely named `comment`. For tables, I'm not sure what the best solution would be, maybe a metadata field?

**Describe alternatives you've considered**
Issuing the COMMENT commands manually.

**Comment by grigi** [comment]
Thank you for the issue report.
We just added a `description="..."` parameter to all fields, and we can use it to omit `COMMENT '...'` when generating DDL.

This actually should be quite easy to do :-)
I confirmed all our supported databases support that syntax. The only "consideration" is that we need to handle basic escaping (at least we don't deal with user input here)

**Comment by harshanarayana** [comment]
@grigi  Can I pick this one up?

**Comment by grigi** [comment]
Sure!

**Comment by grigi** [comment]
Thanks to @harshanarayana we have initial support for this in v0.12.3 \o/
