### ISSUE TITLE
`Model.filter(column__filter={...})` on nested json value not working as excepted

### ISSUE THREAD

**Issue by elder-frog** [tortoise/tortoise-orm#1480]
I hava a JSONField with column name `config` with some data like
```
=============================================
id | config
=============================================
1  | {"account": ["a", "b"]}
---------------------------------------------
2  | {"account": ["b", "c"]}
=============================================
```
I want to build a SQL as
```sql
SELECT *
FROM config_table
WHERE config -> 'account' @> '["a"]'
```
this code working well in raw sql, and when I use tortoise doing this in these code, tortoise generate wrong sql code
```python
print(ConfigTable.filter(config__filter={"account__contains": ["a"]}).as_query())

# output:
# SELECT "id","config" FROM "config_table" WHERE "config"->'account'->>'contains'=1
```
I read some tortoise source code, in [json_functions.py#L19](https://github.com/tortoise/tortoise-orm/blob/c030c9cebd7aba2697832d9c4769428805238f73/tortoise/contrib/postgres/json_functions.py#L19), seems not support query using contains in nested json?

**Comment by henadzit** [comment]
The correct query for what you want to achieve would be `DocumentJson.filter(config__contains={"account": ["a"]})`. `__contains` in `__filter` is actually going to do a `LIKE` filter.
