### ISSUE TITLE
update trigger 3 time 

### ISSUE THREAD

**Issue by xalteropsx** [tortoise/tortoise-orm#1494]
@long2ice  ur  update method why u trigger it 3 time

**Comment by xalteropsx** [comment]
```py

@router.put("/user/{user_id}")
async def update_user(user_id: int, user: UserIn_Pydantic):
    stored_item_data = await Users.get(id=user_id)
    for key, value in user.model_dump(exclude_unset=True).items():
        if value is not None:
            setattr(stored_item_data, key, value)
    print(stored_item_data)
    return stored_item_data

```

**Comment by xalteropsx** [comment]
```py
   # here we call database 3 time first we filter , 2nd we update it , 3rd we recall it 
    await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))
    return await User_Pydantic.from_queryset_single(Users.get(id=user_id))
```

**Comment by xalteropsx** [comment]
return await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))    if we can able return this object would be more better

**Comment by YAGregor** [comment]
can't under understand what are you saying, 
```
 await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))
```
this expression should only trigger update **once**, it returns how many lines it effect, and it's a common pattern.
>  return this object would be more better

not a goods idea

**Comment by xalteropsx** [comment]
@YAGregor  in the above case / 1. database inflict filter to match which data need to update  2, database update its data 
3. u refetch the data back

**Comment by YAGregor** [comment]
> my question why not u return at the moment u update the data

it's limit of SQL.`await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))`execute one line SQL only(`update user set field=... where ...`), in first step, it does **not** fetch data.

the SQL it generate ` update user set field=... where ...`  just return how many  rows it effect, and in many case just need it, so it's nature that returning effect lines count.and fetching data while update need to execute one more line SQL, which will slow down ORM

**Comment by YAGregor** [comment]
> ```python
>    # here we call database 3 time first we filter , 2nd we update it , 3rd we recall it 
>     await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))
>     return await User_Pydantic.from_queryset_single(Users.get(id=user_id))
> ```

in this two lines code, database was called twice only

**Comment by xalteropsx** [comment]
> > my question why not u return at the moment u update the data
> 
> it's limit of SQL.`await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))`execute one line SQL only(`update user set field=... where ...`), in first step, it does **not** fetch data.
> 
> the SQL it generate ` update user set field=... where ...` just return how many rows it effect, and in many case just need it, so it's nature that returning effect lines count.and fetching data while update need to execute one more line SQL, which will slow down ORM

what in the case of only 1 object update rather effect other row which matches to update ? should not we use .get(id).update when to update instead .filter(id).update

**Comment by YAGregor** [comment]
> > > my question why not u return at the moment u update the data
> > 
> > 
> > it's limit of SQL.`await Users.filter(id=user_id).update(**user.model_dump(exclude_unset=True))`execute one line SQL only(`update user set field=... where ...`), in first step, it does **not** fetch data.
> > the SQL it generate ` update user set field=... where ...` just return how many rows it effect, and in many case just need it, so it's nature that returning effect lines count.and fetching data while update need to execute one more line SQL, which will slow down ORM
> 
> what in the case of only 1 object update rather effect other row which matches to update ? should not we use .get(id).update when to update instead .filter(id).update isnt filter is bad idea for only 1 unique id to be update why filter all of the row

I don't think `Model.get().update()` is necessary, firstly is just the same with
```
model = await Model.get(id=1)
model.field = value
await model.save()
```
just a little longer

and tortoise ORM's API is almost the same with Django ORM, it's better to keep similar with django ORM, in DRF we use serializer to update model, and there is no serializer for tortoise, you have to build your own(but serializer is in tortoise's dev plan)
```
@router.put("/user/{user_id}")
async def update_user(user_id: int, user: UserIn_Pydantic):
    stored_item_data = await Users.get(id=user_id)
    for key, value in user.model_dump(exclude_unset=True).items():
        if value is not None:
            setattr(stored_item_data, key, value)
    print(stored_item_data)
    return stored_item_data
```
obviously your alternative also works but its just an example, both way is ok.

**Comment by xalteropsx** [comment]
@YAGregor sorry for disturbance how do u rollback at exception ? database: Session = Depends(get_db)    except IntegrityError:
        database.rollback()

**Comment by YAGregor** [comment]
> @YAGregor sorry for disturbance how do u rollback at exception ? database: Session = Depends(get_db) except IntegrityError: database.rollback() this is sqlalchmey example

I even study a lot on this question, for fastapi, there is no way in fact, you have to write 
```
with session() as session:
    ...
```
otherwise transaction will commit, even exception interrupt the view.

**Comment by xalteropsx** [comment]
> > @YAGregor sorry for disturbance how do u rollback at exception ? database: Session = Depends(get_db) except IntegrityError: database.rollback() this is sqlalchmey example
> 
> I even study a lot on this question, for fastapi, there is no way in fact, you have to write
> 
> ```
> with session() as session:
>     ...
> ```
> 
> otherwise transaction will commit, even exception interrupt the view.

i saw the transaction doc that it rollback automatic but how do we catch the expection to make the logs

**Comment by YAGregor** [comment]
> i saw the transaction doc that it rollback automatic but how do we catch the expection to make the logs
> 
> no idea about where that session came from are u mean session = transaction

it's a complex question and it's off topic, you may come up with a question on stackoverflow

**Comment by xalteropsx** [comment]
@YAGregor bro 1 last question i am stuck i cannot find any docs plz help

except IntegrityError as e:
    # Access the original database exception through .orig
    original_exception = e.orig   this is sqlalchmey while their is nothing orig in tortoise how do we get actual error

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/fb80afb5-a820-4c78-87ba-70650f69389a)
is this doesnt tell what the actual error which coming from postgres

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/e37a8068-189f-465d-b1ca-943b1505fc16)
is their a way to grab actual error detail message rather other thing ?

**Comment by xalteropsx** [comment]
thanks alot @YAGregor

**Comment by YAGregor** [comment]
> i saw the transaction doc that it rollback automatic but how do we catch the expection to make the logs
> 
> no idea about where that session came from are u mean session = transaction

are you using fastapi-sqlalchemy? I don't know much about this library, but in general you need to commit transaction(or session) by your self, like
```python
@router.get()
def view(db = Depends(db)):
    try:
        db.add(...)
        ...
        db.commit()
    except Exception as e:
        ...
    finally:
        ...
```
or write your own context manager, there are some quite free choice.

**Comment by xalteropsx** [comment]
> > i saw the transaction doc that it rollback automatic but how do we catch the expection to make the logs
> > no idea about where that session came from are u mean session = transaction
> 
> are you using fastapi-sqlalchemy? I don't know much about this library, but in general you need to commit transaction(or session) by your self, like
> 
> ```python
> @router.get()
> def view(db = Depends(db)):
>     try:
>         db.add(...)
>         ...
>         db.commit()
>     except Exception as e:
>         ...
>     finally:
>         ...
> ```
> 
> or write your own context manager, there are some quite free choice.

   ```py

 _obj = None
    async with in_transaction() as session:
        try:
            _obj = await _mod.create(**_request)
            session.commit()
            session.refresh(_obj)
        except IntegrityError as e:
            session.rollback()
            print(e)
    return _obj
```

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/054a7cb3-5067-4205-a64a-a2812307f7c8)

it work great now >.<

**Comment by YAGregor** [comment]
> > > i saw the transaction doc that it rollback automatic but how do we catch the expection to make the logs
> > > no idea about where that session came from are u mean session = transaction
> > 
> > 
> > are you using fastapi-sqlalchemy? I don't know much about this library, but in general you need to commit transaction(or session) by your self, like
> > ```
> > @router.get()
> > def view(db = Depends(db)):
> >     try:
> >         db.add(...)
> >         ...
> >         db.commit()
> >     except Exception as e:
> >         ...
> >     finally:
> >         ...
> > ```
> > 
> > 
> > or write your own context manager, there are some quite free choice.
> 
> ```python
> _obj = None
>  async with in_transaction() as session:
>      try:
>          _obj = await _mod.create(**_request)
>      except IntegrityError as e:
>          session.rollback()
>          print(e)
>  return _obj
> ```
> 
> thank u i notice why u did it as to provide me idea how it work awesome i just knew >.< do i need commit and refresh?

you need to commit in `try` block or exception may not raise, in most case you don't need to refresh model, the orm just keep track orm object and database.

**Comment by xalteropsx** [comment]
i think tortoise create automatically take care of commit  ?

**Comment by xalteropsx** [comment]
@YAGregor 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/a4976363-9c54-4cff-872d-30176164decf)

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/438b3877-ba52-40d5-9b40-cc4f79f85145)
but getting this warning

**Comment by YAGregor** [comment]
> i think tortoise create automatically take care of commit ? cause i can see everything working fine even exception raise

right, in tortoise there is not `session.refresh()` use `await model.refresh_from_db()`

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/8c97489c-1936-4425-89fa-0e44354d1578)
yah it work great now

**Comment by xalteropsx** [comment]
@YAGregor i facing the worse issue when i create and if it get fail it occupy that id even it fail to post but take those id like example

if i post 5 time fail 

id. increment next post  id.5     id.10   fail 10time   id.21

**Comment by xalteropsx** [comment]
@YAGregor  147.185.221.16:58651       try post   /tort/user 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/3cbf1fb2-d7a8-4a3f-a2bf-921c4475ef92)

**Comment by xalteropsx** [comment]
```py

@router.post("/users", response_model=User_PY)
async def create_user(user: UserIn_PY):
    try:
        user_obj = await Users.create(**user.model_dump(exclude_unset=True))
        return await User_PY.from_tortoise_orm(user_obj)
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"{e}")

```
