### ISSUE TITLE
Big bug on create || post  > id increment on fail post wasting unique id and spamming db

### ISSUE THREAD

**Issue by xalteropsx** [tortoise/tortoise-orm#1495]
![275183896-3cbf1fb2-d7a8-4a3f-a2bf-921c4475ef92](https://github.com/tortoise/tortoise-orm/assets/103671642/b51756b6-d52d-4f42-924c-d9ebe773fa65)

id keep keep increase even on fail post while this issue not occur on sqlalchmey

**Comment by YAGregor** [comment]
it's not bug, you may need learn more about database, mysql never promise auto increase field continuous, why sqlachemy is not the same? might because that sqlalchemy check data first and it didn't execute create sql statement..

**Comment by xalteropsx** [comment]
> it's not bug, you may need learn more about database, mysql never promise auto increase field continuous, why sqlachemy is not the same? might because that sqlalchemy check data first and it didn't execute create sql statement..

       _database.add(data)
        _database.flush()
i use sort of this technique to avoid waste of id incremental value

**Comment by xalteropsx** [comment]
> it's not bug, you may need learn more about database, mysql never promise auto increase field continuous, why sqlachemy is not the same? might because that sqlalchemy check data first and it didn't execute create sql statement..

is their anything alternative to flush ? in tortoise

**Comment by xalteropsx** [comment]
@YAGregor u need to check the flush method that is the key of not incrementing the id in sqlachemy  while here we have nothing about flush

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/dd73cac4-b59e-4614-a156-18f0cb71a583)
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/10da6edf-15f5-44cc-9bc7-816309a9e571)

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/cf26d7f0-51cb-42b2-bcc8-d86ac03f0194)
even ponyorm has flush ...

**Comment by xalteropsx** [comment]
@grigi why tortoise not has flush which is the most powerful method ? 

feature:
1.it avoid fail attempt id to not trigger incremental 
2.it allow to multi post table cause it get the id before post

**Comment by xalteropsx** [comment]
```py

@router.post("/module-group/", status_code=status.HTTP_201_CREATED)
def create_group(module: scmod, group: sc_mod1, database: Session = Depends(get_db)):
    if not any(module.dict().values()):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Module data is missing")

    if not any(group.dict().values()):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="register_config is missing")

    db_module = mod(**module.dict())
    database.add(db_module)
    database.flush()

    db_group = mod1(**group.dict(), module_id=db_module.id)
    database.add(db_group)

    database.commit()
    database.refresh(db_module)
    database.refresh(db_group)

    return {
        "module": db_module,
        "group": db_group,
    }

```

@long2ice 
plz consider adding `` flush`` method  it provide earlier the id as well  u can post multiple model at the same time

**Comment by YAGregor** [comment]
the `flush` is apart of sqlalchemy's ["unit of work"](https://www.sqlalchemy.org/features.html), tortoise orm would never has `flush`, cause tortoise, just like django, follow "active record pattern", it's very different from sqlalchemy (from idea level),
for your case, you just to need to avoid insert fail, or use another data source(like redis) to make autoincreasing sequence

**Comment by xalteropsx** [comment]
@YAGregor alot of orm used nowday flush i dont think it something very small

**Comment by xalteropsx** [comment]
nvm friend i left tortoise yestarday i saw rust orm which build for fastapi i love it it almost 12k star in 7month of its release

**Comment by YAGregor** [comment]
> nvm friend i left tortoise yestarday i saw rust orm which build for fastapi i love it almost 12k star in 7month of its release

what rust orm? I never heard

**Comment by xalteropsx** [comment]
@YAGregor  Edgedb

**Comment by xalteropsx** [comment]
> the `flush` is apart of sqlalchemy's ["unit of work"](https://www.sqlalchemy.org/features.html), tortoise orm would never has `flush`, cause tortoise, just like django, follow "active record pattern", it's very different from sqlalchemy (from idea level), for your case, you just to need to avoid insert fail, or use another data source(like redis) to make autoincreasing sequence

![image](https://github.com/tortoise/tortoise-orm/assets/103671642/e47c0f44-b9a2-490d-ba33-248faa1120d0)
between i not sure if u know flush do is something is outstanding 
i not sure why tortoise have no idea that why they ignore 
i agree it not needed in django case but for fastapi ,sanic and other frame it really necessary to have this important flush feature or just whole framework of orm consider for me junk
