### ISSUE TITLE
Support annotate F() expression cross model relation

### ISSUE THREAD

**Issue by YAGregor** [tortoise/tortoise-orm#1496]
**Is your feature request related to a problem? Please describe.**

to reproduce:
```
import asyncio

from tortoise import Model, fields, Tortoise
from tortoise.expressions import F


async def test():
    return ""


class A(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=255, default="name_of_a")


class B(Model):
    id = fields.IntField(pk=True)
    a = fields.ForeignKeyField("models.A")
    name = fields.CharField(max_length=255, default="name_of_b")


async def main():
    await Tortoise.init(db_url="sqlite://:memory:", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

    a = await A.create()
    b = await B.create(a=a)

    b2 = await B.annotate(a_name=F("a__name"), ya_b_name=F("name")).get(id=1)

    print(b2.a_name, b2.ya_b_name)  # in django orm we got b2.a_name == "name_of_a", but tortoise treat F(a__name") as string seems that F only works on fields in queryset's model its self

    await Tortoise.close_connections()


if __name__ == '__main__':
    asyncio.run(main())

```

**Describe the solution you'd like**

F() be able to reference fields of foreign key's model

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by YAGregor** [comment]
btw, I don't think F extend pypika's field is a good idea,I tried to implement this feature but seem its hard to extend feature.
Is your code struct imitate Django ORM? I suggest to organize query like tree, and "dump" the tree recursively just like [`peewee` ](https://github.com/coleifer/peewee/blob/01b2d94a4029858b9d2b1bee6fac40eed27ad9ad/peewee.py#L715)

**Comment by xalteropsx** [comment]
> btw, I don't think F extend pypika's field is a good idea,I tried to implement this feature but seem its hard to extend feature. Is your code struct imitate Django ORM? I suggest to organize query like tree, and "dump" the tree recursively just like [`peewee` ](https://github.com/coleifer/peewee/blob/01b2d94a4029858b9d2b1bee6fac40eed27ad9ad/peewee.py#L715)

```py

@router.post("/module-group/", status_code=status.HTTP_201_CREATED)
def create_group(module: scmod, group: sc_mod1, database: Session = Depends(get_db)):
    if not any(module.dict().values()):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Module data is missing")

    if not any(group.dict().values()):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="register_config is missing")

    db_module = mod(**module.dict())
    database.add(db_module)
    database.flush()

    db_group = mod1(**group.dict(), module_id=db_module.id)
    database.add(db_group)

    database.commit()
    database.refresh(db_module)
    database.refresh(db_group)

    return {
        "module": db_module,
        "group": db_group,
    }

```

@YAGregor  @long2ice   
plz consider adding flush method  it provide earlier the id as well

**Comment by fehimaltinisik** [comment]
Have you find a solution or an alternative approach to the problem?

I'm facing a similar issue. Trying to refer foreign key model's field. Following snippet didn't yield any result:

```python
class Stop(Model):
    stop_id = fields.IntField(pk=True)
    stop_code = fields.CharField(max_length=32)
    stop_name = fields.CharField(max_length=255)


class StopTime(Model):
    stop: fields.ForeignKeyRelation['Stop'] = fields.ForeignKeyField(
        model_name='models.Stop',
        related_name='stop_times',
        source_field='stop_id'
    )

record = await StopTime.select_related('stop').annotate(stop_name=F('stop__stop_name').first()
print(record.stop_name)
```

**Comment by YAGregor** [comment]
> Have you find a solution or an alternative approach to the problem?
> 
> I'm facing a similar issue. Trying to refer foreign key model's field. Following snippet didn't yield any result:
> 
> ```python
> class Stop(Model):
>     stop_id = fields.IntField(pk=True)
>     stop_code = fields.CharField(max_length=32)
>     stop_name = fields.CharField(max_length=255)
> 
> 
> class StopTime(Model):
>     stop: fields.ForeignKeyRelation['Stop'] = fields.ForeignKeyField(
>         model_name='models.Stop',
>         related_name='stop_times',
>         source_field='stop_id'
>     )
> 
> record = await StopTime.select_related('stop').annotate(stop_name=F('stop__stop_name').first()
> print(record.stop_name)
> ```

no, I think it's almost impossible, to implement this, its code need a big refactor

**Comment by windows8prew** [comment]
any solution yet?

**Comment by windows8prew** [comment]
I found a solution, it works, but it generates a large query

class City(Model):
    name = fields.CharField(max_length=255)

class Author(Model):
    first_name = fields.CharField(max_length=255)
    city = fields.ForeignKeyField('models.City')

class Book(Model):
    author = fields.ForeignKeyField('models.Author')

record = await Book.select_related('author', 'author__city').annotate(
    author_name=RawSQL('author.first_name'),
    city_name=RawSQL('author__city.name'),
).first()
print(record.author_name, record.city_name)

Translated with DeepL.com (free version)

**Comment by YAGregor** [comment]
> I found a solution, it works, but it generates a large query and dosent work with other annotations like Sum or Count because of GROUP BY
> 
> ```python
> class City(Model):
>     name = fields.CharField(max_length=255)
> 
> class Author(Model):
>     first_name = fields.CharField(max_length=255)
>     city = fields.ForeignKeyField('models.City')
> 
> class Book(Model):
>     author = fields.ForeignKeyField('models.Author')
> 
> record = await Book.select_related('author', 'author__city').annotate(
>     author_name=RawSQL('book__author.first_name'),
>     city_name=RawSQL('book__author__city.name'),
> ).first()
> print(record.author_name, record.city_name)
> ```

I know that, but in my view RawSQL is dirty so I try to avoid RawSQL

**Comment by windows8prew** [comment]
> I know that, but in my view RawSQL is dirty so I try to avoid RawSQL

I found other solution
```python
class City(Model):
    name = fields.CharField(max_length=255)

class Author(Model):
    first_name = fields.CharField(max_length=255)
    city = fields.ForeignKeyField('models.City')

class Book(Model):
    title = fields.CharField(max_length=255)
    author = fields.ForeignKeyField('models.Author')

record = await Book.first().values(
    'title',
    city_name='author__first_name',
    author_name='author__city__name',
)
print(record.title, record.author_name, record.city_name)
```
