### ISSUE TITLE
weird issue with await prefetching

### ISSUE THREAD

**Issue by xalteropsx** [tortoise/tortoise-orm#1509]
sorry for the tag little trouble on prefetch also look like dead community i cant get any idea what missing here 

@YAGregor

**Comment by xalteropsx** [comment]
how does the model relationship work ? if we wait and return it doesnt return relationship model rather pass an generator object

**Comment by xalteropsx** [comment]
```py

from tortoise.models import Model
from tortoise import fields, Tortoise, run_async
import asyncio


class Tournament(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()

    def __str__(self):
        return self.name


class Event(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
    tournament = fields.ForeignKeyField(
        "models.Tournament", related_name="events")
    participants = fields.ManyToManyField(
        "models.Team", related_name="events", through="event_team")

    def __str__(self):
        return self.name


class Team(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()

    def __str__(self):
        return self.name


async def init():
    await Tortoise.init(db_url="postgres://postgres:480@localhost:5432/mytest", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()


async def create_tournament(name):
    tournament = Tournament(name=name)
    await tournament.save()
    await Event.create(name="Without participants", tournament=tournament)
    event = await Event.create(name="Test", tournament=tournament)
    participants = []
    for i in range(2):
        team = await Team.create(name="Team {}".format(i + 1))
        participants.append(team)
    await event.participants.add(*participants)
    async for team in event.participants:
        pass
    for team in event.participants:
        pass

    selected_events = await Event.filter(participants=participants[0].id).prefetch_related("participants", "tournament")
    data = await Event.all().prefetch_related("participants")
    data2 = await Event.all()
    print(data[0].participants)

    print(data[0].participants)
    # await Tournament.filter(events__name__in=["Test", "Prod"]).order_by("-events__participants__name").distinct()


if __name__ == "__main__":
    run_async(init())
    asyncio.run(create_tournament("New Tournament"))

```

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/6051646b-bcd2-41d8-aaed-11c349258964)
we cannot do anything with these data unless we do await but the problem remain the same how do we return relationship using prefetching

**Comment by YAGregor** [comment]
I can explain, when u python execute `await Event.all()`, in the sql level, the database driver execute `select * from event`, and retrieve all events from database, but it did not retrieve any data from `tournament` table, 
For the python expression `event.tournament`, if you want to retrieve data form tournament, driver must execute `select * from tournament where id = ?`, but execute sql is a block IO operation, in python asyncio, you must add await in front of every IO operation.

if you dont want add await for each event object, try `await Event.all().select_releated('tournament').prefetch_related('...')`,
this generate sql `select * from event left join tournament ....`

**Comment by YAGregor** [comment]
BTW, I'd glad to help anyone who use tortoise, but I've decide to left tortoise, no offensive to tortoise, as you said the community is no longer active, and I read the source code of tortoise found that I dont like its desing

**Comment by xalteropsx** [comment]
same here but time was less i need to represent project singapore next month their is a event exhibition for startup company

thnx man u save my life really again :(  i cant thank u so much 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/59a0d9a3-b0b3-4eda-ba6d-feeaf686aabf)

but i didnt able to understand the logic of prefetch what it purpose 

@YAGregor

**Comment by xalteropsx** [comment]
i would be using edgedb but it need to spend alot of time cause the query goes in string type structure very hard for autocompletion like tabnine or copilot will see any changes  sufficient 1month is very less :( i almost need to catch it up as solo developer

**Comment by YAGregor** [comment]
`prefetch` is for making query faster, because every time python evaluate `await event.tournament`, the database driver communicate with database for one time (which cost a lot of time),
if u write 
```python
for event in events:  # assume there is ten events
    await event.tournament
```
then sql statements would execute, that is very slow,
instead of 
```
for event in events.select_related("tournament"):  # assume there is ten events
    await event.tournament
```
only one sql statement would be executed, that is `select * from event left join tournament ....`, it might be about ten more times faster that the version which didn't use prefetch/select_related.

**Comment by xalteropsx** [comment]
oh i see thnx i will read it little bit more and test it with large some of query with cprofile

**Comment by xalteropsx** [comment]
@YAGregor i try

**Comment by xalteropsx** [comment]
@YAGregor i want to return the object but it doenst return

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/09a7ecb8-a4af-4782-b6b5-8dfa8c77b431)
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/7eec180b-1511-4ea3-8138-31e01537e728)
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/9eea6af8-7916-4804-b193-b5a71bae8ce9)
@YAGregor

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/774613a1-9adc-414e-a673-bb20f2c27493)

**Comment by xalteropsx** [comment]
feel free to drop answer

**Comment by RicarTang** [comment]
> ![图像](https://user-images.githubusercontent.com/103671642/280437676-774613a1-9adc-414e-a673-bb20f2c27493.png)

You can use the "from_orm" method of the pydantic model object to serialize the pre-selected data, as long as you make sure that the pre-selected parameters of the model class are the same as the associated parameters of the model model
```
    query_list = (
        await TestSuite.all()
        .prefetch_related("testcase")
        .offset(limit * (page - 1))
        .limit(limit)
    )

    testsuites_list = [
        testsuite_schema.TestSuiteTo.from_orm(testsuite) for testsuite in query_list
    ]
```

**Comment by xalteropsx** [comment]
@RicarTang didnt work for 1 object  i am trying to avoid relooping

**Comment by xalteropsx** [comment]
@RicarTang 

```py

from tortoise import fields, models
from tortoise.contrib.pydantic import pydantic_model_creator
from tortoise import Tortoise, run_async
import asyncio
from typing import Optional, Any, List
from pydantic import BaseModel, ConfigDict
# from app import Book, Author

db = 'postgres://postgres:480@localhost:5432/mytest'

# copy this and create app.py to test aerich failiure 1- aerich init -t filename.TORTOISE_ORM  2- aerich init-db


class Author(models.Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=100)


class Book(models.Model):
    id = fields.IntField(pk=True)
    title = fields.CharField(max_length=200)
    author = fields.ForeignKeyField('models.Author', related_name='books')


# aerich v0.7.2 fail this is failing ortoise.exceptions.ConfigurationError: DB configuration not initialised. Make sure to call Tortoise.init with a valid configuration before attempting to create connections.
# aerich 0.7.1 fail no model with name relationship failing
TORTOISE_ORM = {
    "connections": {"default": db},
    "apps": {
        "contact": {
            "models": ["aerich.models", "app"],
            "default_connection": "default",
        },
    },
}


async def init():
    await Tortoise.init(db_url=db, modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

Author_PY = pydantic_model_creator(Author, name="Author")
Book_PY = pydantic_model_creator(Book, name="Book")


async def create_tournament(name):
    class SchemaMixin(BaseModel):
        code: int = 10000
        message: str = "success"
        data: Optional[Any]

    class ReadAuthorSchema(SchemaMixin):

        class AuthorEntity(Author_PY):
            model_config = ConfigDict(from_attributes=True)
            books: List[Book_PY] = []

        data: AuthorEntity

    author = Author(name=name)
    await author.save()
    for i in range(2):
        await Book.create(title=f"participants_{i}", author=author)

    authors = await Author.get(id=1).prefetch_related('books')

    store = dict(authors)
    print(store)  # problem with this it doesnt bring authors.book list

    data2 = {"data": store, "subdata": list(authors.books)}
    print(data2)

    print(ReadAuthorSchema(data=authors))


if __name__ == "__main__":
    run_async(init())
    asyncio.run(create_tournament("New Tournament"))



u can play around with this and show me how from_orm work on list and normal way plz guide me cause i not able to understand ur code `testsuite_schema.TestSuiteTo `

**Comment by xalteropsx** [comment]
```py
from tortoise import fields, models
from tortoise.contrib.pydantic import pydantic_model_creator
from tortoise import Tortoise, run_async
import asyncio
from typing import Optional, Any, List
from pydantic import BaseModel, ConfigDict
# from app import Book, Author

db = 'postgres://postgres:480@localhost:5432/mytest'

# copy this and create app.py to test aerich failiure 1- aerich init -t filename.TORTOISE_ORM  2- aerich init-db


class Author(models.Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=100)


class Book(models.Model):
    id = fields.IntField(pk=True)
    title = fields.CharField(max_length=200)
    author = fields.ForeignKeyField('models.Author', related_name='books')


# aerich v0.7.2 fail this is failing ortoise.exceptions.ConfigurationError: DB configuration not initialised. Make sure to call Tortoise.init with a valid configuration before attempting to create connections.
# aerich 0.7.1 fail no model with name relationship failing
TORTOISE_ORM = {
    "connections": {"default": db},
    "apps": {
        "contact": {
            "models": ["aerich.models", "app"],
            "default_connection": "default",
        },
    },
}


async def init():
    await Tortoise.init(db_url=db, modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

Author_PY = pydantic_model_creator(Author, name="Author")
Book_PY = pydantic_model_creator(Book, name="Book")


async def create_tournament(name):
    author = Author(name=name)
    await author.save()
    for i in range(2):
        await Book.create(title=f"participants_{i}", author=author)

    authors = await Author.get(id=1).prefetch_related('books')
    delta = Author_PY.from_orm(authors)
    print(delta)
    print('asda')
    store = dict(authors)
    print(store)

    data2 = {"data": store, "subdata": list(authors.books)}
    print(data2)


if __name__ == "__main__":
    run_async(init())
    asyncio.run(create_tournament("New Tournament"))

```
little playground show me

**Comment by xalteropsx** [comment]
@RicarTang  suppose u have the list scheme 

Event_List = pydantic_queryset_creator(Event) how would u do it ?   not pydantic_model_creator

testsuites_list = await Event_List.from_queryset(Event.all().prefetch_related("participants"))

**Comment by xalteropsx** [comment]
```py

class ReadQuestionSchema(SchemaMixin):
    class QuestionEntity(Event_List):
        model_config = ConfigDict(from_attributes=True)
        participants = List[Team]

    data: List[QuestionEntity]

    testsuites_list = await Event_List.from_queryset(Event.all().prefetch_related("participants"))
    testsuites_list = ReadQuestionSchema.QuestionEntity.from_orm(testsuites_list)
```

**Comment by xalteropsx** [comment]
alternatively i tried using this 

```py
class ReadQuestionSchema(SchemaMixin):

    class QuestionEntity(Event_R):
        model_config = ConfigDict(from_attributes=True)
        participants: List[Team_R] = []

    data: List[QuestionEntity]

    data = await Event.all().prefetch_related("participants")
    testsuites_list = ReadQuestionSchema.QuestionEntity.from_orm(data)

``` @YAGregor

**Comment by xalteropsx** [comment]
@YAGregor

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/8abb4916-f489-4924-a8b0-e69f8e7193b7)

**Comment by xalteropsx** [comment]
@YAGregor  @RicarTang 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/587273f6-d4ab-4bb5-8576-0a0c7186224d)

**Comment by xalteropsx** [comment]
nvm look like both same speed 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/d680f763-5600-4741-9002-fbcbefe0beb1)

**Comment by xalteropsx** [comment]
@YAGregor u have idea why this not work 

class Users(models.Model):
    id = fields.IntField(pk=True)
    username = fields.CharField(max_length=20, unique=True)
    name = fields.CharField(max_length=50, null=True)
    family_name = fields.CharField(max_length=50, null=True)
    category = fields.CharField(max_length=30, default="misc")
    password_hash = fields.CharField(max_length=128, null=True)
    created_at = fields.DatetimeField(null=True, auto_now_add=True)
    modified_at = fields.DatetimeField(null=True, auto_now=True)

    @property
    def created_time(self) -> str:
        created_at = getattr(self, "created_at")
        return created_at.strftime("%Y-%m-%d %H:%M:%S") if created_at else ""

    @property
    def updated_time(self) -> str:
        modified_at = getattr(self, "modified_at")
        print(modified_at)
        return modified_at.strftime("%Y-%m-%d %H:%M:%S") if modified_at else ""

**Comment by YAGregor** [comment]
> @YAGregor when i bulk post object i dont get id back why is that
> 
> ```python
> @router.post("/users")
> async def create_user(users: List[UserIn_PY]):
>     # try:
>     async with in_transaction():
> ```
> 
> ~ user_dicts = [dict(user) for user in users] user_obj = await Users.bulk_create([Users(**user) for user in user_dicts]) ~
> 
> ```python
>         user_obj = await Users.bulk_create([Users(**dict(user)) for user in users])
>         return user_obj
> ```
> 
> ![image](https://user-images.githubusercontent.com/103671642/281203602-fb960043-0c10-442c-af86-a39a2b1e1b6f.png)

U just can't get id back with bulk create, it's by desing

**Comment by xalteropsx** [comment]
@YAGregor  but i able to get the id in sqlalchmey  why it cannot ? it make it really difficult to make the array append if we update something on vue or react

**Comment by YAGregor** [comment]
U can't with sqlalchemy, too.except u create one by one, bulk create insert many lines in one sql statement, one sql statement returns one number, it can't get id back because the way it works

**Comment by xalteropsx** [comment]
> U can't with sqlalchemy, too.except u create one by one, bulk create insert many lines in one sql statement, one sql statement returns one number, it can't get id back because the way it works

bro u are wrong i can proof u  give me a little 1hr i do some breakfast

**Comment by xalteropsx** [comment]
hmm u look like right although their is little i know i try something like 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/6dd56a9b-a12c-4949-ac59-9962c654df36)

**Comment by xalteropsx** [comment]
@YAGregor 
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/2b751f62-3940-4618-b69d-b01d5158fd13)

**Comment by xalteropsx** [comment]
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/5c7e2a15-4483-486d-a5e4-9270fa5f98be)
 nvm u look right haha its same as add
