### ISSUE TITLE
You can add an analog of Django's Auto Field, because so far I don't see the possibility to make an IntField with the auto increment parameter

### ISSUE THREAD

**Issue by Foldren** [tortoise/tortoise-orm#1527]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by waketzheng** [comment]
`IntField(pk=True)` is auto increment, e.g. `Users` model in [fastapi example](https://tortoise.github.io/examples/fastapi.html#models-py)
