### ISSUE TITLE
Distinguish between attribute fields and relation fields

### ISSUE THREAD

**Issue by FirstKlaas** [tortoise/tortoise-orm#156]
**The Problem / Issue**
I want to auto generate rst documentation for the models. In documentation it makes sense to describe _plain_ attributes, like IntField or CharField in a different block then relation attributes. Programmatically I cannot distinguish these to types. Of course I could do something like: `isinstance(...)` an list all corresponding classes. But if tortoise will introduce a new field type, the code breaks.
 
**Describe the solution you'd like**
My idea would be to introduce two new classes `AttributeField` and `RelationField`. Both are a subclass of Field. And all the current fields will inherit either from `AttributeField` or from `RelationField`. So `class IntField(Model):` will become `class IntField(AttributeField):`.

The approach is pretty straight forward, does not change any semantics and should have no performance impact. 

**Describe alternatives you've considered**
An alternative could be a property.

**Comment by grigi** [comment]
I don't think there is a need to change the fields inheritance structure. We have ample metadata and any field will be mapped appropriately.
Also, there is no plans to add a new field type for relations that doesn't map cleanly to fk or m2m.
There is also no plans to change the _meta so it can be used for introspection. Hmm, it should actually be documented…

## Suggestion
In the model's `_meta` class you should have all the info you need?
e.g. `User._meta.fetch_fields` is all the fields that define relations.
Literally defined as `self.m2m_fields | self.backward_fk_fields | self.fk_fields` (it is a set)

Quick description of the _meta fields one can use for introspection: (all sets except `fields_map` which is a dict)
* `fields_map` → name:field dict of fields.
* `db_fields` → Columns on that model
* `fetch_fields` → Relations (could overlap with `db_fields`)
  * `fk_fields` → A fk column (will also occur in `db_fields`)
  * `backward_fk_fields` → A backwards fk relation (not in `db_fields`)
  * `m2m_fields` → a m2m field, either forward or backwards (not in `db_fields`)

Simply you could first take:
`db_fields - fetch_fields` → Non-relational
`fetch_fields` → Relational

We don't guarantee order, but on Py3.6+ you could use the order in `fields_map` to keep order as defined.

Also, the primary key is not always at the top of definition, you could force it to the top by using `pk_attr` which is a string containing the name of the primary key.

So, order of evaluation could be:
* PK: 
  `_meta.pk_attr`
* Other DB fields in order of definition: 
  `[(name, field) for name, field in _meta.fields_map if name != _meta.pk_attr and name in (_meta.db_fields - _meta.fetch_fields)]`
* Relational fields in order of creation: 
  `[(name, field) for name, field in _meta.fields_map if name in _meta.fetch_fields]`

(Although it would make sense to order by FK, then back-FB, and lastly M2M for reasons of consistency)

Would this work for you?

Also, I would be happy to include the code that generates the doc if you are happy to share, and have a function to generate static RST or as a Sphinx plugin. Then we also maintain it?

**Comment by grigi** [comment]
Would it benefit you if we have a `Tortoise.describe_models(<optional model>)` method?
Then we ensure that it has a consistent interface?

Then we could use it for building documentation and for building serialisation specs?

After looking at the code, it is more-or-less all It is more-or-less all that we need to also finish #39

**Comment by FirstKlaas** [comment]
Hi @grigi,
  thanks for your good answer. Yes, I could do, what you described in your first answer. But that would mean usind the private "_meta" field. I wont use any private fields in my code, because they are not part of the APIs contract. Otherwise they wouldn't be private. So I think your second approach will do the trick. Lucky me, I'm off for holiday the next two weeks. I will think about a sphinx contribution when I'm back.

Cheers

**Comment by grigi** [comment]
@FirstKlaas Could you look at the docstring here: https://github.com/tortoise/tortoise-orm/pull/170/files#diff-d4178e1b9fc39bf0424956e7e28d27d8R61-R113 and tell me if this will work for you?

**Comment by FirstKlaas** [comment]
@grigi: I will have a look at it upcoming weekend and give you some feedback.

**Comment by grigi** [comment]
@FirstKlaas I'm going to merge the work (as there is some important bugfixes included), but will mark the API as "Proposed". That should give us a few releases before it is pinned down formally.

**Comment by grigi** [comment]
@FirstKlaas You can look at the docs here: https://tortoise-orm.readthedocs.io/en/latest/setup.html#tortoise.Tortoise.describe_model
