### ISSUE TITLE
Docs request: if `pk` will be unique

### ISSUE THREAD

**Issue by jamesbraza** [tortoise/tortoise-orm#1562]
**Is your feature request related to a problem? Please describe.**

This model:

```python
from tortoise.models import Model

class Foo(Model):
    id = fields.CharField(max_length=32, pk=True)
```

And reading docs here: https://tortoise.github.io/models.html?h=primary+key#primary-keys

Don't indicate if `pk` will be unique or not.

**Describe the solution you'd like**

Can we document in the primary keys docs that `pk` means unique, or doesn't mean unique?

**Describe alternatives you've considered**

N/a

**Additional context**

None

**Comment by vlakius** [comment]
it's a primary key...they are [unique by design](https://en.wikipedia.org/wiki/Primary_key#:~:text=Informally%2C%20a%20primary%20key%20is,single%20attribute%3A%20a%20unique%20ID.)..
