### ISSUE TITLE
Updating config at runtime

### ISSUE THREAD

**Issue by intigratech** [tortoise/tortoise-orm#1563]
I have a use case where I need to be able to dynamically "install/uninstall" apps at runtime. I guess this would entail closing the connection and re-init with the new config. However, the issue with this approach is that this would cause connections to all databases to close? Is there a way to update the config/apps for just a particular connection without affecting other database connections?

**Comment by abondar** [comment]
No, there isn't way to do so, and I am not sure there should be

I'll close issue, but you can describe your usecase if you think that is something that could be used not only in extremely exotic cases

**Comment by intigratech** [comment]
No worries. Yes, I realize it's a bit of an exotic use case.
