### ISSUE TITLE
https://tortoise.github.io/0.19.1 gives 404

### ISSUE THREAD

**Issue by 1pav** [tortoise/tortoise-orm#1569]
**Describe the bug**
The documentation for 0.19.1 at https://tortoise.github.io/0.19.1/ returns 404.

**To Reproduce**
Go to https://tortoise.github.io/0.19.1/

**Expected behavior**
https://tortoise.github.io/0.19.1/ should load the documentation for 0.19.1.

**Additional context**
I couldn't file this issue to the more appropriate https://github.com/tortoise/tortoise.github.io because it doesn't accept issues.

**Comment by waketzheng** [comment]
@1pav You can view docs of 0.19.1 by this way:
```bash
git clone https://github.com/tortoise/tortoise-orm
cd tortoise-orm
which poetry || ((which pipx || (pip install --user pipx && export PATH=$HOME/.local/bin:$PATH)) && pipx install poetry)
poetry shell
git reset --hard 0.19.1
which apt && sudo apt install -y unixodbc unixodbc-dev # fix fatal error: sql.h: No such file or directory
make deps
cd docs
make html
open _build/html/index.html
```
<img width="719" alt="image" src="https://github.com/tortoise/tortoise-orm/assets/35413830/cb8e86c7-afa7-4afe-b515-a08e30c09054">

**Comment by abondar** [comment]
Yeah, linking for older versions was unfinished, for now I removed it and display only latest
