### ISSUE TITLE
I think the save method of the object adds an update_fields field to update some fields

### ISSUE THREAD

**Issue by csrftoken** [tortoise/tortoise-orm#157]
I think the save method of the object adds an update_fields field to update some fields.
Because I update the user table frequently when I log in WeChat, it might be better to update some fields
Do you think this idea?

**Comment by csrftoken** [comment]
Fetch I should write a manager to reduce the frequent update of a single record

**Comment by grigi** [comment]
This is performance related? e.g. you want to update a subset of fields in the DB?

**Comment by csrftoken** [comment]
Yes, I do. Updating one field is better than multiple fields, right?
For example：
```
instance.save(update_fields=("username"))  # good？
```

**Comment by grigi** [comment]
1) Does the current `instance.save()` do anything wrong (other than overhead on DB) ?
2) Could you please write an example of how you would use it, and what the caveats would be?

**Comment by grigi** [comment]
Actually, this isn't too much work to do, and your suggestion would not break anything.
I'd be happy to implement it.

**Comment by csrftoken** [comment]
There are no mistakes. I am familiar with django's orm, so I think django's orm design is really beautiful, and the framework is similar to django's orm, right.

**Comment by csrftoken** [comment]
For example：
```
from tortoise import Tortoise, run_async
from tortoise import models
from tortoise import fields


class Account(models.Model):
    id = fields.IntField(pk=True)
    username = fields.CharField(max_length=255)
    headimg = fields.CharField(max_length=128)
    gender = fields.BooleanField(default=True)

    def __str__(self):
        return self.username


async def init(generate=False):
    await Tortoise.init(
        db_url='sqlite://db.sqlite3',
        modules={'models': ['__main__']}
    )
    if generate:
        await generate_schemas()

    # Create user
    account = await Account.create(username="Tom", headimg="/static/xx.jpg", gender=True)

    # Update user
    account.username = "jerry"
    await account.save()


async def generate_schemas():
    await Tortoise.generate_schemas()


async def close_conns():
    await Tortoise.close_connections()

if __name__ == '__main__':
    run_async(init(generate=True))
```

*OUTPUT*

```
UPDATE "account" SET "username"='jerry',"headimg"='/static/xx.jpg',"gender"=1 WHERE "id"=1
```

Actually，I only update one field，but `get_sql` update all fields.
If a table has many fields but only one field is updated, wouldn't it be better to have 'update_fields' to control the updated fields.

Thanks.

**Comment by grigi** [comment]
Thank you for the complement :-)
Although I think that the performance will not be drastically different for smaller objects (e.g. under 4kb, due to how disk I/O happens) it will definitely provide a big boost for larger objects. :+1:

**Comment by csrftoken** [comment]
Hello, I would like to ask you a question about how this performance was tested?

**Comment by grigi** [comment]
I didn't. It was a guess based on my experience.

I **do** plan to extend the [Benchmarks](https://github.com/tortoise/orm-benchmarks):
* Add "update" (large query and do a .save() on each one)
* Add "update: partial" (this feature request)
* Rename the existing tests to actually be named what they test

Then extend with a large model, and relationship queries.

Originally the benchmarks was to find bottlenecks, and the current set of benchmarks have just about found all the bottlenecks for simple cases, now we need to dial up the complexity.
The issue is that for it to be sensible I need to do the same for all the other ORMs referenced.

And then explode it by testing MySQL & PostgreSQL as well.

IOW it is to be comprehensive.

**Comment by csrftoken** [comment]
Do you prefer database-related development？

I should learn from you.
Thanks.

**Comment by grigi** [comment]
Thank you
I definitely prefer data-first development. It may not actually involve databases.
Consider it experience . I know at least three people personally whom is a LOT better at SQL.

I just worked on "big data" 15 years ago, and there you quickly learn that doing less work doesn't mean better performance. Sometimes ensuring that updates line up with 4k boundaries (and doing the whole 4k, so never any partial writes) gave serious improvements. (On this system our disk cluster size was 4k)

Hence my guess that unless the table has many fields or references (e.g. BLOB/TEXT/JSON objects which are never stored in-line with the table) the speed up would be marginal.

**Comment by csrftoken** [comment]
I would probably prefer business development, I want to make some improvements in some areas.
Like in processing or SQL?
I've been programming in python for two years，Has been used at the framework level，but I think's it's the same idea.
From a framework perspective, I might find a lot of customization in them, but I probably won't reinforce it.

I want to get your suggest.
Thank you.

**Comment by grigi** [comment]
Do you want to take this offline? I feel this may not be the right forum for this conversation?
You can find me on gitter? Or would you prefer anything else?

**Comment by csrftoken** [comment]
ok.
