### ISSUE TITLE
model relationship bugged 

### ISSUE THREAD

**Issue by xalteropsx** [tortoise/tortoise-orm#1572]
data come in unknown format after sometime the relationship itself break

msgx: fields.ManyToManyRelation["Messagex"] = fields.ManyToManyField("tortmodels.Messagex", related_name="personxs", through="personx_messagex")

        data = await Personx.get(id=id).prefetch_related("msgx")
        async for dx in data.msgx:
              print(dx.id)
![image](https://github.com/tortoise/tortoise-orm/assets/103671642/c870b66a-f4a6-4c03-9a0d-fac3a0e962dc)

**Comment by YAGregor** [comment]
why don't u specialize the ordering? like
```python
 data = await Personx.get(id=id).prefetch_related(Prefetch("msgx", queryset=Msg.all().order_by("id")))
```

and why do you consider it as a bug of tortoise? have you executed the raw sql that tortiose generated, and checked the ordering that the database direct return?

ref: https://tortoise.github.io/query.html#complex-prefetch

**Comment by YAGregor** [comment]
>but isnt the data always come in an ascending manner ?

I think that it depends on which database you use.You may [set a default ordering of a model](https://tortoise.github.io/models.html#tortoise.models.Model.Meta.ordering), but what is the ordering if you don't change anything? At least it does not guarantee any ordering explicitly.

**Comment by abondar** [comment]
Return order is not guaranteed in most databases and it is out of scope of tortoise to tweak it
Please use `order_by` if you rely on ordering
