### ISSUE TITLE
why are there three files for one database?

### ISSUE THREAD

**Issue by MorTazaFarYabi** [tortoise/tortoise-orm#1573]
why does tortoise orm create 3 files for one sqlite database? (I could not find any explanations for it online)
I have a deployed project that uses tortoise orm and I need to remove a row from one of the tables manually. Seeing as there are three files the question is which file should I delete that row from?

**Comment by vlakius** [comment]
This how Asynchronous SQLite works -> [https://www.sqlite.org/asyncvfs.html](url)

TLDR: when you save some data it doesnt write it directly to the database. it write a sort of "log" file and the execute the data modification in a separate thread leaving the main thread free to receive other request
