### ISSUE TITLE
auto_now  not working

### ISSUE THREAD

**Issue by lichen404** [tortoise/tortoise-orm#1574]
**Describe the bug**
I use auto_now in my model,but when I  use update method ,its updated time doesn't  update

### update mtheod
![image](https://github.com/tortoise/tortoise-orm/assets/17066936/ff44eaaa-7685-4b96-a8a2-0affa33c6506)

### model
![image](https://github.com/tortoise/tortoise-orm/assets/17066936/626fffa5-7fda-4535-89ee-f5520aadbcf1)
![image](https://github.com/tortoise/tortoise-orm/assets/17066936/9d8439ae-3fba-4b69-a962-93058f78c27a)

**Expected behavior**
auto_now works when I update data

**Comment by daudln** [comment]
auto_now fields are not updated on calling .update() method.

auto_now fields are updated only if .save() method is called on model instance.

Be aware that update() does an update at the SQL level and, thus, does not call any save() methods on your models, nor does it emit the pre_save or post_save signals (which are a consequence of calling Model.save()

Based on your scenario, you need to get item, set attribute you want to update and save the instance

```py
@app.put("/movies/{pk}")
async def update_movie(pk: int, movie_in: MovieIn):
    movie = await Movie.filter(id=pk).first()
    if movie:
        # Your staffs
        await movie.save()
        return  # Your staffs
    return  # Your staffs
```

**Comment by waketzheng** [comment]
A few months ago, both auto_now and auto_now_add not work at my code. But after I change database from sqlite3 to MySQL, they work fine.
