### ISSUE TITLE
QuerySet is not working properly in a Jinja2 for loop

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#161]
Sorry if this is not the right place to ask, but there wasn't even a tortoise-orm tag on stackoverflow.

I can't figure out what's the right syntax to prefetch related data from relationships as I don't want the Jinja template to execute any databate queries

I'm doing the following (In Quart, which is like Flask but async)

```python
    @app.route("/projects")
    async def user_home():
        user = await User.get(email=session['email'])
        await user.fetch_related('roles')
    
        for role in user.roles:
            await role.fetch_related('project')

        print(user.roles[0].project.name) #Just a test, but this works here

        return await render_template("projects.html", user=user)
```

And in project.html :

```html
        {% for role in user.roles %}
        <tr>
            <td>{{role.project.name}}</td>
            <td>{{role.name}}</td>
        </tr>
        {% endfor %}
```

`role.project.name` is blank, but `role.name` is working fine.

And here are the models :

```python
    class User(Model):
        email = fields.CharField(255,unique=True)
        roles = fields.ManyToManyField('models.Role', related_name='users')
    
    class Role(Model, TimestampMixin):
        name = fields.CharField(100)
        project = fields.ForeignKeyField('models.Project', related_name='roles')
    
    
    class Project(Model, TimestampMixin):
        name = fields.CharField(100)
```

What am I missing here? I don't understand why it works on the route function but not on the Jinja template

**Comment by abondar** [comment]
Hi

Could you try fixing your example to be like this? 

```
    @app.route("/projects")
    async def user_home():
        user = await User.all().prefetch_related('roles__project').get()

        print(user.roles[0].project.name) #Just a test, but this works here

        return await render_template("projects.html", user=user)
```

That should at least speed up your code by quite a bit, and may be can fix your issue 😄 

If it won't work - I would recommend trying serialising model instances to dict before passing to template. There could be some incompatibilities between tortoise models and expected value for template context

**Comment by mojimi** [comment]
@abondar Hey thanks for the quick reply.

I tried the following but now I'm getting a different error before going to Jinja template `'ForeignKeyField' object has no attribute 'name'`

```python
    user = await User.get(email=session['email']).prefetch_related('roles__project').get()
    #await user.fetch_related('roles')
    #for role in user.roles:
    #    await role.fetch_related('project')
    print(user.roles[0].project.name)
```

**Comment by abondar** [comment]
`user = await User.get(email=session['email']).prefetch_related('roles__project').get()`
I believe there is typo, because you are calling `.get()` two times. First get should be replaced with `.filter()`. 

But error message looks confusing 🤔 
Please try fixing typo and say if it helped

**Comment by mojimi** [comment]
It really is weird.

I called get because it was on your code 😄 , to be honest I'm still learning how this works. But fixing the typo still gave the same error.

Let me try to give more info :

I want a specific user, all its roles and the project of each role.

The error is weird, sounds like it wasn't instantiated properly, maybe my creation code is wrong?

Here is how I create and assign a role/project to an user :

```python
class Project(Model, TimestampMixin):
    name = fields.CharField(100)

    @classmethod
    async def new(cls, template, name, user):
        #Creating the project
        project = cls()
        project.name = name
        await project.save()

        #Creating default admin role
        role = Role()
        role.name = 'Admin'
        role.project_id = project.id

        await role.save()
        await role.users.add(user)

        return project
```

**Comment by mojimi** [comment]
Even printing inside the jinja template works, I still haven't found a solution unfortunately.

I think it could be related to how the for loop in jinja is done

**Comment by abondar** [comment]
Did you try serialising model instances to dicts before passing them as context?
I think it should work fine, and using serialisation is quite good pattern in general, because it let's you separate data formatting from data storing

**Comment by mojimi** [comment]
> 
> 
> Did you try serialising model instances to dicts before passing them as context?
> I think it should work fine, and using serialisation is quite good pattern in general, because it let's you separate data formatting from data storing

Tortoise-orm models have a serialize method? I couldn't find anything about it in the docs

**Comment by abondar** [comment]
Sorry, may be I was misleading. I meant some thrid-party serialisers. 
I, personally, prefer to use https://github.com/marshmallow-code/marshmallow - it's very convenient in use and allows you to declare your desired formatting in code

**Comment by mojimi** [comment]
> 
> 
> Sorry, may be I was misleading. I meant some thrid-party serialisers.
> I, personally, prefer to use https://github.com/marshmallow-code/marshmallow - it's very convenient in use and allows you to declare your desired formatting in code

Never head of marshmallow before but it seems pretty easy to use.

I feel that it adds some redundant processing though, hopefully tortoise-orm can have its own serializer in the future

**Comment by abondar** [comment]
We have issue for that #13 , but I don't think that we will be able to attempt it in any near future, because there so much issues that we consider more important

**Comment by grigi** [comment]
We have a framework almost in place for clean schema extraction.

Then it should be easier to do so properly
