### ISSUE TITLE
Model.update_or_create should inherit the value of model

### ISSUE THREAD

**Issue by shaoerkuai** [tortoise/tortoise-orm#1668]
**Is your feature request related to a problem? Please describe.**

https://github.com/tortoise/tortoise-orm/issues/1364
https://github.com/tortoise/tortoise-orm/issues/885

**Describe the solution you'd like**
Currently I have a api endpoint which will update/insert a data to table.

I use this code to determine insert/update:

```python
user = SysUser.filter(username="...").first()
if user is None:
    # insert
else:
    # update..
```

Then I found `update_or_create`,but it will create a new object to table using `default` value in the field.

The only solution I've found is using `defaults=dict(key=value)` arg to save the data. It's strange..

**Describe alternatives you've considered**

Using `SysUser(age=16,role=1).update_or_create(username=username)` to update the `age` and `role` of the item.

**Additional context**

**Comment by Abeautifulsnow** [comment]
You can try: `SysUser.update_or_create(defaults=dict(age=16, age=1), username="...")` to do it.

```python
@classmethod
async def update_or_create(
    cls: Type[MODEL],
    defaults: Optional[dict] = None,
    using_db: Optional[BaseDBAsyncClient] = None,
    **kwargs: Any,
) -> Tuple[MODEL, bool]:
    """
    A convenience method for updating an object with the given kwargs, creating a new one if necessary.

    :param defaults: Default values used to update the object.
    :param using_db: Specific DB connection to use instead of default bound
    :param kwargs: Query parameters.
    """
    if not defaults:
        defaults = {}
    db = using_db or cls._choose_db(True)
    async with in_transaction(connection_name=db.connection_name) as connection:
        instance = await cls.select_for_update().using_db(connection).get_or_none(**kwargs)
        if instance:
            await instance.update_from_dict(defaults).save(using_db=connection)
            return instance, False
    return await cls.get_or_create(defaults, db, **kwargs)
```

**Comment by Abeautifulsnow** [comment]
> This is where I get confused because I wasthought defaults and Model's default field were the same thing,well...

Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper) inspired by `Django`.

Tortoise ORM was build with relations in mind and admiration for the excellent and popular `Django ORM`. It’s engraved in it’s design that you are working not with just tables, you work with relational data.

... So its behavior is similar to django's [update_or_create](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#update-or-create) 😅.

> Is there a solution for this scenario? For example, constrain a list of updatable fields in update_create, like [update_fields](https://tortoise.github.io/setup.html?h=save#tortoise.Model.save.update_fields) ?

I'm not sure if there's a elegant approach to do that, you might need to do some research or wait for someone else or @ the primary maintainer to answer. Sorry about that.

**Comment by abondar** [comment]
@shaoerkuai I am not sure I fully understood your problem, but if you need some different behaviour in case of update or create - than you should just use explicit `get`, check if object exists, update it with required field, or `create` another object if it doesn't exist/fulfil your requirements. 

It also shouldn't be much slower that calling `update_or_create`, as it is basically what that function does under the hood
