### ISSUE TITLE
Missing type tags when using async for ... in ... in PyCharm

### ISSUE THREAD

**Issue by panla** [tortoise/tortoise-orm#1681]
**Describe the bug**

when use async for instance in Model.filter(), there no type info.

```python
async for team in event.participants:
    print(team.id)
```

The team.id in this code does not prompt for the id attribute,

```text
Unresolved attribute reference 'id' for class 'QuerySet' 
```

in version 0.19.3

```python
def filter(cls: Type[MODEL], *args: Q, **kwargs: Any) -> QuerySet[MODEL]:
```

in version 0.21.5

```python
def filter(cls, *args: Q, **kwargs: Any) -> QuerySet[Self]:
```

**To Reproduce**
Steps to reproduce the behavior, preferably a small code snippet.

**Expected behavior**

**Additional context**

version: 0.21.5

**close**

if is is not  a bug, please close it

**Comment by waketzheng** [comment]
Failed to reproduce in PyCharm 2023.1.3 (Community Edition) with tortoise-orm==0.21.5
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/6ec980a7-76b9-4660-8560-7434011bf5ba">

**Comment by panla** [comment]
@waketzheng 
![20240816111659](https://github.com/user-attachments/assets/c65f879d-3256-47d0-b47a-bfb7f0f95efd)

**Comment by waketzheng** [comment]
@panla I believe that is a BUG of PyCharm!

Currently, you have two ways to improve prompt:
1. Use `for (await queryset)` instead of `async for`
```py
for instance in (await User.filter()):
    print(instance.id)
``` 
2. Add overload to source code of tortoise/queryset.py
```py

    @overload
    def __getitem__(self, key: int) -> "MODEL": ...
```
<img width="609" alt="image" src="https://github.com/user-attachments/assets/abd2b4b8-0796-4b93-bf97-717611b66738">
