### ISSUE TITLE
Provide count() in Model

### ISSUE THREAD

**Issue by lnxsr** [tortoise/tortoise-orm#1721]
**Is your feature request related to a problem? Please describe.**
It took me quite some time as newbie to figure out how to get the count of all rows in a table.

**Describe the solution you'd like**
An easy way to get the count of rows of a table.

Provide count() in Model similar like this
```python
@classmethod
async def count(cls):
    return (await cls.first().annotate(count=Count(<some column>)).count
```

**Describe alternatives you've considered**
The current workaround I ended up with is

```python
class Counter:
    @classmethod
    async def count(cls):
        return (await cls.first().annotate(count=Count(next(iter(cls._meta.db_fields))))).count

class Tournament(Counter, Model):
    pass
```

**Additional context**
Maybe PK should be preferred if existing, with a fallback.

**Comment by henadzit** [comment]
@lnxsr there's `count` method on `QuerySet`, see https://tortoise.github.io/query.html?h=count#tortoise.queryset.QuerySet.count

`print(await Tournament.all().count())`
