### ISSUE TITLE
"cannot start a transaction within a transaction" in bulk_create on sqlite3

### ISSUE THREAD

**Issue by mooskagh** [tortoise/tortoise-orm#1757]
Sorry for not giving clear steps to reproduce, maybe someone could guess what's going on just by looking at the code.

Once per day or so, my server (with sqlite3 backend) crashes with the following stack trace:

```
        | Traceback (most recent call last):
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 44, in translate_exceptions_
        |     return await func(self, query, *args)
        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 134, in execute_many
        |     await connection.execute("BEGIN")
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/aiosqlite/core.py", line 184, in execute
        |     cursor = await self._execute(self._conn.execute, sql, parameters)
        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/aiosqlite/core.py", line 129, in _execute
        |     return await future
        |            ^^^^^^^^^^^^
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/aiosqlite/core.py", line 102, in run
        |     result = function()
        |              ^^^^^^^^^^
        | sqlite3.OperationalError: cannot start a transaction within a transaction
        |
        | During handling of the above exception, another exception occurred:
        |
        | Traceback (most recent call last):
        |   File "/home/lc0/dev/lczero-live/backend/analyzer.py", line 246, in _uci_worker_think
        |     await self._process_info_bundle(
        |   File "/home/lc0/dev/lczero-live/backend/analyzer.py", line 306, in _process_info_bundle
        |     await db.GamePositionEvaluationMove.bulk_create(moves)
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tortoise/queryset.py", line 1929, in _execute
        |     await self._db.execute_many(str(self.insert_query), values_lists)
        |   File "/home/lc0/.pyenv/versions/3.12.3/lib/python3.12/site-packages/tortoise/backends/sqlite/client.py", line 46, in translate_exceptions_
        |     raise OperationalError(exc)
        | tortoise.exceptions.OperationalError: cannot start a transaction within a transaction
        +------------------------------------
```

**UPD** Without explicit `async with in_transaction()`, it sill fails similarly.

~~What I believe happens is in one task I have bulk_create() within a transaction (by reading the code I know it doesn't make sense to do that, but still that's what I have):~~
```
async with in_transaction():
    game = await Game.create(...)
    await GameFilter.bulk_create([...])
```

and another task at the same time runs another `bulk_create` (not within a transaction)
```
await db.GamePositionEvaluationMove.bulk_create(moves)
```

Those tasks run fine periodically a few times per day (the first one), or every second (the second one), but I suspect that when they happen to run at the same time, the crash happens.

I don't use any connection pool explicitly (I suspect sqlite3 just uses a single connection with a lock by default, and I'm fine with that).

**Comment by mooskagh** [comment]
I attempted to remove `async with in_transaction()`, it still crashed.

**Comment by mooskagh** [comment]
Thanks for paying attention to this bug report!

By tasks, I mean `asyncio` tasks (or rather `anyio` with `asyncio` underneath).

It's a single worker Sanic webapp, the code is located here https://github.com/mooskagh/lczero-live/tree/a0407c36733dfa042a0e956d478b8319eaf74214. For the upcoming World Chess Championship that starts on November 23, it's going to run live annotation of games with the Lc0 engine, at https://live.lczero.org.

So, the web server starts a few `asyncio` background tasks (I know for doing it "properly", I'd need external message broker, but I just need something quick and hacky).
- One tasks communicates with a chess engine, which sends the updates of current state of the thinking process.  The task then calls [bulk_create()](https://github.com/mooskagh/lczero-live/blob/a0407c36733dfa042a0e956d478b8319eaf74214/backend/analyzer.py#L313) to store that annotation (one row per candidate move, up to 20 rows total). This happens ≈once per second.
- Another task watches for the external feed to get chess moves. When a game finishes, it picks a new game to follow and runs (among other things) [bulk_create()](https://github.com/mooskagh/lczero-live/blob/a0407c36733dfa042a0e956d478b8319eaf74214/backend/game_selector.py#L115) to write game properties to the DB. Also it cancels the "chess engine" task and starts a new one afterwards. This happens roughly once per hour.


In the stacktrace, I see the "thinking" `bulk_create()`, i.e. the one that runs once per second. However, this failure only happens during the game change, i.e. during the event that runs once per hour (which has another `bulk_create()` call, but also a few other calls).

---

I've just put an `anyio.Lock` lock aroung both of bulk_create()s, to prevent them from running at the same time, let's see whether that helps.

...and now as I've typed it, I have another hypothesis of what's happening...  
Maybe the "thinking" task is being cancelled while doing `bulk_create()`, and the transaction is not properly rolled back -- so that when a next transaction starts, it appears nested.

**Comment by mooskagh** [comment]
Sorry for misleading you again, but I just re-read the logs, and I was wrong that it happens during the "new game" `bulk_create()`, it actually happens during the game.

I'll post more details tomorrow.

**Comment by henadzit** [comment]
hey @mooskagh, were you able to collect more information about the issue?

**Comment by mooskagh** [comment]
I switched to Postgres for now, and the problem stopped reproducing after that.

Before that, I tried to "fix" it by puting a`anyio.Lock`s here and there and it didn't help, so I'm failrly certain it's because of a cancellation and not because of simultaneous requests from different tasks.

Sorry for not providing a clear reproducer, hopefully I'll have a time for it in a few weeks. But here's what the server does (minified to db interactions):

```python
async def _uci_worker(
    self,
):
    pgn: Optional[chess.pgn.Game] = None
    while True:
        async with anyio.create_task_group() as tg:
            if pgn:
                # Start "thinking" of the move.
                tg.start_soon(
                    self._uci_worker_think,
                    get_leaf_board(pgn),
                )
            while True:
                # Get next move from (external) feed.
                pgn = await pgn_recv_stream.receive()
                # Runs a few get_or_create() in a loop, see below.
                last_pos: db.GamePosition = await self._update_game_db(pgn, game)
            async with self._uci_cancelation_lock:
                # Cancel the previous _uci_worker_think
                # !!! THAT'S WHAT I BELIEVE CAUSES THE FAILING STATE !!!
                tg.cancel_scope.cancel()


# Started ≈once per minute, when new move is made. Old worker is cancelled.


async def _uci_worker_think(self, board: chess.Board):
    with await self._engine.analysis() as analysis:
        info_bundle: list[chess.engine.InfoDict] = []
        async for info in analysis:
            info_bundle.append(info)
            if bundle_is_complete:
                await self._process_info_bundle(
                    info_bundle=info_bundle,
                )
                info_bundle = []


# is called ≈once per second
async def _process_info_bundle(
    self,
    info_bundle: list[chess.engine.InfoDict],
):
    evaluation: db.GamePositionEvaluation = await db.GamePositionEvaluation.create(
        # ...
    )

    moves: List[db.GamePositionEvaluationMove] = [
        db.GamePositionEvaluationMove(...) for _ in info_bundle
    ]
    # ~30 rows in average.
    await db.GamePositionEvaluationMove.bulk_create(moves)
    self.pos.nodes = ...
    await self.pos.save()


async def _update_game_db(self, pgn: chess.pgn.Game, game: db.Game) -> db.GamePosition:
    async def create_pos(
        ply: int,
        move_uci: Optional[str],
        move_san: Optional[str],
    ) -> db.GamePosition:
        res, created = await db.GamePosition.get_or_create(
            game=game,
            ply_number=ply,
            defaults={
                "fen": board.fen(),
                "move_uci": move_uci,
                "move_san": move_san,
                "white_clock": white_clock,
                "black_clock": black_clock,
                "nodes": 0,
                "q_score": 0,
                "white_score": 0,
                "draw_score": 0,
                "black_score": 0,
            },
        )

    for ply, node in enumerate(pgn.mainline(), start=1):
        await create_pos(
            ply=ply,
            move_uci=node.move.uci(),
            move_san=san,
        )
```

**Comment by henadzit** [comment]
@mooskagh thank you for providing more information!

Frankly postgres is a better choice for async. Tortoise uses aiosqlite for sqlite and aiosqlite is just a wrapper around sqlite3 that uses a single thread and a queue of operations, so there is no real parallelism.
