### ISSUE TITLE
AttributeError in Aerich migrations for M2M fields

### ISSUE THREAD

**Issue by gLiNtAlpHa** [tortoise/tortoise-orm#1787]
When running Aerich migrations with many-to-many fields, an AttributeError occurs if the M2M field is defined in a certain way. The error prevents migrations from completing successfully.

Traceback (most recent call last):
  File "C:\Users\AppData\Local\pypoetry\Cache\virtualenvs\src-AvnCrrma-py3.11\Lib\site-packages\aerich\migrate.py", line 244, in diff_models
    table = change[0][1].get("through")
            ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

```py
from tortoise import fields, Model

class Course(Model):
    name = fields.CharField(max_length=100)

class Student(Model):
    name = fields.CharField(max_length=100)
    course= fields.ManyToManyField('RelatedModel')
```
Aerich should successfully create the migration file, handling both dictionary-based and string-based M2M field definitions. The migration process fails with an AttributeError when trying to access the "through" attribute on a string object. While debuging I found out that the error occurs because the migration system assumes M2M field definitions are always in dictionary form with a "through" key, but they can also be simple strings. This needs to be handled also to support both forms of M2M field definitions. 

### Labels
- bug
- migrations
- aerich
- many-to-many

**Comment by waketzheng** [comment]
https://tortoise.github.io/fields.html?h=source_field#tortoise.fields.relational.ManyToManyField

<img width="475" alt="image" src="https://github.com/user-attachments/assets/53666fcc-b715-4974-8318-24ec5e275667">

It seems that you miss the app label: change `ManyToManyField('RelatedModel')` to `ManyToManyField('models.RelatedModel')` may fix it
