### ISSUE TITLE
A UnicodeDecodeError happened when install tortoise-orm in non-utf8 environment

### ISSUE THREAD

**Issue by zkonge** [tortoise/tortoise-orm#180]
**Describe the bug**
```python
>>> verstrline = open("tortoise/__init__.py", "rt").read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 9131: illegal multibyte sequence
```

**To Reproduce**
In `tortoise/__init__.py` line 225
```
...
 and the same output as ``describe_model(…)`` as value:
...
```
Replace "…" with three dots "..." which are ASCII characters.

**Expected behavior**
Install successfully

**Additional context**
None

**Comment by grigi** [comment]
Is this a non-unicode environment? (as in ASCII or Latin-x)

**Comment by zkonge** [comment]
I use it in powershell and my Windows system language is Chinese.

**Comment by grigi** [comment]
I really thought that Windows handles Chinese in unicode... Well, now I have learnt it does not.
Could you please see if any OTHER characters are causing problems for you? I only found the one you referenced when I looked just now.

**Comment by grigi** [comment]
Please test if `pip install https://github.com/tortoise/tortoise-orm/archive/update_queryset.zip` fixes it for you?

**Comment by zkonge** [comment]
It works.
