### ISSUE TITLE
`select_related` and `prefetch_related` are raising an error

### ISSUE THREAD

**Issue by Abdeldjalil-H** [tortoise/tortoise-orm#1803]
**Describe the bug**
When using `select_related` or `prefetch_related` on a model with a ForeignKey relationship, the code raises a TypeError: 'Field' object is not callable.

**To Reproduce**
```python
from tortoise import Tortoise, fields, run_async
from tortoise.models import Model


class Parent(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=50)


class Child(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=50)
    parent = fields.ForeignKeyField("models.Parent", related_name="children")


async def run():
    await Tortoise.init(db_url="sqlite://memory", modules={"models": ["__main__"]})
    await Tortoise.generate_schemas()

    # Create sample data
    parent = await Parent.create(name="Parent 1")
    child = await Child.create(name="Child 1", parent=parent)

    # This line triggers the error
    result = await Child.get(id=child.id).select_related("parent")

    await Tortoise.close_connections()


if __name__ == "__main__":
    run_async(run())
```
<details><summary>Error traceback</summary>

```
Traceback (most recent call last):
  File "example.py", line 31, in <module>
    run_async(run())
  File "tortoise/__init__.py", line 632, in run_async
    loop.run_until_complete(coro)
  File "asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "example.py", line 25, in run
    result = await Child.get(id=child.id).select_related("parent")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tortoise/queryset.py", line 1148, in _execute
    *self.query.get_parameterized_sql(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Field' object is not callable
```
</details>

**Expected behavior**
The query should successfully fetch the Child model instance along with its related Parent data as it was before. I think the issue happened after merging #1797 

**Additional context**
The above code fails on the `develop` branch, but it was working on `0.22.1` (I didn't test all commits after).

**Comment by henadzit** [comment]
Hey @Abdeldjalil-H, thank you for the detailed bug report! I couldn't reproduce the issue on the `develop`. There are tests for [select_related](https://github.com/tortoise/tortoise-orm/blob/ec4e1a15e844d8ad0d79c47ff0338847486fd124/tests/test_queryset.py#L734), they should have failed if it wasn't working. Can you please double check that you're testing against `develop`?

**Comment by Abdeldjalil-H** [comment]
Hi @henadzit.
Now I am not able to reproduce myself too. Maybe I was using the wrong env. So I am closing this. Thank you for your time.
