### ISSUE TITLE
backward_relations in PydanticMeta is not respected

### ISSUE THREAD

**Issue by PushUpek** [tortoise/tortoise-orm#1806]
I think that here is a bug:

https://github.com/tortoise/tortoise-orm/blob/e5cadb5fa687631935c4cd3d2447964a13ba1b7d/tortoise/contrib/pydantic/descriptions.py#L116

it should be `backward_relations`

**Comment by zhuying412** [comment]
I hava the sample problem.
you need change `backward_relations = True` to `backward_relations_raw=True` for this bug.

**Comment by markus-96** [comment]
my fault, I am sorry for the inconvenience.

**Comment by henadzit** [comment]
Fixed in 0.23.0
