### ISSUE TITLE
Char fields cannot be primary key

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#195]
**Describe the bug**
According to the documentation (https://tortoise-orm.readthedocs.io/en/latest/models.html#primary-keys) you can make CharField to a primary key field, but it is not working.
~~I checked in the source and it is just not implemented in _get_primary_key_create_string function. At least not in the MySQL schema generator.~~

**To Reproduce**
Tried with the following code:
```python
class Metadata(models.Model):
    key = fields.CharField(pk=True, max_length=64)
    value = fields.TextField()
```
After creating the schema, in the database no primary key is created for the field 'key'.

**Expected behavior**
The field 'key' should be a primary key.

**Additional context**
~~I checked the source of MySQL and Postgres schema generator and both of them have no generator for char fields.~~
Ok, the problem is only in MySQL generator. I don't no why, the FIELD_TEMPLATE is overriden, and doesn't contain {primary} variable. I tested with the original in the BaseSchemaGenerator and works well.

**Comment by grigi** [comment]
Ah…
Thank you for investigating this. I'll ensure that we add this case as a test case and test it.

**Comment by grigi** [comment]
:man_facepalming: My test was wrong. Fixing now.

**Comment by grigi** [comment]
Hi @wallneradam I release 0.13.8 with a fix. Please confirm that this solves the issue for you?

**Comment by wallneradam** [comment]
Yes it solves it, thanks.
