### ISSUE TITLE
Field operator support

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#196]
**Is your feature request related to a problem? Please describe.**
Take the following example:
```python
class Users(BaseModel):
    id = BigIntField(pk=True)

    firstname = CharField(max_length=128)
    lastname = CharField(max_length=128)

    @property
    def full_name(self):
        return self.firstname + " " + self.lastname
```

The IDE shows an error, that CharField does not define `__add__` method.

**Describe the solution you'd like**
It would be good to make fields implement basic, possible operators.

**Describe alternatives you've considered**

It may be a solution to make basic fields also inherit from base Python types, e.g. CharField inherit not just Field, but str.

Of course I can workaround the above issue:
```python
return str(self.firstname) + " " + str(self.lastname)
```

**Comment by grigi** [comment]
This is more of a metaprogramming issue.

What happens is that the type system sees the field as a class variable, and assumes that is what is running when you use the model.

What actually happens is that the fields as class variables are removed, and the constructor will instead populate an instance variable of the Python type. Which for CharField is str.

So at runtime you work with a plain Python string, as one would expect.

But the IDE type system doesn't know it.

I built a pylint plugin to help with this, but thesedays ides may need their own plugin. I know mypy plugins is now a thing, but unsure if it will help at all.

1. It works as you expect
2. IDEs need help with metaprogramming

**Comment by wallneradam** [comment]
Thanks, now I understand how it works.
Hello, I have an idea to make IDEs know the Python class of fields without plugins:

```python
class FieldMeta(type):
    def __new__(cls, name, bases, attrs):
        # Remove fake base classes
        if len(bases) > 1:
            bases = (bases[0],)
        return type.__new__(cls, name, bases, attrs)
        

class Field(metaclass=FieldMeta):  # Use metaclass to modify subclasses before creation
    __slots__ = ('p1', 'p2')
    def __init__(self, p1=None, p2=None):
        self.p1 = p1
        self.p2 = p2


class IntField(Field, int):  # Acts like an int object for IDEs
    def __init__(self, p1=None, *args, **kwargs):
        super().__init__(p1, *args, **kwargs)
        

class CharField(Field, str):  # Acts like an str object for IDEs
    __slots__ = ('p3')
    def __init__(self, p1=None, *args, **kwargs):
        super().__init__(p1, *args, **kwargs)
```

In brief:
- You add the type you want the class act as a 2nd base class. (you can add more classes)
- Create a FieldMeta class, which will be the metaclass for Field class.
- The metaclass will leave only Field as base class, so in runtime no errors or any consequences will occur.

It could be done other ways but that will break __slots__ possibilities, which I think makes Tortoise faster.

I tried it and works like a charm in PyCharm. If you like the idea, I can create a pull request.

**Comment by wallneradam** [comment]
It can also be used to make Field class to know the type instead of passing it as a parameter. I think it would be intuitive. And then it would not just a syntactic sugar for IDEs, but it could have a real use.

**Comment by grigi** [comment]
It is an interesting idea, and might just work :-)

**Comment by grigi** [comment]
Closing this as it is in current release. Thanks for your idea @wallneradam ! It works great!
