### ISSUE TITLE
Foregin keys on MySQL

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#197]
**Describe the bug**
Foreign key constraints are not working on MySQL/MariaDB

**To Reproduce**

models/countries.py:
```python
class Countries(Model):
    id = IntField(pk=True)
    code = CharField(max_length=2, unique=True, description="ISO 3166-1")
    name = CharField(max_length=50, index=True)
```

models/users.py:
```python
class Users(Model):
    id = BigIntField(pk=True)
    firstname = CharField(max_length=128)
    lastname = CharField(max_length=128)

    country = ForeignKeyField(model_name="models.Countries")
```

**Expected behavior**
Foreign keys should be created.

**Additional context**

The created SQL is like this:
```sql
CREATE TABLE `countries` (
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `code` VARCHAR(2) NOT NULL UNIQUE COMMENT 'ISO 3166-1',
    `name` VARCHAR(50) NOT NULL,
    KEY `countries_name_991101_idx` (`name`)
) CHARACTER SET utf8mb4;

CREATE TABLE `users` (
    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `firstname` VARCHAR(128) NOT NULL,
    `lastname` VARCHAR(128) NOT NULL,
    `country_id` INT NOT NULL REFERENCES `countries` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
```
1st problem is that pk fields are unsigned, but ForeignKeyFields are not. When I tried to add a foreign key by SQL from a mysql gui, I got the following error: "Foreign key constraint is incorrectly formed"
More info: https://stackoverflow.com/questions/8434518/mysql-foreign-key-constraint-is-incorrectly-formed-error

The 2nd is it seems MySQL can't handle the REFERENCES in the same row as the field (it just ignores it), but it needs a separate FOREIGN KEY row inside CREATE TABLE.

**Comment by grigi** [comment]
I learn things every day.
Will look at fixing it tonight or the weekend.

**Comment by grigi** [comment]
Ok, Interesting that I couldn't replicate the issue until I changed the DB type to `MyISAM`. The tests was running with `InnoDB`.
Second is that Integer fields are signed in Tortoise ORM, and ONLY integer PK's were unsigned in MySQL (which is weird, I wonder if this is a bug that started with the original MySQL implementation?)(I just checked: Yes)

Using `InnoDB` tests fail all over the place, so we should probably add it to the CI.

**Comment by wallneradam** [comment]
My DB type is InnoDB. I tested it on MySQL5.7.27, and MariaDB 10.4.8 (both with docker image).

I can print the SQL Tortoise generates (with tortoise.utils.get_schema_sql). And after I print the generated schema with SHOW CREATE TABLE. It shows that the table is InnoDB and has no foreign keys. When I tried to create a foreign key by hand, it was not possible because the difference between the field type and the foreign key type.

If you are interested I can somehow share my test project with you. It is easily reproducible. But really I just used the 2 above models and used generate_schemas method.

Also I created a workaround in my own SchemaGenerator class. Just had to add UNSIGNED before reference strings, then split references into CONSTRAINT ... FOREIGN KEY ... query and it worked well.

**Comment by grigi** [comment]
Right, it is because `MyISAM` doesn't support transaction rollback, which the tests depend on. 

@wallneradam Could you please have a look at #200 and see if it resolves your issues?

I didn't do the refactor to move REFERENCES and PRIMARY/FOREIGN KEY to its own line yet, It could be a MySQL/MariaDB difference, as when I looked at what the DB table structure looked like, it had all the references already?

**Comment by grigi** [comment]
I dropped `UNSIGNED` as we don't actually support unsigned ints at this stage.

Also, strange that MySQL Workbench sees the foreign keys, but when I do a SHOW CREATE TABLE it doesn't? But now I see a difference between the different syntaxes.

And this should also fix the "safe creation" of indexes for MySQL.

**Comment by grigi** [comment]
@wallneradam Please test if v0.13.9 resolves this issue?

**Comment by wallneradam** [comment]
@grigi Well, both yes and no. 

It creates the foreign keys now. But the SQL is not the same format as SHOW CREATE TABLE provides. The name of the foreign key is missing:
```sql
FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON DELETE CASCADE
```
But it should look like this:
```
CONSTRAINT `fk_country_id` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON DELETE CASCADE
```

Without this it creates a foreign key and gives a name like `users_ibfk_1`. The problem is, I can't know which name will it have, it may depends of the version, the order of creation...

**Comment by grigi** [comment]
Hmm, OK. We should fix that.
Is the constraint name scoped to the table? If so we could literally do `fk_{field}`, and that would be easy to do.

**Comment by grigi** [comment]
From the docs:
> If the CONSTRAINT **symbol** clause is given, the symbol value, if used, must be unique in the database. A duplicate symbol will result in an error similar to: `ERROR 1022 (2300): Can't write; duplicate key in table '#sql- 464_1'`.

So DB scoped. We need to generate unique names for it.
A suggestion is `fk_{from_table}_{from_field}_{to_table}_{to_field}` but that can easily get too long, So will have to use a deterministic hash like we use for indexes.

**Comment by wallneradam** [comment]
I just started to write the same. Yes it is DB scoped: https://stackoverflow.com/questions/1397671/can-there-be-constraints-with-the-same-name-in-a-db

But if you later want to create more sophisticated foreing key support, it is the same in Postgres, and I think in SQLite as well. And yes also has a 64 character limit for the name.

**Comment by grigi** [comment]
Makes sense, as a FK is a constraint on an index. We should just use the index naming system, but also for FK's.

**Comment by wallneradam** [comment]
Thanks, it works.
