### ISSUE TITLE
Can't I use .values() with relationships?

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#198]
Take the following example : 

```python
class Task(Model):
  title = fields.CharField(255)

class Actions(Model):
  title = fields.CharField(255)
  task = fields.ManyToManyField('models.Task', related_name='actions')

async def main():
  tasks = await Task.all().prefetch_related('actions').values('actions')
```

I'm trying to achieve the following structure:

```json
[
    {
        "id" : 1,
        "title" : "Task 1",
        "actions" : [
            {
                "id" : 1,
                "title" : "Action 1"
            }
        ]
    }
]
```

But it gives me `Selecting relation "actions" is not possible, select concrete field on related model`

Is this intended? Do I need to use a serializer to be able to achieve this structure?

How would I choose to return only specific fields from `actions` if not using `values`?

**Comment by abondar** [comment]
Hi

Currently, `values` and `values_list` only support fetching concrete fields, so that result looks like plain table. Still, you can request field from related models like this 

```
tasks = await Task.all().values('id', 'title', 'actions__id', 'actions__title')
```

Which will result in separate row for each related "action" 

In your case, indeed using serializer with such query will be the way 
`tasks = await Task.all().prefetch_related('actions')`

Currently we are not supporting excluding fields from fetched models, because we think it is not intuitive enough (because of async enviroment we can't autoload requested fields, like django does when you access field that was excluded from query)

I think we will investigate possibility to add support for nested objects in `values` in future, right now I'll mark this issue as feature request

**Comment by mojimi** [comment]
Thanks,

In the end a `to_json` method would be sufficient for my case

**Comment by abondar** [comment]
Do you mean `to_json` method for model instances, that will serialise all fetched info into dict?

**Comment by mojimi** [comment]
I think so, but in my case it would be for a executed queryset since I'm looking for a list of model instances

**Comment by grigi** [comment]
Would ’.values('actions__name')’ work? I have done test cases like that.

**Comment by mojimi** [comment]
@grigi When you use that instead of adding a list of actions it just adds the `name` of one action, I think it's the first one

**Comment by abondar** [comment]
I have idea that it would be quite neat to have such api

```
ojb.values('name', Prefetch("childs", queryset=Child.all().values('id', 'name')))
```

That would result in such dict

```
[{
  'name': 'Res 1',
  'childs': [{
    'id': 1,
    'name': 'John'
  }]
}]
```

@grigi What do you think about such design?

**Comment by grigi** [comment]
Could we not make it use kwargs?
E.g. values('name', childs=Childs.all().values(...)) ?
And if you pass a queryset it would auto prefetch?

This would implement a useable deserialisation step :thinking:
And be performant

(Generally in favour)

**Comment by grigi** [comment]
Some of the groundwork for this is in #260 as the request here is basically a SerDes framework.
Possibly expose this though a `.values_nested()` method that works very similarly, but only for reads.

**Comment by grigi** [comment]
Can be done via the Pydantic serialisation support we have since v0.16.0
Closing this as equivalently to done.

**Comment by looselytiedshoelaces** [comment]
Hi! Everyone! I just want to ask if this is possible now. Like also fetching the backward FK.

```python

class TableOne(Model):
    id = fields.IntField(pk=True)
    table1_col = fields.CharField(max_length=50)
    table2: fields.ForeignKeyField["TableTwo"] = \
        fields.ForeignKeyField(
            model_name="models.TableTwo", related_name="table1_rel")


class TableTwo(Model):
    id = fields.IntField(pk=True)
    table2_col: fields.CharField(max_length=50)
    table1_rel: fields.ReverseRelation["TableOne"]


rows = await TableTwo.all().prefetch_related("table1_rel")
```

Can I achieve this output?

```json
[
    {
        "id": 1,
        "table2_col": "value",
        "table1_rel": [
            {
                "id": 1,
                "table1_col": "value one"
            },
            {
                "id": 2,
                "table1_col": "value two"
            }
        ]
    },
]
```

I just made up those codes, but I hope you understand want I am trying to achieve. I am kind of refactoring some codes at the moment. TIA
