### ISSUE TITLE
Add Multicolumn index

### ISSUE THREAD

**Issue by RafRaf** [tortoise/tortoise-orm#207]
I know that tortoise already has a `unque_together` feature, but is there any way to add a multicolumn index without unique constraint?

**Comment by grigi** [comment]
:+1: An obvious oversight on our part.
What about adding an:
```py
indexes = ( (<fields>), …)
```
to the Meta like we do for `unique_together`?

**Comment by RafRaf** [comment]
Yeah. 👍 It looks like something from django world  :-)

**Comment by grigi** [comment]
@RafRaf  Please test v0.14.0 if it resolves this issue for you. https://tortoise-orm.readthedocs.io/en/latest/models.html#tortoise.models.Model.Meta.indexes

**Comment by RafRaf** [comment]
Sorry for the delay.
Yes, It works perfectly. Thank you.
