### ISSUE TITLE
Allow flash to receive extra keyword arguments and repass them to get_flashed_messaged

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#210]
**Is your feature request related to a problem? Please describe.**
When trying to create a standardized Exception -> User message flow, I found `flash`'s two parameters to be insufficient

**Describe the solution you'd like**
I would like `flash` to accept extra kwargs

**Describe alternatives you've considered**
For now we overwrited `flash` and `get_flashed_messages` but that was far from elegant

**Additional context**
The problem came about because our errors had a `title`, `category` and `detail`, which couldn't be translated into the current `flash` implementation

**Comment by grigi** [comment]
? Did you log this issue in the right project ?
I'm confused

**Comment by mojimi** [comment]
Very sorry! haha
