### ISSUE TITLE
unique_together field name escape

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#215]
**Describe the bug**

When you use `unique_together`, fields are not escaped. Which can cause error.

**To Reproduce**
```python
class UserParameter(BaseModel):
    user = fields.ForeignKeyField(model_name='models.User', related_name='parameters')

    key = fields.CharField(max_length=64)
    value = fields.TextField()

    class Meta:
        table = 'user_parameter'

        unique_together = ('key', 'user_id')
```

This code will generate error on MySQL, because `key` is a reserved keyword.

**Expected behavior**

The generated SQL should look like this:
```sql
UNIQUE (`key`, `user_id`)
```

**Additional context**

Now a workaround is to escape the keyword in the string in the tuple of ˙unique_together`. But in my opinion it is not the way it should work.

It may be another issue, but UNIQUE indexes should have a unique name as well. Because this will create an index in the table called `key`.

**Comment by wallneradam** [comment]
I`ve solved this in my own schema_generator, and it works:
```python
class MariaDBSchemaGenerator(MySQLSchemaGenerator):
    UNIQUE_CONSTRAINT_CREATE_TEMPLATE = "UNIQUE KEY `{key_name}` ({fields})"

    def _get_unique_constraint_sql(self, field_names: List[str]) -> str:
        key_name = "{fs}_{h}".format(
            fs="_".join(field_names)[:21],
            h=self._make_hash2(*field_names, length=8)
        )
        return self.UNIQUE_CONSTRAINT_CREATE_TEMPLATE.format(
            fields=", ".join(['`' + fn + '`' for fn in field_names]),
            key_name=key_name
        )
```

But I think it could be in the `BaseSchemaGenerator`.

**Comment by grigi** [comment]
Yes, this needs to call the quote function in the base generator :+1:

**Comment by grigi** [comment]
@wallneradam Please test v0.14.0 if it resolves this issue for you.

**Comment by wallneradam** [comment]
@grigi  Sorry, I was too busy... Yes, it solves the escaping issue.
