### ISSUE TITLE
unique_together and foreign key field

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#216]
**Describe the bug**
I don't know if it is a bug. But it is confusing a bit.
When you use `ForeignKeyField` with `unique_together`, the field name should be without "_id" suffix (which I think is good), but in the list of fields I need to write the field name with '_id' suffix.

**To Reproduce**
```python
class UserParameter(BaseModel):
    # Here only 'user' is needed
    user = fields.ForeignKeyField(model_name='models.User', related_name='parameters')

    key = fields.CharField(max_length=64)
    value = fields.TextField()

    class Meta:
        table = 'user_parameter'

        unique_together = ('key', 'user_id')  # Here user_id is needed
```

**Expected behavior**
I think it should be working without the '_id' suffix

**Additional context**
It is related to #215 .

**Comment by grigi** [comment]
`unique_together = ('key', 'user')`
should be equivalent to:
`unique_together = ('key', 'user_id')`

I agree. I'll consider this to be equivalent to a bug, as we already morph the data if source_field was defined.

Do you need this asap, or can I do this and #215 with the Field/schema refactor work?

**Comment by wallneradam** [comment]
No need asap, they can be solved easily with workarounds.

**Comment by grigi** [comment]
@wallneradam Please test v0.14.0 if it resolves this issue for you.

**Comment by wallneradam** [comment]
@grigi Yes, it is good now. Though I still has a problem with it, I'll create a different issua about it.
