### ISSUE TITLE
Add database functions in queries to support manipulation of fields

### ISSUE THREAD

**Issue by zoliszeredi** [tortoise/tortoise-orm#217]
**Is your feature request related to a problem? Please describe.**
As of [v0.13.2](https://github.com/tortoise/tortoise-orm/tree/0.13.12) there is no support for database functions. Depending on your use-case, query fields might require extra processing: 
 - for NULLs COALESCE for comparisons and conversions
 - for text types: TRIM for trailing white-spaces, LENGTH, REPLACE, SUBSTRING, CONCAT

**Describe the solution you'd like**
Add support for functions via an importable module (e.g. `tortoise.models.functions`)
that implements database functions (like COALESCE) and can wrap model fields possibly via annotations like:
```python
from tortoise.models.functions import Coalesce

class User(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
    email = fields.TextField()
    username = fields.TextField()
    join_date = fields.DateTimeField()

users = await User.annotate(
    screen=Coalesce("name", "username", "email"),
    clean_join_date=Coalesce('join_date', datetime.datetime(2011, 12, 31),
).filter(
    clean_join_date__gt=datetime.datetime(2012, 1, 1)
).values_list('screen', 'clean_join_date')
```

**Describe alternatives you've considered**
The two most well known ORMs for python [SQLAlchemy](https://docs.sqlalchemy.org/en/13/core/functions.html?highlight=coalesce#sqlalchemy.sql.functions.coalesce) and [Django ORM](https://docs.djangoproject.com/en/2.2/ref/models/database-functions/#coalesce) have similar APIs:

**Additional context**
The underpinning SQL library pypika [does implement](https://github.com/kayak/pypika/blob/v0.8.0/pypika/functions.py) and have [documented](https://pypika.readthedocs.io/en/latest/api/pypika.functions.html?highlight=coalesce#pypika.functions.Coalesce) the most important database functions.

From the pypika [documentation](https://github.com/kayak/pypika#strings-functions) for example of string functions:

```python
from pypika import functions as fn

customers = Tables('customers')
q = Query.from_(customers).select(
    customers.id,
    fn.Concat(customers.fname, ' ', customers.lname).as_('full_name'),
)
```

**Comment by grigi** [comment]
Thank you for this well presented/thought out feature request @zoliszeredi 

We already have support for some aggregate functions, and I don't see much new required to support other functions. 
(Although the name "Aggregate" is too specific, we should probably change it to "Function")

Looking at the code, adding single-parameter functions will be trivial, multi-parameter functions will need a refactor. Shouldn't be too difficult.

Do you want to have a go?
