### ISSUE TITLE
Can I get join query without foreign keys

### ISSUE THREAD

**Issue by Huangkai1008** [tortoise/tortoise-orm#221]
I have two models named user and role

```python
class User(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
    group_id = fields.IntField()


class Group(Model):
    id = fields.IntField(pk=True)
    group_name = fields.TextField()
```
There is a record in the user table {“id”: 1, "name": "tom", "group_id": 1}
There is a record in the group table {"id": 1, "group_name":  "group A"}

How can i get the user result within group_name {"id": 1, "name": "tom", "group_name": "group A"},  thanks

**Comment by abondar** [comment]
Hi

You can't use relations logic without using fk fields. 
But fk fields do not force you to use constraint, so if you would describe your model like 
```
class User(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
    group = fields.ForeignKeyField('models.Group', related_name='users')
```

Then you will be able to do query like 
```
result = await User.filter(...).values('id', 'name', group_name='group__group_name')
```

Just declaring ForeignKeyField doesn't force any new fields on your database schema, so it will just use `group_id` as source field for your relation

**Comment by Huangkai1008** [comment]
Oh, I see, thanks !
