### ISSUE TITLE
Drop Database isnt working in DB_URL

### ISSUE THREAD

**Issue by partha7827** [tortoise/tortoise-orm#232]
drop database function is using database username as a database name instead of database name
![Screenshot from 2019-11-02 15-51-54](https://user-images.githubusercontent.com/6007655/68069651-19ff0100-fd89-11e9-8722-275988a39c66.png)

**Comment by grigi** [comment]
I think I know what is going on here.

For the drop database method, it can't be ON the db it is going to drop, so it connects without specifying the db, and therefore uses the users default DB, which may not exist.
