### ISSUE TITLE
Indexes and foreign key fields

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#238]
**Describe the bug**
It is the same as #216 . Just with `indexes`, not `unique_together`. It is needed to use the '_id' suffix.

**Comment by grigi** [comment]
Thanks for pointing this out, I'll have a look at it.

**Comment by grigi** [comment]
I just released v0.15.0 Please test to see if it does it right :-)

**Comment by wallneradam** [comment]
Thanks! Yes, it seems to be good.
