### ISSUE TITLE
Q-objects

### ISSUE THREAD

**Issue by AEnterprise** [tortoise/tortoise-orm#240]
after working withe the Q objects i have some questions, remarks and things that don't work as intended/expected

- a blank Q object in AND mode works with just 1 argument to filter on, however OR mode requires a minimum of 2, quite inconvienient when your Q object is assembled based on client data
- you can't combine keywords and nested Q objects into the same Q object but you got to wrap them into seperate Q objects to then combine into one master Q object to handle both, throws an explicit exception so seems to be intended behaviour but makes things more complex
- are there any performance penalties to using nested Q objects several layers deep (other then ofc the overhead of python constructing objects)

**Comment by grigi** [comment]
1. I think this is a bug, ideally we want Q objects to be consistent in behaviour
2. We should consider adding this as a feature if the syntax makes sense?
3. The SQL generated should be the same if one nests identity Q objects, so I think not. There will be a Python-level overhead in construction evaluating them, but that is pretty minimal? I think.

Could you provide a some sample code snippets of 1 & 2?

**Comment by AEnterprise** [comment]
for 1 it's quite simple just filtering on any table: with ``Q(join_type="OR", user_id=106354106196570112)`` triggered it for me

as for 2 it's quite similar, right now it comes down to ``Q(join_type="AND", Q(guild_id=617292599966957582), Q(user_id=106354106196570112))`` while it would be much nicer to be able to do ``Q(join_type="AND", guild_id=617292599966957582, Q(user_id=106354106196570112))``

**Comment by grigi** [comment]
Ok, 1 should be fixed as a NOP.
I am uncertain about 2, well have to experiment with it myself a bit.

**Comment by AEnterprise** [comment]
more testing done, another issue/bug with Q objects: https://gist.github.com/AEnterprise/fc485a4643177ee04fa4c1c2b74f3c2c

the Q object came down to 
```
Q(join_type="AND", Q(guild_id=617292599966957582), Q(join_type="OR", id__gt=5, id__lt=50))```

**Comment by grigi** [comment]
The `Q(join_type="AND", guild_id=617292599966957582, Q(user_id=106354106196570112))` is a limitation of the Python function call syntax.
There is a requirement that positional args are BEFORE the keyword args. Hence that is a syntax error, and there is nothing that I can do.

**Comment by grigi** [comment]
I have done lots of tests, and I can't actually verify any of the Q related behaviour here. I'm not certain what is going on.

That stacktrace is complaining about some kind of subquery, which Q objects have no control over.

Could you give me some more info please?

**Comment by grigi** [comment]
I have at least confirmed that wrapping everything in Q objects results in exactly the same SQL generated as not.
And that you don't have to pass it the exactly correct type, as it will try coerce the type depending on the model.
If you send 'moo' for an integer, it will explode with a ValueError as one would expect.

So we should add docs to state that type conversion is deferred to query generation, so one would have to handle conversion exceptions around the `await moo.filter(Q_object)` if you deal with user input.

**Comment by AEnterprise** [comment]
the issue isn't with python syntax though, i put in the wrong order here. if i put the Q object before the kwargs i get an error raised by the Q object itself (https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/query_utils.py#L173)

for the Q object exception i don't really have much more info, other then that it happens when i'm re-assembling the Q object based on the info the client sends (the first line in the log)

i'll add the type coercion info once i write the docs on those objects

**Comment by grigi** [comment]
After thinking it through, since the ordering of the AND's or OR's doesn't matter, I see no reason to not allow both. I'll work on it for you the weekend.

**Comment by grigi** [comment]
Ok, that should resolve point 2. I still can't actually replicate point 1.
At least by now there is a lot more `Q()` tests in the CI :smile:

**Comment by AEnterprise** [comment]
thanks a lot! i'll do some further testing for replicating the rest, must be something with the way i'm re-assembling them

**Comment by grigi** [comment]
I just released v0.15.0 It should have fix for 2

**Comment by AEnterprise** [comment]
2 is indeed fixed, for the subcriterion one i found a reproduction case, it happens with nested filter that include blank filters

using a code set filter of ``Q(Q(Q(id__gt=5), Q(), join_type=Q.OR), guild_id=123, join_type=Q.AND)`` triggers it every time for me

model: https://github.com/gearbot/Dashboard-api/blob/dev/Utils/DataModels.py#L17-L26

**Comment by grigi** [comment]
Aha! I can replicate it. Seems to require an OR with blank...

**Comment by AEnterprise** [comment]
thanks a lot! sorry for not getting to the bottom and figuring out it was the empty or thing the first time

**Comment by grigi** [comment]
Don't apologise for something that we can't expect you to just know.
We are all human... I suspect... Probably... :grin:

**Comment by AEnterprise** [comment]
still, as fellow dev i should be able to do better for bug reports

anyways that seems everything taken care of, thanks for all the improvements and explanations

**Comment by grigi** [comment]
I dunno, most bug reports I get from developers still pale in comparison to some of the better QA testers. :man_shrugging:
