### ISSUE TITLE
F Expression for atomic update?

### ISSUE THREAD

**Issue by bbedward** [tortoise/tortoise-orm#245]
I'm looking for a way to do an atomic update of a field or multiple fields (to increment it)

In Django ORM this is possible using the `F` class, I didn't see anything equivalent in tortoise documentation.

The goal would be to achieve something like this

```
counter = Counter.objects.get_or_create(name = name)
counter.count = F('count') +1
counter.save( update_fields=["count"] )
```

To generate some SQL like

`update counter set count = count + 1`

(In my case I also want to cast in some cases)

`update counter set count = cast(cast(count as integer) + 1) as char)`

Wondering if either of the above are possible yet with tortoise.

**Comment by grigi** [comment]
Interesting :thinking: 
I didn't even know about this from Django.

Unfortunately we don't have any such feature, or even planned at the moment.
If you want to have a go at it, you're welcome to try.

Or we can come up with a workaround. Maybe making custom SQL a bit easier to do?

**Comment by bbedward** [comment]
I can try, no promises though 😛

For reference, we would probably want an entire expressions API similar to Django:

https://docs.djangoproject.com/en/2.2/ref/models/expressions/

**Comment by grigi** [comment]
I had a look, and much of this seems to wrap directly to PyPika expressions.
We already have `Q`, `Func` & `Aggregate`, We do `Value` implicitly.
I don't see anything resembling `F` expressions unfortunately, but the rest I do see.

**Comment by bbedward** [comment]
I'll take a look at pypika, atomic updates (without raw SQL) is definitely a desirable feature to avoid any race conditions when incrementing data.

**Comment by grigi** [comment]
At worst you can do a `async with in_transaction():` block to guarantee atomicity. But performance won't be as good as F-Expressions.

**Comment by AEnterprise** [comment]
@grigi i don't think that will actually guarantee atomicity due to the new pooling, as reading doesn't place any locks unless you add "for update" to the select query, it is theoretically possible to still have a race

**Comment by grigi** [comment]
The in_transaction() will immediately start a transaction, which depending on your DB, will guarantee race detection via a raised exception. (InnoDB or PostgreSQL should be safe.)
True, that the row won't be locked until the first update.

**Comment by jet10000** [comment]
https://www.revsys.com/tidbits/keeping-django-model-objects-ordered/

Here is an example using F expression

**Comment by srini-akhil** [comment]
hey how to use F expressions for list field? 
Example SQL QUERY: update page set feedback[1] =feedback[1]+1 ;
anyway to do this using tortoise ORM? @grigi
