### ISSUE TITLE
Count query uses the wrong WHERE clause

### ISSUE THREAD

**Issue by svms1** [tortoise/tortoise-orm#249]
I found a strange issue and I'm having a hard time tracking it down. I'm not sure whether it's actually a bug in tortoise or something wrong with PyPika.

When doing a `count()` query with a filter on a `DatetimeField`, the filter is overwritten with the datetime at execution / query building. This does not happen in a normal `all()` query.

**Example script:**
```
import logging
from datetime import datetime, timedelta
from tortoise.models import Model
from tortoise import fields, Tortoise, run_async


class TestModel(Model):
    id = fields.IntField(pk=True)
    when = fields.DatetimeField(auto_now_add=True)


async def init():
    await Tortoise.init(
        db_url='sqlite://db.sqlite3',
        modules={'models': ['__main__']}
    )
    await Tortoise.generate_schemas()


async def insert():
    await TestModel.create()


async def query():
    when = datetime.utcnow() - timedelta(hours=6)
    logging.info(when)
    print(
        await TestModel.filter(when__lt=when).count()
    )
    print(
        await TestModel.filter(when__lt=when).all()
    )


async def run():
    await init()
    await insert()
    await query()


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    run_async(run())
```

The logged datetime is e.g. `2019-11-27 08:19:38.384482`. The logged queries are:

    SELECT COUNT(*) FROM "testmodel" WHERE "when"<'2019-11-27 14:19:38.384740'
    SELECT "id","when" FROM "testmodel" WHERE "when"<'2019-11-27 08:19:38.384482'

As you can see, the datetime in the `COUNT(*)` query is wrong. I was able to confirm that the `Q` objects are correct. After the `self.query._select_other(Count("*"))` call in `class CountQuery(AwaitableQuery)` the wrong query is built, no query exists before that. This happens with any of `lt`, `lte`, `gt`, `gte` and even equals.

Any ideas where things might go wrong?

**Comment by grigi** [comment]
Wow... It's like it replaced the `when` with `now()`...
Now I gotta try replicate it locally.

**Comment by grigi** [comment]
Ok, definitely only happens when `auto_now` or `auto_now_add` is set.
I can confirm it uses `now()` and confirm it happens regardless of DB backend.

**Comment by grigi** [comment]
Release v0.15.2 should have the fix for this. Please test and confirm.

**Comment by svms1** [comment]
I can confirm that the query and its result is correct now. Thanks for the insanely fast fix!

**Comment by grigi** [comment]
You logged the issue on the right time :-P
Had you logged it two days ago, I would not have seen it until today.
Such is life :man_shrugging:
