### ISSUE TITLE
Pydantic support

### ISSUE THREAD

**Issue by wallneradam** [tortoise/tortoise-orm#250]
**Is your feature request related to a problem? Please describe.**
It is actually not a feature request, but a question about integrating the feature in subject.
My project uses FastAPI as backend, which uses Pydantic models everywhere. It is a wonderful project uses all good things in modern Python. I'm working on a solution, to convert Tortoise model to Pydantic model runtime. It has started working, though not complete yet, but will be in a few days.
It makes my API functions very clean, because I can use my models as input and output of my API calls, no need to specify the same thing in different way. It has automatic documentation without extra work, And it solves the serialization problems in #13 as well (https://pydantic-docs.helpmanual.io/usage/exporting_models/).

**Describe the solution you'd like**
I extended the Tortoise model like this:
```python
class Model(models.Model):
    # If not empty, only fields this property contains will be in the pydantic model
    __pydantic_include__: Tuple[str] = ()
    # Fields listed in this property will be excluded from pydantic model
    __pydantic_exclude__: Tuple[str] = ()
    # Computed fields can be listed here to use in pydantic model
    __pydantic_computed__: Tuple[str] = ()

    @classmethod
    @functools.lru_cache(maxsize=128)
    def pydantic_model(cls, *, exclude: Tuple[str] = None, include: Tuple[str] = None,
                       computed: Tuple[str] = None, name=None) -> pydantic.BaseModel:
        ...
```
The `pydantic_model` static method will create a Pydantic class which can be used as schema descriptor and serializer for FastAPI. I even created a solution, which can use comments before fields as description in the automatic documentation (OpenAPI) of FastAPI.

It can generate multiple Pydantic class from the same Tortoise class, to be able to use different views for the same database object. E.g. you can use less fields for one API call than the other. Or you can have private fields. The defaults can be described in the `__pydantic` prefixed properties. And if you need more views you can use the optional parameters of the method. It may be better to include this in the `class Meta` to make it more Tortoise friendly, it was just a quick implementation.

Then the created `PydanticModel` class has an async `from_orm` method which can be used to convert the database results to the pydantic counterpart. Then you can just give it to the API to send it serialized as JSON or anything you want. The from_orm can automatically fetch the needed not already fetched foreign key and many2many fields.

**Additional context**
Are you interested in this? 
It is not an easy one. I'm not sure if it could work with Pypy or anything other than cPython. It uses `gc` to find `ForwardReference` classes defined in models and runtime class creations, inspect and things like that. But this way Tortoise could be the ORM for FastAPI.

Also I may need help in writing unit tests and to make it compatible with your automated test system.

**Comment by grigi** [comment]
I'm definitely interested.
Also, we already only support _some_ functionality for PyPy, so it's fine if we miss out on some more functionality.

I looked at FastAPI and Pydantic support in the future, but since I have no urgent need right now, I probably won't get around to making it work any time soon.

I'll gladly help with unit tests for you.

**Comment by wallneradam** [comment]
Is it ok to make Pydantic as dependency. Or do you prefer to make it somehow optional?
If the 2nd, which way you prefer? I can think 2 ways for that:
- dynamic import when you call `pydantic_model` method. This way pydantic module is only needed when you call it. It may be hard to make your linting system happy, but in my opinion it is more integrated solution.
- create a different python file for the Model class supporting Pydantic. So if you need this feature, you need to use that model as base model (this is the classic Java approach).

**Comment by grigi** [comment]
I'd go for option 1. We already have to jump through many hoops for linting, we can easily do more.
And since we are so metaprogramming heavy, we already have pylint plugins (and considering mypy plugin).
