### ISSUE TITLE
Connect to PostgreSQL with SSL + self-signed certificate

### ISSUE THREAD

**Issue by lxmnk** [tortoise/tortoise-orm#255]
**Describe the bug**
I'm trying to connect to a PostgreSQL database that has SSL enabled on. Also it has self-signed certificate.

**To Reproduce**
Try to connect to PostgreSQL DB with SSL and self-signed certificate.

**Expected behavior**
Allow to pass `ssl.SSLContext` into `Tortoise.init`.

**Additional context**
I've found #150, but it can't resolve my problem.

**Comment by grigi** [comment]
Hi

The verbose init form should work:
```python3
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

await Tortoise.init(
    config={
        "connections": {
            "default": {
                "engine": "tortoise.backends.asyncpg",
                "credentials": {
                    "database": None,
                    "host": "127.0.0.1",
                    "password": "moo",
                    "port": 54321,
                    "user": "postgres",
                    "ssl": ctx
                }
            }
        },
        "apps": {
            "models": {
                "models": ["some.models"],
                "default_connection": "default",
            }
        },
    }
)
```

:thinking: I see that mysql driver also accept an SSL context, it would be useful to inject either a custom ssl context, or have tortoise generate a verified, and unverified ssl context via the url-style init?

**Comment by lxmnk** [comment]
Thank you for quick answer!

Using code above I have the following error:

```
  File "/app/utils/db.py", line 28, in db
    'default_connection': 'default'
  File "/usr/local/lib/python3.7/site-packages/tortoise/__init__.py", line 640, in init
    await cls._init_connections(connections_config, _create_db)
  File "/usr/local/lib/python3.7/site-packages/tortoise/__init__.py", line 478, in _init_connections
    db_params = deepcopy(info["credentials"])
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SSLContext objects
```

I think injecting custom ssl context will be better. For example, you can download self-signed certificates from Google Cloud and use them in context.

**Comment by grigi** [comment]
Ugh, why deepcopy? surely a copy would do?
I wrote a test for it, and released v0.15.4
The earlier proposed solution now really _should_ work. Please test :smile:

**Comment by lxmnk** [comment]
Pickle error disappeared, but here is another one :(

```
  File "/app/utils/db.py", line 28, in db
    'default_connection': 'default'
  File "/usr/local/lib/python3.7/site-packages/tortoise/__init__.py", line 644, in init
    cls._init_apps(apps_config)
  File "/usr/local/lib/python3.7/site-packages/tortoise/__init__.py", line 494, in _init_apps
    cls.get_connection(info.get("default_connection", "default"))
AttributeError: 'list' object has no attribute 'get'
```

**Comment by grigi** [comment]
Could you give more info as to how you are calling it?
I don't validate the full schema for the config object, and that can only happen if the object is structured wrong that I can see?

It looks like you passed in:
```python
await Tortoise.init(
    config={
        "connections": {
            ...
        "apps": {
            "models": ["some.models"]
        },
    }
)
```
instead of
```python

await Tortoise.init(
    config={
        ...
        "apps": {
            "models": {
                "models": ["some.models"],
                "default_connection": "default",
            }
        },
    }
)
```

**Comment by lxmnk** [comment]
Oh, I'm sorry. I've really rewrite code incorrectly. Now app successfully connected to DB. Also I've created some objects for test. Thank you very much!

**Comment by grigi** [comment]
Documented SSL: https://tortoise-orm.readthedocs.io/en/latest/databases.html#passing-in-custom-ssl-certificates

**Comment by tleerai** [comment]
> Documented SSL: https://tortoise-orm.readthedocs.io/en/latest/databases.html#passing-in-custom-ssl-certificates

Updated link: https://tortoise.github.io/databases.html#passing-in-custom-ssl-certificates
