### ISSUE TITLE
Ability to SUM multiple columns

### ISSUE THREAD

**Issue by bbedward** [tortoise/tortoise-orm#257]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use the `Sum` function over multiple columns.

Example for a model

```
class Stats(Model):
    one_column = fields.IntField(default=0)
    two_column = fields.IntField(default=0)
```

I'd like to be able to do run a query like `select sum(one_column+two_column) from stats`

**Describe the solution you'd like**
`Stats.annotate(total_sum=Sum('one_column+two_column'))` (or something similar)

**Additional context**

Pypika can already resolve this as seen in this test:

https://github.com/kayak/pypika/blob/16339f85ed871d937609e9dbe26487b382ca5211/pypika/tests/test_formats.py

`fn.Sum(self.table_abc.fizz + self.table_abc.buzz)`

**Comment by grigi** [comment]
Hmm, This would be a useful feature.
There is a syntax issue that could get in the way (string + string is an example). So we should probably wrap the strings in "field name" objects (and translate strings into one or multiple "field name" objects, to keep simple (and legacy) syntax working.)

Note that Functions/aggregations/Q have to resolve the actual columns lazily, because we map the fields to columns. 

:thinking: this might be rolled together with some of #245

**Comment by lntuition** [comment]
With #245, apply F field to annotation can be workaround. maybe like this?
```python
Stats.annotate(total_sum=F('one_column')+F('two_column'))
```

If you agree, then i want to try this. But I think it can be hard work.@grigi Do you agree with this workaround? And also can you help me once more?

**Comment by lntuition** [comment]
With my current view, I think add variable something like `_annotation_f_expression` into `QuerySet` and modify queryset and query utils looks good. I hope my solution looks ok :smiley:

**Comment by grigi** [comment]
:thinking: It does make sense to merge `F` operators and Aggregations/Functions. There is some code overlap between them already.

What about merging the functionality of F and Functions? 
Then one could write
```py
Stats.annotate(average_sum=(Sum('one_column') + Sum('two_column')) / 2)
```
and it would do what one expects? And your example would work too?

**Comment by lntuition** [comment]
I agree that adding `F` operator functionality to `Functions` is best solution. I need to check with that direction. Wow your example is better than mine 👍

**Comment by lntuition** [comment]
@grigi I found current `F` expression is wrapped with Field of pypika. Solution with adding operator functionality to function is looks elegance. But it can annoy current code and structure(inherit Field class to Functions is hmm...) Maybe applying this solution should force rebuilding all resolve related logic. So I think this is not good workaround. 

As @bbedward said, pypika already can process arithmetic expression like below.
``` python
fn.Sum(self.table_abc.fizz + self.table_abc.buzz)
```
So i think applying this solution is better. What do you think about this @grigi ?

**Comment by lntuition** [comment]
Of course, my final goal is
- allow Arithmetic expression with Functions parameter -> suggested as a solution to this issue
- allow Arithmetic expression with Functions -> suggested by yours
- merge `F` expression to `Functions` -> to prevent duplication

But i think it should be really hard work.. and also first feature is some different with above feature.

``` python
class Stat(Model):
    o = fields.IntField()
    t = fields.IntField()

...

await Stat.create(o=1, t=2)
await Stat.create(o=1, t=3)
res = await Stat.annotate(s=Sum("o * t")).values("s")
print(res[0]["s"]) # 5
res = await Stat.annotate(s=(Sum("o") * Sum("t"))).values("s")
print(res[0]["s"]) # 10
```

Like above example, we eventually should need both feature(allow arithmetic expression with function and allow arithmetic expression with function parameter)

**Comment by grigi** [comment]
The real issue with just using pypika directly is what to do when column names and field names don't match? (They often don't). Now the user would have to keep track of these differences.

So basically we just need something elegant from an API pov.

Both the current over-wrapping that `Function` does, and barely-anything that `F` is fine, as long as we can resolve the columns from fields lazily.

Ah, there is a difference between `Sum('a' + 'b')` and `Sum('a')+Sum('b')` :thinking: 

I'm not a fan of `Sum('a + b')` as that means we have to provide our own parser, which I really don't want to do. I suppose lazy local resolution and using `eval` could do it, but that just makes me cringe a bit.

Maybe a syntax more like `Sum(F('a')+F('b'))` could do it without needing to parse anything?

**Comment by grigi** [comment]
Oh, I forgot to add that we can break backwards compatibility on both F & Function, as long as we have a good reason for it.
We still haven't declared a stable API yet.

**Comment by lntuition** [comment]
> It does make sense to merge F operators and Aggregations/Functions. There is some code overlap between them already.

But django allow `F` expression to annotation. [link](https://docs.djangoproject.com/en/3.0/ref/models/expressions/#using-f-with-annotations)

> The real issue with just using pypika directly is what to do when column names and field names don't match? (They often don't). Now the user would have to keep track of these differences.

Ah, I don't think about this. maybe `source_field` param can do this.

> Maybe a syntax more like `Sum(F('a')+F('b'))` could do it without needing to parse anything?

This can be good solution without providing our own parser(also i found django do like this). I need to check about this solution.

**Comment by grigi** [comment]
Yes, `source_param` is a prime example where we want a Model to be different compared to a legacy DB column name. 

We should definitly allow `F` expressions in annotations. And the inverse, of annotations in `.update(...)` operations as well. Maybe we can get away by just making `Function` aware of `F` expressions?

**Comment by lntuition** [comment]
> We should definitly allow `F` expressions in annotations. And the inverse, of annotations in `.update(...)` operations as well. 

Sorry, I cannot understand well. Could you give me some example?

**Comment by grigi** [comment]
e.g.  `await model.filter(a='b').update(c=Coalese('d', 'default-value))`

**Comment by lntuition** [comment]
> Maybe we can get away by just making `Function` aware of `F` expressions?

I think no. I think i should be allowing `Function` to update params. it is ouside of Function params.

1.`Sum(F('a')+F('b'))` = `F` expression to `Function` params
2.`total_sum=F('one_column')+F('two_column')` = `F` expression to annotate Params
3.`update(c=F('a')+1)` = `F` expressions to update parames -> i think it is resolved
4.`update(c=Coalese('d', 'default-value))` = `Function` to update params.

I think 2, 3 is similiar(also inner is very different too) but 1 and 4 are different subject. 
umm.. i think we should do 1 first, then 2, and last 4.

**Comment by grigi** [comment]
What is point 2 exactly?

**Comment by lntuition** [comment]
> F() can be used to create dynamic fields on your models by combining different fields with arithmetic:

With [django document](https://docs.djangoproject.com/en/3.0/ref/models/expressions/#using-f-with-annotations), this feature is for generate dynamic fields with db's value. 
e.g `await model.annotate(a_plus_b = F('a') + F('b')).values("a_plus_b")`

**Comment by grigi** [comment]
Ah, so part of annotate.

I thought it could be an assignment as a variable, which is a feature I'm not comfortable supporting, as now the var type is mutated, and when we do a `.save()` we need to rewrite it into an update that returns the generated value. 
Which is really only supported atomically by PostgreSQL. This is a lot of plumbing change for dubious benefit.

Ok, your plan seems fine, and your high-level test cases is a good spec :+1:

**Comment by lntuition** [comment]
@grigi Thank you so much for your discussion. I will make PR with 1 (but i'm not sure that i'm doing good. i will make WIP PR soon. Review that PR plz!) As you said, we need to think more carefully about 2 and 4.
