### ISSUE TITLE
can't create row with foeign keys

### ISSUE THREAD

**Issue by skunkwerk** [tortoise/tortoise-orm#259]
Error:
python3.8/site-packages/tortoise/models.py", line 413, in __init__
    if value and not value._saved_in_db:
AttributeError: 'str' object has no attribute '_saved_in_db'

Model that doesn't run:
class CustomerOrganizationRelation(Model):
	id = IntField(pk=True)
	customer_id = ForeignKeyField('models.Customer')
	organization_id = ForeignKeyField('models.Organization')

Model that will run:
class CustomerOrganizationRelation(Model):
	id = IntField(pk=True)
	customer_id = TextField()
	organization_id = IntField()

Code:
record = CustomerOrganizationRelation(customer_id = 'Dna3d', organization_id=1)
await record.save()

**Comment by grigi** [comment]
Hi

When creating a FK, one gets a `*_id` extra, so you don't need to specify a _id field

Try this instead:
```py
class CustomerOrganizationRelation(Model):
    id = IntField(pk=True)
    customer = ForeignKeyField('models.Customer')
    organization = ForeignKeyField('models.Organization')
```

Then you can do 
```py
record = await CustomerOrganizationRelation.create(customer_id = 'Dna3d', organization_id=1)
```

Also, I see you are using `TextField`, it is not recommended to use it as an indexable field, as it is designed to store a HUGE amount of text, and some DB's like MySQL will fail to index it. Rather use `CharField(max_len=255)` where you can get away with it.

**Comment by skunkwerk** [comment]
Awesome, thank you - wish this was documented!

**Comment by grigi** [comment]
@skunkwerk Could you please indicate where in the docs it should have been made clearer, then I'll ensure that something is added there.
I was under the impression this was in the documentation. So I'm treating it as a failure of some sort.

**Comment by grigi** [comment]
Described the `_id` and caveats for FK: https://tortoise-orm.readthedocs.io/en/latest/models.html#the-db-backing-field

**Comment by GMbrianlaw** [comment]
I agree, and I also had the same problem. I think `_id` should not be automatically appended to the end of the parameter.
