### ISSUE TITLE
Indices support in database.

### ISSUE THREAD

**Issue by JuniorJPDJ** [tortoise/tortoise-orm#266]
I'd like to see an possibility to at least create one `index` or more.
It will allow us eg. to have set of columns unique.
I'm trying to rewrite plain aiosqlite code to tortoise and gain `pg`/`mysql` support but I just can't because I decided to use indices.
Example query I'd like to be able to model:
```
CREATE UNIQUE INDEX history_idx ON history(feed_id, post_id);
```

**Comment by grigi** [comment]
This is supported?
https://tortoise-orm.readthedocs.io/en/latest/models.html#tortoise.models.Model.Meta.unique_together

**Comment by JuniorJPDJ** [comment]
Oh thank you very much then. I'll check it.

**Comment by JuniorJPDJ** [comment]
Yes, thank you.
It works, my bad.
I'd like not to create new issue, but I've question if something like that is implemented:
```
			CREATE TABLE IF NOT EXISTS feeds (
				id INTEGER PRIMARY KEY AUTOINCREMENT,
				url TEXT NOT NULL UNIQUE
			);

			CREATE TABLE IF NOT EXISTS history (
				feed_id INTEGER NOT NULL,
				post_id TEXT NOT NULL,
				FOREIGN KEY (feed_id)
					REFERENCES feeds (id)
						ON UPDATE CASCADE
						ON DELETE CASCADE
			);
```

I'm asking about `REFERENCES` section. It's supposed to delete every related key if his foreign key is deleted.

**Comment by grigi** [comment]
https://tortoise-orm.readthedocs.io/en/latest/fields.html#tortoise.fields.relational.ForeignKeyField
The `on_delete` param should set that.

**Comment by JuniorJPDJ** [comment]
Thank you very much :D 
I've not found this in docs.
Marking as resolved.
