### ISSUE TITLE
unique TextField not allowed

### ISSUE THREAD

**Issue by om26er** [tortoise/tortoise-orm#268]
**Describe the bug**
I am not able to set `unique=True` on a TextField, it raises the exceptions
```
tortoise.exceptions.ConfigurationError: TextField can't be indexed
```
**To Reproduce**
Just create a simple model using the following code and initialize tortoise.
```
class Something(Model):
    uid = fields.IntField(pk=True)
    myfield = fields.TextField(unique=True)
```

**Comment by AEnterprise** [comment]
you want a charfield or similarly probably. textfield uses the "text" datatype, those can not be fully indexed. for mysql best they support is partial by saying the first x chars of the textfield should be seen as prefix and unique: https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-column-prefixes

not sure if postgres supports this, documentation doesn't say it doesn't but i'm not as familiar with postgres data types: https://www.postgresql.org/docs/9.1/textsearch-tables.html

**Comment by grigi** [comment]
Hi, @AEnterprise is correct. Since we can't guarantee that a textfield can be indexed correctly using a btree, we disabled index & unique on it. The same for binaryfield & jsonfield.

One could use custom indexes on text/json, depending on db, but we have not yet added support for non btree indexes yet.

**Comment by om26er** [comment]
> you want a charfield or similarly probably.

that is true, I changed the code to CharField and now it works. Thanks

**Comment by grigi** [comment]
We should improve on the error messages some more.
