### ISSUE TITLE
Should DELETE honour limit and offset?

### ISSUE THREAD

**Issue by grigi** [tortoise/tortoise-orm#27]
When I do
```py
await IntFields.all().order_by('intnum').limit(10).delete()
```
I expected it to delete the first 10 `IntFields` items ordered by lowest value of `intnum`.

I read up, and just about all databases support deleting on a limit, as long as one doesn't do a join.

I feel we should decide what should be allowed, and then raise an exception if you build a queryset that does e.g. offset and delete, or join+limit and delete?

And make the same limitations apply to `count()` ?

**Comment by Zeliboba5** [comment]
It definitely should work that way, but as much as I see sample SQL queries for such actions, this is implemented by subqueries. Even though it shouldn't be hard to implement it right away I would prefer to leave it as post-1.0 feature and bundle up it's implementation with subqueries. 
At the moment it's quite easy to do similar actions just by two separate queries.
