### ISSUE TITLE
Equivalent of "UPDATE...WHERE"?

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#272]
Just a quick question, is there a way of doing the following :

```
async with in_transaction() as connection:
    await connection.execute_query(f"UPDATE EMPLOYEE SET SALARY = 5000 WHERE OCCUPATION = DEVELOPER")
```

But without using raw sql, something like :

`await Employee.filter(occupation='developer').batch_update(salary=5000)`

I understand I could also do a for loop inside a transaction but there's no way that's the right way to do it.

**Comment by AEnterprise** [comment]
you where actually pretty close:
 ``await Employee.filter(occupation='developer').update(salary=5000)``
will do that

**Comment by mojimi** [comment]
Thank you, totally missed that in the docs

**Comment by grigi** [comment]
Tried to make docs clearer re `.update()` usage.
