### ISSUE TITLE
Model Signals

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#273]
Does tortoise saves the old values before a save? So I can compare what has been changed.

The context here is I'm trying to create a "application trigger" module, for example :

```python
#When a task is done, all its child tasks should be automatically done too
@Task.bind('after-save')
async def update_child_tasks(self, old_values):
  if old_values.status != self.status:
    if self.status == 'done'
      await Task.filter(mother_task=self).update(status='done')
```
This is only a small example, there are many other cases where I need triggers like this

Hope it is understood what I'm trying to do, emphasis on trying, I'm accepting ideas on different ways to approach this.

Also it wouldn't work on batch QuerySet methods, like update or batch_create, if anyone has any idea on how to overcome this that'd be great

**Comment by grigi** [comment]
Right now tortoise doesn't keep the old values unfortunately.

For batch update/delete you get a counter of how many records got affected, so if that is >0 something happened. But we don't know what the old value was.

Do you want a global trigger?

**Comment by mojimi** [comment]
@grigi Can I somehow get the IDs of the affected records after a batch operation? That'd solve it.

I'm not sure what you mean by global trigger, I'm just trying to come up with a system similar do Django signals, or any sort of before/after bindings. 

I've managed to do it, but it won't work on batch operations yet

**Comment by grigi** [comment]
@mojimi Unfortunately not.
SQLite reports the no of lines filtered, has no syntax to return other data during an update.
MySQL reports the no of lines updated, has no syntax to return other data during an update.
Postgres eports the no of lines filtered(not updated), and has syntax to return data.

In none of the cases we get the right data (or any data).

The best would be to run two queries in a transaction:
- Filter by parameters to `.filter()` and by NOT parameters to `.update()` → This should get you the object that is going to change in the next query
- Do the update

And depending on the database and the configured isolation level, would possibly raise an exception if any race gets detected.
So the data would be pretty close to trustworthy, but not guaranteed 100% trustworthy.


Django's signals is more-or-less what I was talking about :+1:

**Comment by mojimi** [comment]
I guess for getting "old values" I could just re-query the object and compare changes, that would even be more accurate.

I don't know how PR works and my code is probably not standardized enough to be merged, but I can share what I came up with if that's useful

**Comment by grigi** [comment]
Thank you, it would be useful to even drop it here in the comments :smile:

**Comment by long2ice** [comment]
hey,I try to implement model signals in my own thought:
```python
class BaseModel(Model):
    create_at = fields.DatetimeField(auto_now_add=True)
    update_at = fields.DatetimeField(auto_now=True)

    _pre_save_listeners: Dict[Type[MODEL], List[Callable]] = {}
    _post_save_listeners: Dict[Type[MODEL], List[Callable]] = {}

    class Meta:
        abstract = True

    @classmethod
    def register_listener(cls, listener_type: ListenerType, listener: Callable):
        assert callable(listener), 'listener must be callable!'
        listeners_collect = getattr(BaseModel, f'_{listener_type}_listeners')  # type:dict
        if listener not in listeners_collect:
            listeners_collect.setdefault(cls, []).append(listener)

    async def save(
            self,
            using_db: Optional[BaseDBAsyncClient] = None,
            update_fields: Optional[List[str]] = None,
    ) -> None:
        await self._pre_save(using_db, update_fields)
        await super(BaseModel, self).save(using_db, update_fields)
        await self._post_save(using_db, update_fields)

    async def _pre_save(self, using_db, update_fields):
        for listener in self._pre_save_listeners.get(self.__class__, []):
            await listener(self.__class__, self, not self._saved_in_db, using_db, update_fields)

    async def _post_save(self, using_db, update_fields):
        for listener in self._post_save_listeners.get(self.__class__, []):
            await listener(self.__class__, self, not self._saved_in_db, using_db, update_fields)
```
``signals.py``:

```python
from typing import Type
from tortoise.models import MODEL
from . import ListenerType


def post_save(sender: Type[MODEL]):
    def decorator(f):
        sender.register_listener(ListenerType.post_save, f)
        return f

    return decorator


def pre_save(sender: Type[MODEL]):
    def decorator(f):
        sender.register_listener(ListenerType.pre_save, f)
        return f

    return decorator
```

``listeners.py``
```python
from db.signals import post_save
from db import models


@post_save(models.User)
async def user_save(sender, instance: models.User, created: bool, using_db, update_fields):
    print(sender)
    print(instance)
    print(created)
    print(using_db)
    print(update_fields)


@post_save(models.App)
async def app_save(sender, instance: models.User, created: bool, using_db, update_fields):
    print(sender)
    print(instance)
    print(created)
    print(using_db)
    print(update_fields)
```

now it worked,hope to give a review and some suggestions! @grigi 
then I can try a pull request if you agreed.

**Comment by long2ice** [comment]
maybe should be unify ``model.save`` and ``model.create`` behavior with same ``save_base``.

**Comment by grigi** [comment]
Thanks for this. Could we come up with a list of signals that would be useful? A minimal list would be great.

Eg:
* model create
* model update
* model delete

Do we need pre/post variations?
What do we do about bulk operations? We typically only know how many objects was affected, not which ones.

Do we want signals on a per model granularity or global or both? Why?

Init signals? Cleanup signals?

Let's pin down exactly the minimum viable set, so we have a clean spec to implement.
Also, what level of performance impact is acceptable? I'd prefer no impact if not used.

**Comment by long2ice** [comment]
my thought,mostly inspired by django:
1. ``pre_save``,``post_save``,both include create and update,``pre_delete``,``post_delete``.
2. pre/post variations is unnecessary.
3. bulk operations not support.
4. only need per model,not global.
5. cleanup signals can be support.

this is the early commit.[https://github.com/long2ice/tortoise-orm/commit/0605c3e97a2713ee06ccdbd7ca4f1984aa9aee88](https://github.com/long2ice/tortoise-orm/commit/0605c3e97a2713ee06ccdbd7ca4f1984aa9aee88),maybe imperfect and lack of consideration.

**Comment by grigi** [comment]
In step one you list pre/post, then you say unnecessary? Could you clarify?

**Comment by long2ice** [comment]
I mean we don't need know difference before save and after save,just add a signal before save and after save,then write listeners to catch the signal.maybe I misunderstand,sorry to my poor english.

**Comment by grigi** [comment]
Oh, that was not my question. Why do we need BOTH a before-save and after-save? I don't see the need? Just after-save, and before-delete?

**Comment by long2ice** [comment]
maybe we should check something or logging something or do someother before save,delete and after save,delete,depend on the coder, reserve a signals maybe flexible.

**Comment by mojimi** [comment]
> 
> 
> Oh, that was not my question. Why do we need BOTH a before-save and after-save? I don't see the need? Just after-save, and before-delete?
> 
> Don't worry, English is not my first language either, it's fine for there to be misunderstandings :-)
> Which is why we are having a conversation.

In my code, I use before saves to enforce business rules, but for that I had to change the code so that I can see what has been changed.

I mean, if there are uses for it in SQL there will be here too.

But, at least in my case, without the ability to check before/after (which fields have changed) it wouldn't be too useful.

**Comment by grigi** [comment]
Ok, so there is a concrete cases for:
* pre_save (only for updates? or for creates too?)
* post_save
* pre_delete

Still uncertain on:
* post_delete (It's already gone?)

And then generic signals, like (out of scope for now, but can be useful for plugins to manage init/teardown properly):
* setup_models_loaded (relationships have been build and models considered complete)
* setup_db (possibly both a pre/post connection)
* cleanup_db (possibly both a pre/post disconnection)

**Comment by grigi** [comment]
@long2ice Just checking up, are you still working on Model Signals?

**Comment by long2ice** [comment]
Yeah,complete before in my own branch,https://github.com/long2ice/tortoise-orm/commit/4aaa6dd0c28bf7244e093ccf03f4af8dac81ced2, but I'm not sure is it appropriate to commit to master,could you give a look?
