### ISSUE TITLE
How to use lock, like "for update" in mysql

### ISSUE THREAD

**Issue by xiaoqiu206** [tortoise/tortoise-orm#280]
use this orm ,how to use lock, like mysql "for update"?

**Comment by abondar** [comment]
Hi!

Sadly, currently Tortoise doesn't provide syntax for `for update` queries.
Even though it would be nice to have such feature, I think right now development is focused on other things around stable release and I wouldn't expect that it will be implemented soon.

As a workaround, for now you can start transaction and get transaction wrapper and call your queries directly over it.
I think something like that could work:

```
from tortoise.transactions import in_transaction

async with in_transaction() as tr:
    _, raw_result = await tr.execute_query("SELECT something FROM somewhere for update")
```

**Comment by long2ice** [comment]
Look https://github.com/tortoise/tortoise-orm/pull/483
