### ISSUE TITLE
New related field code in 0.15.9 requires PyPika >= 0.35.18

### ISSUE THREAD

**Issue by davidpurser** [tortoise/tortoise-orm#282]
The use of 'get_table_name' in the new related field join code requires PyPika >= 0.35.18, as this function was not available in PyPika prior to 0.35.18.  However, the Tortoise ORM requirements.txt only specifies >= 0.35.8, so some queries fail to execute unless PyPika is manually upgraded.  The Tortoise ORM requirements.txt should be updated to reflect >=0.35.18.

**Comment by grigi** [comment]
Indeed, it seems you are right. Thank you for pointing this out. I'm going to do a dep upgrade for any downstream that has a useful feature/fix in the next release.

**Comment by grigi** [comment]
I released a version with just this fixes. I have been struggling to get time to work on the other issues. And this fix, whilst super simple, can easily trip people up.
Thank you for debugging this :+1:
