### ISSUE TITLE
Aggregate functions

### ISSUE THREAD

**Issue by abondar** [tortoise/tortoise-orm#3]

**Comment by grigi** [comment]
@abondar We already have some aggregate functionality. Could you at least update this with a checklist of what you consider a "basically good" set of aggregation functionality, and then vet if we have it or not?

**Comment by abondar** [comment]
I think we can close this issue, cause it was created when there wasn't any kind of aggregation at all. Now we have some basic functions, so any more advanced aggregation could be requested and created through other issues
