### ISSUE TITLE
Fix confused context or remove py3.6

### ISSUE THREAD

**Issue by grigi** [tortoise/tortoise-orm#303]
Py3.6 suffers from a confused context, in part due to backported contextvars not keeping perfect track of state for asyncio event loop.

Either fix it
Or work-around the issue (e.g. disable pooling for py3.6)
Or remove support for it.

**Comment by abondar** [comment]
I think dropping pooling for 3.6 is fine.

I would even say that dropping 3.6 at all is fine too, because I don't think we have that much users that use Tortoise and can't upgrade python version

**Comment by grigi** [comment]
Well, if we drop support entierely for py3.6, we would have to drop pypy too, as they don't have a py3.7 version out yet.
In fact, if they come out with a py3.7 version I'd almost immediately drop py3.6 support.

Still, I'm in conflict if its better to release a version that's slow on 3.6 or not at all.

**Comment by abondar** [comment]
Well, it's not like we are deleting all oldversions after dropping 3.6 :)

People who stick to pypy could use old versions, and we could get pypy back on board when it will release 3.7 version

Releasing slow version for 3.6 imo worth it only if doesn't require additional work

**Comment by grigi** [comment]
I have been busy with it for half a day so far, and it doesn't realy work reliably. It gets confused between inner/outer transactions still. It only works with SQLite because it uses a mutex.

I'm beginning to think that the amount of work requires is a bit tooo big at this stage. Also Py3.6 had a `DeprecationWarning` since 24 Nov 2019. Is 3 months notice enough?

**Comment by AEnterprise** [comment]
honestly if it is indeed that unreliable and hard to keep it working it might be best to drop 3.6?

i'd say it's probably enough time, and it will save people more headaches then letting them run it on 3.6 and crash things because python gets confused

**Comment by grigi** [comment]
pypy3.7 is mostly there: The ci test failures are a small fraction of the testsuite at this stage: http://buildbot.pypy.org/summary?branch=py3.7

Knowing them, it could be released in a week or half a year. They always surprise me with timelines. :man_shrugging: 

I'm tending towards dropping 3.6 at this stage. But to make it worthwhile, we need some great features as a counterpoint. So I'll ensure that bugfixes go into the 0.15 series for a while, and then feature work going forwards with 0.16 series.

**Comment by grigi** [comment]
After consideration and discussion, I will remove py3.6 from support. We will keep on releasing 0.15 with backported bugfixes for a while still. 
Basically by the time 0.16 comes out without Py3.6 support it will have been about 4 months since py3.6 got marked as deprecated.

**Comment by PatTheMav** [comment]
@grigi I'm sorry to pick this up after the issue has been closed, but as I'm running my projects with PyPy it's great to read that it's not forgotten.

So for now installing tortoise via `tortoise-orm<0.16` is the way to go for PyPy? I've written a backend based on `aiopg` and `psycopg2cffi`, so from what I can see I'd need to remove the PyPy guard in the available tests to check if it works as expected.
