### ISSUE TITLE
Is there any solution for filter in Aggregate function?

### ISSUE THREAD

**Issue by pjongy** [tortoise/tortoise-orm#309]
**Is your feature request related to a problem? Please describe.**
In my project, I need filter while using Count function like this
(It is an example code that is not really in project code):
``` python
User.first()
.preferch_ralated(
    'post'
)
.annotate(
    post_count=Count('post')  # We need to filter post.status is NORMAL
)
```

In my mind, It can be achieved with SQL(pseudo):
``` sql
SELECT COUNT(CASE WHEN post.status = 0 THEN post.id ELSE null END)
FROM user
INNER JOIN post ON post.user_id = user.id
```
and pypika:
``` python
Count(
    Case().when(board.status == NORMAL, board.id).else_(None)
)
```

django.db.models has filter argument in Aggregate for filtering while SQL function runs
(https://github.com/django/django/blob/828e3b1335e2614d338a630fd5b5f88d38a6b5d2/django/db/models/aggregates.py#L16)

And usage in django:
(https://docs.djangoproject.com/en/2.2/ref/models/conditional-expressions/#conditional-aggregation)
``` python
>>> Client.objects.aggregate(
...     regular=Count('pk', filter=Q(account_type=Client.REGULAR)),
...     gold=Count('pk', filter=Q(account_type=Client.GOLD)),
...     platinum=Count('pk', filter=Q(account_type=Client.PLATINUM)),
... )
```

**Describe the solution you'd like**
I think functions.Aggregate can recieve parameter 'filter' like this:
``` python
class Aggregate(Function):
    database_func = AggregateFunction
    def __init__(self, field, _filter: Q=None, *default_values) -> None:
        self.field = field
        self.field_object: Any = None
        self.default_values = default_values
        self.filter = _filter
    ...
```

and I expect enhanced sql function usage is:
``` python
User.first()
.preferch_ralated(
    'post'
)
.annotate(
    post_count=Count('post', _filter=Q(status=NORMAL)) 
)
```

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by grigi** [comment]
The proposed API does make sense. Right now we don't have anything like that, unfortunately.

@lntuition Could you look at this together with #257 or should we do this completely separately?

**Comment by lntuition** [comment]
I think it is different with #257. As is we can't do like above action in tortoise atomically. Current work around it use `filter` with `annotate` multiple times. (but it is also too inefficient).

After doing #257, I should check this, too.

**Comment by lntuition** [comment]
I'm working on this issue. I found that some method need some change to support this feature. I will make some minor patch first. 

I'm not sure that i can support this feature. hmm.. needs time !
