### ISSUE TITLE
Should we consider ODBC?

### ISSUE THREAD

**Issue by grigi** [tortoise/tortoise-orm#31]
ODBC is a bit of a crap shoot. It can sometimes help in a pinch, though.

We should formalise our stance on ODBC.
e.g.
1) We support ODBC through `aioodbc` and support the basic features for ODBC driver for a select set of DBs only.
2) Like 1) but ODBC is marked as best-effort-only
3) We decide that we don't want ODBC as part of the primary project.

ODBC is the only way from the asyncio python world to connect to the Microsoft/Oracle databases, and to  Warehousing databases (such as Vertica/Teradata/IQ).
For the first set I could see that someone might want to use a Python ORM over MS-SQL, but the latter cases, for warehouse db's... They likely don't want to be used like a relational database, so an ORM doesn't make sense.

**Comment by Zeliboba5** [comment]
I think we should give this decision to community itself.
I will write guide to implementing new backends after we will push it to release.
So if there will be anyone who will want to use tortoise for ODBC he will just implement backend using that guide. 
Currently I don't think there is much users who struggle for ODBC asyncio ORM :)

**Comment by grigi** [comment]
:+1:

**Comment by reedjosh** [comment]
Hey, I've been looking for a way to do Oracle async in an ORM. Any chance this would be implementable with this project? I'd be happy to work on it with guidance.

For background: we're building out a GraphQL api, and we want to use an ORM to fullfill the object mapping. SQLAlchemy actually does a great job, but it's incompatible w/async. We have both PostGres and Oracle DBs. Oracle is legacy, but must be supported for the foreseeable future.

Thanks!

**Comment by grigi** [comment]
Well, that is enough reason to reopen this.

The issue with Oracle is how do I do CI against it? Don't I need a license for installation?
Ah, I see this exists: https://www.oracle.com/database/technologies/appdev/xe.html Would that be an OK target to test against?

Unfortunately adding support for extra DB's at this stage is relatively low, although it shouldn't be too difficult.

**Comment by reedjosh** [comment]
I will download and connect to the Oracle Express Edition you've linked, and will let you know if I have any reservations. AFAIK, that should be fine.

Further, I will try to do some more reading on adding a backend and or I will read through the codebase a bit, but could you point me toward which modules/files to look into first?

**Comment by reedjosh** [comment]
Actually, I seen now it's simply backend/client, executor, schema generator. I suppose I'll pull and attempt connecting to the XE be. Thanks! : )

**Comment by grigi** [comment]
Also take a look at fields/data.py
Each of the fields can have overrides for SQL types, or sometimes emulation.
The autonumber integers would probably need additions, as every db does autonumbers differently.

**Comment by mojimi** [comment]
I like ODBC simply because it the closest to SQL Server support

**Comment by long2ice** [comment]
Supported
