### ISSUE TITLE
Function with source_field fields does not work well

### ISSUE THREAD

**Issue by lntuition** [tortoise/tortoise-orm#310]
```python
class TestFields(Model):
    ch = fields.CharField(max_length=100, source_field='source_ch')

async def run():
    await TestFields.create(ch="Apple")
    await TestFields.create(ch="Apple   ")
    values = await TestFields.annotate(a=Trim("ch"), b=Length("ch")).values("a", "b")
    print(values)
```

**To-be**
```console
[{'a': 'Apple', 'b': 5}, {'a': 'Apple', 'b': 8}]
```

**As-is**
``` console
[{'a': 'ch', 'b': 2}, {'a': 'ch', 'b': 2}]
```

Also, It only works at sqlite. postgresql looks like treating generated query as an error.

**Comment by lntuition** [comment]
Also I think this is looks messy bug. I will make patch to hotfix this with below workaround
```diff
--- a/tortoise/functions.py
+++ b/tortoise/functions.py
@@ -59,7 +59,11 @@ class Function:
                 function_joins.append(join)
                 field = related_field_meta.basetable[related_field_meta.db_pk_field]
             else:
-                field = table[field_split[0]]
+                field = model._meta.fields_map.get(field_split[0])
+                if field.source_field:
+                    field = table[field.source_field]
+                else:
+                    field = table[field_split[0]]
                 if self.populate_field_object:
                     self.field_object = model._meta.fields_map.get(field_split[0], None)
                     if self.field_object:  # pragma: nobranch
```

**Comment by lntuition** [comment]
However, I think this type of bug can exist anywhere that creates query (also current workaround looks not beautiful) I think we should look all query generating code and may refactor that?.. Maybe It could be a little difficult :worried: 

How about your thinking? @grigi

**Comment by grigi** [comment]
Woah, that's a bad one. I know to root this out with regular fields I did the whole `StraightFields`/`SourceFields` tests. Basically I have 2 models that are supposed to be identical from the Tortoise model interface, but the one has translation to the DB.

We may have to extend that with a lot more test cases?

**Comment by grigi** [comment]
We still need to identify anything that works with pypika objects directly, (I don't think `Table`, but the others) and do a straight/source test on all of them.
