### ISSUE TITLE
pydantic documentation suggestions

### ISSUE THREAD

**Issue by AEnterprise** [tortoise/tortoise-orm#314]
In general the documentation looks pretty good but after using it for the last weeks i do have some remarks i feel like might need to be included in the documentation:

- that you can chose to await or not, if you await it will fetch all foreign key objects (recursively). While this in many cases might be the intended behavior. it should def be mentioned that it will do this and that you need to blacklist the fields to not have this happen. also that not awaiting it at all will prevent this behavior (albeit with an error if not blacklisted). yes it's listed in the function at the bottom. but most people will never look at this and go by the examples.

- in the 2nd tutorial ``print(Tournament_Pydantic_List  .schema())`` has some extra spacing. just looks funky

- it references "regular Pydantic-object methods", probably worth adding a link back to the pydantic documentation here (https://pydantic-docs.helpmanual.io/usage/exporting_models/) for people who are not super familiar with pydantic or encountering it here for the first time

- the early init tutorial is saying "uhow where is our relationship" but is about early init but none of the tutorials ever explicitly connect to any database since they are partial code snippets. i think it might be worth being explicit here and mentioning that you only need to do an early init if you need to create these models before you awaited the tortoise init

overall great docs, just some things to consider to make things more explicit and help new people find their way easier

**Comment by grigi** [comment]
Thank you. All points are good points :smile:

**Comment by grigi** [comment]
>     * that you can chose to await or not, if you await it will fetch all foreign key objects (recursively). While this in many cases might be the intended behavior. it should def be mentioned that it will do this and that you need to blacklist the fields to not have this happen. also that not awaiting it at all will prevent this behavior (albeit with an error if not blacklisted). yes it's listed in the function at the bottom. but most people will never look at this and go by the examples.

Yes, this probably needs to be made clear, the caveats come in with relationships. Possibly a topic large enough for it's own tutorial topic?

>     * in the 2nd tutorial `print(Tournament_Pydantic_List  .schema())` has some extra spacing. just looks funky

Done
 
>     * it references "regular Pydantic-object methods", probably worth adding a link back to the pydantic documentation here (https://pydantic-docs.helpmanual.io/usage/exporting_models/) for people who are not super familiar with pydantic or encountering it here for the first time

Added links to pydantic model definition and model usage into the tutorials.

>     * the early init tutorial is saying "uhow where is our relationship" but is about early init but none of the tutorials ever explicitly connect to any database since they are partial code snippets. i think it might be worth being explicit here and mentioning that you only need to do an early init if you need to create these models before you awaited the tortoise init

In fact the tutorials are available as a full code examples: https://tortoise-orm.readthedocs.io/en/develop/examples/pydantic.html#relations-early-init but obviously this isn't clear enough, so I'll add deep-links at the beginning of each tutorial to it's sample. (I build an example that demonstrates something and the make it into a tutorial)

Yes, I'll be more explicit as to when early init is needed.

**Comment by grigi** [comment]
@AEnterprise I applied our suggestions, but opted to not do a separate tutorial for from_orm. Please review the docs: https://tortoise-orm.readthedocs.io/en/develop/contrib/pydantic.html to see if its better now?

**Comment by AEnterprise** [comment]
looks a lot better as a starting point for new people. i might try my hand at some more examples later, though i guess those would be better suited later for a more general fastapi integration tutorial

**Comment by grigi** [comment]
We probably need tutorials of similar quality for Tortoise ORM itself...
