### ISSUE TITLE
How can I specify a time zone

### ISSUE THREAD

**Issue by Erbeter** [tortoise/tortoise-orm#335]
await Tortoise.init(db_url="mysql://root:123456@127.0.0.1:3306/example",
                        modules={'models': ['models']}
                        )

**Comment by grigi** [comment]
Ah... Somehow we haven't gotten to timezone-aware datetimes :-(

I can't find the ticket now, so I'm leaving this as the issue to work towards.

There was an abandoned attempt #103 but it appeared to have beem forgotten. Thank you for bringing it up again. This is important.

**Comment by mookrs** [comment]
@long2ice I think this PR brings breaking change. If I use old config which has no `timezone` info, after executing `Tortoise.init()`, time in my program becomes confused. Here is my logs:

```
2020-11-21 13:25:45.098 | INFO     | uvicorn.main:serve:405 - Started server process [19978]
2020-11-21 13:25:45.098 | INFO     | uvicorn.lifespan.on:startup:22 - Waiting for application startup.
2020-11-21 05:25:47.902 | INFO     | app.core.events:connect_db:32 - Tortoise-ORM startup, connections: {'db1': <tortoise.backends.mysql.client.MySQLClient object at 0x10f8cac10>, 'db2': <tortoise.backends.mysql.client.MySQLClient object at 0x110946550>}
2020-11-21 05:25:47.904 | INFO     | uvicorn.lifespan.on:startup:34 - Application startup complete.
2020-11-21 05:25:47.906 | INFO     | uvicorn.main:startup:492 - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

As above, setting `TZ` environment variable also affects other functions in my program.

**Comment by long2ice** [comment]
Yes, so changelog said that, be careful to upgrade.

**Comment by mookrs** [comment]
I tend to this is a breaking change, maybe 0.17.0 version number will be more suitable. And the worst part is if I don't specified `timezone`, the default `TZ` environment variable also affects whole program, not only Tortoise ORM...

**Comment by long2ice** [comment]
You are right, maybe default UTC timezone setted is not suitable, so in version 0.16.18 you can specify your local timezone to resolve that.

**Comment by mookrs** [comment]
OK, I have pin 0.16.17 to resolve the problem. To be more clear, here is the situation we are facing. Look forward to getting a better solution:

```python
❯ python
Python 3.8.2 (default, May 13 2020, 11:47:24)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from datetime import datetime
>>> datetime.now()
datetime.datetime(2020, 11, 21, 14, 14, 50, 253867)
>>> os.environ['TZ'] = 'UTC'
>>> datetime.now()
datetime.datetime(2020, 11, 21, 6, 14, 58, 217979)
```

**Comment by long2ice** [comment]
Read the complete docs maybe helpful, https://tortoise-orm.readthedocs.io/en/latest/timezone.html

**Comment by mookrs** [comment]
I said "here is the situation **we** are facing" means "you and me and Tortoise ORM"... I have already read manual and source code, fixed my case before I commenting this issue, thanks for your reminding. 😄

So... The problem is not I don't know how to use new params `use_tz` and `timezone`, the problem is this PR made Tortoise ORM always set `TZ` environment variable and I think this is **implicit** behavior.

If I have time, I maybe commit a PR to fix this behavior. (But I think I have no time... 🤣)

**Comment by long2ice** [comment]
Yes, set `TZ` globally is not good, I noticed that and updated it to `TIMEZONE` already, thanks!

**Comment by mookrs** [comment]
Appreciate it!

**Comment by Tayum** [comment]
@long2ice @mookrs sorry, any possibility I can get back to same behavior in `0.16.18` as in `0.16.17`?
Even with `use_tz` set to `False`, I get `tzinfo=<UTC>` in my datetime fields in tests (using SQLite).

See example:
```python3
import datetime

from tortoise import fields, models


class DatetimeModel(models.Model):
    id = fields.IntField(pk=True, null=False)
    created_at = fields.DatetimeField(null=True)

await DatetimeModel.create(created_at=datetime.datetime.utcnow())

created = await DatetimeModel.get(id=1)

assert created.tzinfo is None  # Good on 0.16.17, fails on 0.16.18
```

---

Tried `Tortoise.init(timestamp=None)`, but that leads to exceptions.

**PS: +1** to that it should be at least `0.17`, not `0.16.18`.

**Comment by long2ice** [comment]
try set `timezone` with your local timezone, default is `UTC`

**Comment by Tayum** [comment]
@long2ice sorry, maybe I've misunderstood you...

But I don't need the timezone there at all, I want the returned datetimes to be timezone-naive :thinking:

I want the default timezone to be absent at all, e.g. `assert created.tzinfo  is None`.
I don't want it to be my local timezone.

But `Tortoise.init(timestamp=None)` doesn't work.
