### ISSUE TITLE
How can I query any field

### ISSUE THREAD

**Issue by Erbeter** [tortoise/tortoise-orm#338]
`class Quota(BaseModel, TimestampMixin):
    memory = fields.BigIntField()
    cpu = fields.FloatField()
    disk = fields.BigIntField()

async def query(cls, key, value, gt=None, lt=None, start=0, limit=None):
    query_set = cls.all()
    if not key:
        return query_set
    col_name = cls._meta.fields_map.get(key)
    print(dir(col_name))
    if not col_name:
        raise AttributeDoesNotError(key)
    if value:
        query_set = query_set.filter(col_name.like(value))
    return query_set

`
i find Field no attribute like，How can I do it? Thank you very much

**Comment by grigi** [comment]
I don't understand what it is you are asking?

**Comment by Erbeter** [comment]
I entered the name of field，then  get the  field  of model through getattr,i want to query this field through  filter(),
`
fieldName=getattr(model,"i input")
Model.all().filter(fieldName=value)
`
My English is not very good. Do you understand？

**Comment by Erbeter** [comment]
I have solved this problem, but I have encountered a new problem. How get  number of queryset ? 
queryset can't use len()
`
        if value:
            query_set = query_set.filter(**{key: value})
        if lt:
            query_set = query_set.filter(**{f'{key}__lt': lt})
        if gt:
            query_set = query_set.filter(**{f'{key}__gt': gt})
`

**Comment by grigi** [comment]
Have you looked at Q expressions? It's pupose is to compose query fragments, and for programmatic use.

**Comment by grigi** [comment]
https://tortoise-orm.readthedocs.io/en/latest/query.html#q-objects
