### ISSUE TITLE
Explicit group by

### ISSUE THREAD

**Issue by mojimi** [tortoise/tortoise-orm#347]
Is it currently possible to do a explicit group by? I searched the docs but couldn't find anything about this.

The use I'm looking for is to get the count of each distinct value in a column, like the following query :

```sql
SELECT
  title,
  COUNT(status) AS `status_count`
FROM
  tasks
GROUP BY
  status
```

This would count the number of tasks of each status

**Comment by grigi** [comment]
No, we don't have explicit group by at this stage, what syntax do you propose?

Part of the problem with an explicit group by is that we can't guarantee to get models, as the data may be skewed. So it could only work with `.values()` or `.values_list()`.

```py
await Tasks.all().annotate(status_count=Count('status')).values('title', 'status_count').group_by('status')
```

I think  a syntax like that makes sense to me? Would that work fine for you with the limitations specified?

**Comment by mojimi** [comment]
> 
> 
> No, we don't have explicit group by at this stage, what syntax do you propose?
> 
> Part of the problem with an explicit group by is that we can't guarantee to get models, as the data may be skewed. So it could only work with `.values()` or `.values_list()`.
> 
> ```python
> await Tasks.all().annotate(status_count=Count('status')).values('title', 'status_count').group_by('status')
> ```
> 
> I think a syntax like that makes sense to me? Would that work fine for you with the limitations specified?

Well in my case it would definitely work just fine as I'm only looking for the count, but maybe its worth exploring more cases where this would be useful.

The syntax you proposed seems pretty good, is what I'd expect
