### ISSUE TITLE
Function thay can converse an instance of Model into dict

### ISSUE THREAD

**Issue by jdgjxxchy** [tortoise/tortoise-orm#348]
I read the doc carefully to find a function that can converse a Model instance into dict but failed.

For example:

`>>>user = User(name="peter")`
`>>>print(user.dict())`
`{`
`  "id": 1,`
`  "name": "peter"`
`}`

Forgive me if I miss something in the doc that can do this.

**Comment by abondar** [comment]
Hi! 

This could be helpful - https://tortoise-orm.readthedocs.io/en/latest/examples/pydantic.html

**Comment by jdgjxxchy** [comment]
@abondar Thank you for your answer.
So if I want to converse an instance into dict, I must learn Pydantic first.
I thought I could use sanic instead of FasiAPI to avoid learning Pydantic :(

**Comment by CoolSpring8** [comment]
I'm new to Tortoise-ORM and FastAPI too and had a similar question, but after reading the documentation again I came across "[values()](https://tortoise-orm.readthedocs.io/en/latest/query.html#tortoise.queryset.QuerySet.values)" on a QuerySet. Maybe that works?

I use it in my project like this, but I'm not sure if it's really the "correct" usage though.
`user_result = await User_DB.filter(username=username).first().values()
user_dict = user_result[0]
`

Now the `user_dict` is:
`{'id': 2, 'username': 'admin', 'hashed_password': 'somehashedcontent'}`

**Comment by grigi** [comment]
values() is pretty optimal if it works for you.
It bypasses the Object layer, and will perform well.
The earlier Pydantic suggestion is for a proper controllable serialisation, it may be overkill for your use case.

values() is a fully supported method, so don't worry about it.

The issue with a todict method is what do we do with relations? And you very quickly end up with something as complex as just using Pydantic.
