### ISSUE TITLE
Initializer provided by contrib.test assumes app name is "models"

### ISSUE THREAD

**Issue by gdmoore** [tortoise/tortoise-orm#352]
`initializer` allows you to specify your modules (`List[str]`) but does not allow you to supply your app name; `app_label="models"` is passed to `getDBConfig(...)`.

This does not work if your models are configured for a different app name.

Initializer should take an additional `str` argument to allow specifying the app_label argument.

**Comment by grigi** [comment]
There is three solutions I can think of:
1. Add optional parameters to `initializer`
2. Add extra ENVVAR for app name.
3. Add a multi app&model ENVVAR

I feel that 1 & 2 or 1 & 3 would work best?

What is your choice(s)?

**Comment by gdmoore** [comment]
I would prefer 1 + 2 with separate environment variables. Aggregate envvars can be a pain to deal with in some environments.

**Comment by grigi** [comment]
Hi, release v0.16.7 is out with the changes for this:
* https://tortoise-orm.readthedocs.io/en/latest/contrib/unittest.html#tortoise.contrib.test.env_initializer
* https://tortoise-orm.readthedocs.io/en/latest/contrib/unittest.html#tortoise.contrib.test.initializer

Please confirm if this resolves your issue.

**Comment by gdmoore** [comment]
Looks good 👍
