### ISSUE TITLE
fastapi and tortoise, can not get model definitions

### ISSUE THREAD

**Issue by netinsideout** [tortoise/tortoise-orm#364]
**Describe the bug**
I have big api based on Django orm and i started rewriting it to tortoise-orm. First impressions were great.  After tortoise-orm introduced pydantic serialization support, i removed all old pydantic models and start using pydantic_model_creator.  I found strange bug with relations. They was not loaded. Field _events_ in Tournament will be missing in example 'Tournament has many Events'. I started to using `Tortoise.init_models` to early initialize model relations, but found another problem because my **fastapi** application can not load.  I start debugging and researching problem and found that something going wrong after calling Tortoise.init_models. If i do not call it i will not have any relations in objects, if i call it, application will fail to load. I start guessing that something wrong with my code in project and i created a simple project with models from tortoise example to check, this is my fault or bug in one of the library i am using. Today i have a simple project with following error:
```
File "/home/test/venv/lib/python3.8/site-packages/fastapi/applications.py", line 92, in openapi
    self.openapi_schema = get_openapi(
  File "/home/test/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 290, in get_openapi
    definitions = get_model_definitions(
  File "/home/test/venv/lib/python3.8/site-packages/fastapi/utils.py", line 83, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 455, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 491, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 185, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 412, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 665, in pydantic.schema.field_singleton_schema
KeyError: <class 'abc.Tournament'>
```
It also can be `KeyError: <class 'abc.Event'> ` or  `KeyError:  <class 'abc.Team'>`.  
I do not understand everything, because 3 projects involved to this issue. **I guess, tortoise-orm have the problem with relation serialization, when using pydantic_model_creator after call Tortoise.init_models** I do not have any error related to fastapi or pydantic, when i manually create pydantic validation object and manually fetch needed relations to feet pydantic object. 
May be my project structure was wrong? 

**Steps To Reproduce**
Install fastapi, pydantic and tortoise-orm
Unpack project [test.zip](https://github.com/tortoise/tortoise-orm/files/4527921/test.zip)
Run run.py to create objects in sqlite db
Start uvicorn or gunicorn
Try to access fastapi with your_fastapi_url/docs
Error will be
Than try to comment Tortoise.init_models in models.py and restart application.
Push try out button in fastapi docs.
Enter 1 in id field
Hit execute.

Object without relation will be fetched

And another trick:
Uncomment Tortoise.init_models in models.py 
Delete or comment all fastapi methods except get_tournament
Run application.
Push try out button in fastapi docs.
Enter 1 in pk field
Hit execute.
Object with relation will be fetched.
Very strange behaviour... Huh :(

**Expected behavior**
Application must run and relations must fetch

**Additional context**
Versions
fastapi           0.54.1
pydantic          1.5.1
tortoise-orm      0.16.8
Python     3.8.1

**Comment by grigi** [comment]
Hi, it seems you were thorough enough in testing this.
I had a quick look, and it SEEMS like it should work fine. I wonder if it is some kind of import order confusion?
I will look at this is more detail the weekend.

Thanks for logging this :+1:

**Comment by tba91** [comment]
I've facing related issue. When I startup the fastapi app, for some reason the startup events (fastapi), doesn't run before the app itself. After all, the pydantic doesn't make relations because it's loaded before the generate schemas.

**Comment by grigi** [comment]
Ok, I managed to repeat the same errors.
I actually think this is to do with the mentioned `Enforcing globally unique model names` in https://github.com/tortoise/tortoise-orm/issues/315#issuecomment-599260643

as if I print out the schemas piece by piece, it works.

**Comment by grigi** [comment]
Yup, if I force names to be globally unique, it works, just now we end up with 4x of every type. Inspecting them, it seems to be more like 2x that is needed, so I'll try and dedup it a bit.

**Comment by grigi** [comment]
So on latest develop should be a fix for the non unique identifier for models (which confuses Pydantic).

Your example exposes a bug when using the O2O relation id as the Primary Key, which I will address in a later commit.
(On your test: `GET /address/?id=2` once you fix the search criteria to be `Address.get(event_id=id)`)
This appears to be prefetcher related...

Still the more edge cases we can add to the test suite the better :grin:

**Comment by grigi** [comment]
Hi, I released 0.16.9 and it should have the changed & fixes to resolve the issues.

Could you please test and confirm?

**Comment by netinsideout** [comment]
Yeah. Works fine now. Thanks for fix.

**Comment by Gaut9a8m** [comment]
I am not able to get foreign key fields value. 
Here is my model 

class BookingSlots(models.Model):
    id = fields.IntField(pk=True)
    is_active = fields.BooleanField(default=True)
    start_time = fields.DatetimeField()
    end_time = fields.DatetimeField()
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)
    
    user  = fields.ForeignKeyField('models.User', related_name='booking_slots_user')
    conference_room  = fields.ForeignKeyField('models.ConferenceRoom', related_name='booking_slots_room')


    def __str__(self):
        return f'{self.conference_room.name} - {self.start_time} - {self.end_time} - {self.user.name}'

BookingSlots_Pydantic = pydantic_model_creator(BookingSlots,name="BookingSlots", include=['id', 'conference_room', 'user', 'start_time', 'end_time','created_at','updated_at'])
BookingSlotsIn_Pydantic = pydantic_model_creator(BookingSlots,name="BookingSlotsIn", exclude_readonly=True)

User and conference_room is a FK relation. 



@router.post("/add/")
async def create_slot(slot: BookingSlotsIn_Pydantic, user_id:UserB_Pydantic, conference_room_id:ConferenceRoomB_Pydantic):
    try:
        user_obj = await User.get(id=user_id.dict()['id'])
        conf_obj = await ConferenceRoom.get(id=conference_room_id.dict()['id'])
        
        if not user_obj:
            raise Exception('User does not exists')
        if not conf_obj:
            raise Exception('Conference room does not exists')

        from_date = slot.dict()['start_time']
        to = slot.dict()['end_time']
    
        if from_date > to:
            raise Exception('Start time should be less than end time')
    
        slots = await BookingSlots.filter(start_time__range=(from_date,to), is_active=True, conference_room__vacant=True)
        print(BookingSlots_Pydantic.schema())
        if slots:
            raise Exception("Slot already exists")
        else:
            body = slot.dict(exclude_unset=True)
            slot = await BookingSlots.create(**body, user=user_obj, conference_room = conf_obj)
            return await BookingSlots_Pydantic.from_tortoise_orm(slot)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f'{e}')



UserB_Pydantic = pydantic_model_creator(User,name="UserB", include=['id'])
ConferenceRoomB_Pydantic = pydantic_model_creator(ConferenceRoom,name="ConferenceRoomB", include=['id'])


It will add record in db but in reponse on api it didn't show user_id, conference_id. 

Also While fetching all records. It didn't show user and conference room details aswell

@router.get("/")
async def get_all_slots():
    try:
        obj = BookingSlots.all()
        return {
            'msg':'success',
            'data':await BookingSlots_Pydantic.from_queryset(obj)
        }
    except Exception as e:
        raise HTTPException(status_code=404 ,detail=f"Slot data not found. {e}")

**Comment by stvnksslr** [comment]
Yeah running into this as well in the latest release, was working properly in the past but it seems like the `from_tortoise_orm` style methods dont detect FK relations in 19.0.

**Comment by gimebreak** [comment]
> Yeah running into this as well in the latest release, was working properly in the past but it seems like the `from_tortoise_orm` style methods dont detect FK relations in 19.0.

19.3 version seems too, how do you solve this?

**Comment by i701** [comment]
@aguywithnojob hey i noticed you are using a similar model to the fastapi intgeration example in the tortoise orm [documentation](https://tortoise.github.io/examples/fastapi.html#example-fastapi). I recently came across a bug where i could not expose any field with `DatetimeField` in the schema. i created an issue for that as well [here](https://github.com/tortoise/tortoise-orm/issues/1482)


Were you able to expose datetimefields in your example?
