### ISSUE TITLE
Filtering a database using __icontains fails for JSONB fields

### ISSUE THREAD

**Issue by odimko** [tortoise/tortoise-orm#365]
**Describe the bug**

In the previous version of the library (`tortoise-orm==0.16.4` namely), filtering of a database using `__icontains` on a JSONB field of a model would convert the field to `VARCHAR` and then search for the requested substring. However, for `tortoise-orm==0.16.8` that does not work and fails with an error:
```shell
function upper(jsonb) does not exist
HINT:  No function matches the given name and argument types.
You might need to add explicit type casts.
```

**To Reproduce**

The code to execute the query:
```python
phrases = ["a red apple", "a book", "the Sun", "a big store"]
query = Q()
for phrase in phrases:
    query = query & Q(poem__icontains=phrase)
    collection = collection.filter(query)
total_filtered = await collection.count()
```
where `collection` is a table that has the `poem` field, which in turn is of a JSONB type.
For `tortoise-orm==0.16.8` the raw query is (and it fails with the error above):
```sql
SELECT COUNT(*) FROM "collection" WHERE UPPER("phrases") LIKE UPPER(\'%a red apple%\') ESCAPE \'\\\
```

**Expected behavior**

```sql
SELECT COUNT(*) FROM "collection" WHERE UPPER(CAST("phrases" AS VARCHAR)) LIKE UPPER('%a red apple%')
```

**Additional context**

PostgreSQL is used for database handling.

**Comment by lntuition** [comment]
Ah, I found `CAST` was removed at 733eaf3. I think we should revert it. Thank you for your report !

**Comment by odimko** [comment]
> Ah, I found `CAST` was removed at [42adca3](https://github.com/tortoise/tortoise-orm/commit/42adca39dbfec65cd9d6cff9edb5c80651b3690d). I think we should revert it. Thank you for your report !

great, looking forward to the updated library :+1:

**Comment by grigi** [comment]
Hi, I released 0.16.9 and it should have the fix for this issue.

Could you please test and confirm?

**Comment by odimko** [comment]
yes, works great.
thank you both @lntuition and @grigi for the fast replies and action!

**Comment by yoann9344** [comment]
This leads to a problem. I have postgres field "CHAR" (not variable) on which I have an index "bpchar_pattern_ops". And by casting to "VARCHAR", postgres doesn't consider the index anymore.

It would be nice to revert this casting. I've not found any solution yet with the current state of tortoise !
