### ISSUE TITLE
TorToise exceptions cannot import name 'basestring' from pypika.terms

### ISSUE THREAD

**Issue by t1waz** [tortoise/tortoise-orm#373]
Describe the bug:

    Cannot import exceptions:
    from tortoise import exceptions - not working. 

    I using tortoise in my own serializer package, need to import this to handle IntegrityError when 
    serializer try to create data.

    few days before it works.

To Reproduce:

    just try to:
        from tortoise import exceptions

    It will raise ImportError: cannot import name 'basestring' from pypika.terms

Expected behavior:

    I can import exceptions, or any exception from tortoise.exceptions

Thanks guys
t1waz

**Comment by lntuition** [comment]
duplicate with #371 Plz look that issue
