### ISSUE TITLE
Cannot filter correctly with F expressions

### ISSUE THREAD

**Issue by moubctez** [tortoise/tortoise-orm#376]
**Describe the bug**
Sometimes it is necessary to compare two (or possibly more) fields of the same model in a query. Currently it is not possible with filtering and F expressions.

**To Reproduce**
Create a model with two fields of the same type, and select all rows from the database where these two fields are equal: `Model.filter(aaa=F('bbb'))`
The F expressions evaluates into a string of text, so an SQL query looks like this:
`SELECT "aaa","bbb" FROM "model" WHERE "aaa"=\'"bbb"\';`

**Expected behaviour**
SQL query should look like this:
`SELECT "aaa","bbb" FROM "model" WHERE "aaa"="bbb";`

**Comment by lntuition** [comment]
If i remember correctly, we didn't implement `F` expression with `filter` yet (I'm not sure that it is correct ) Also your suggestion is reasonable. I will check that point! Thank u :+1:
