### ISSUE TITLE
Add fields dynamically

### ISSUE THREAD

**Issue by netinsideout** [tortoise/tortoise-orm#382]
**Is your feature request related to a problem? Please describe.**
I want to add fields to models dynamically. This is related to model fields in my project that needed for translation. For example:
i have `content = fields.TextField()` and i want to add two fields for each language: 
`content_en = fields.TextField()`
`content_ru = fields.TextField()`
This is will work if i define all needed fields manually. 
I want to do this something like this:
```
def add_translation_fields(self):
      for field_name, field_type in self.translation_fields.items():
            for lang in self.languages:
                   self.magic_method_to_add_fields_dynamically("%s_%s" % (field_name, lang), field_type)
```
**Describe the solution you'd like**
In django orm i can add fields using `model.add_to_class()` method and `cls._meta.add_field()`.  We need something similar.  This is also will be great for other customizations and plugins to tortoise-orm.

**Comment by grigi** [comment]
Well... `cls._meta.add_field()` would work: https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/models.py#L233

It's not documented, but I don't think that interface is going to change.

Init order could be an issue. you would need to do it BEFORE you run tortoise.init().

**Comment by netinsideout** [comment]
Oh great. I will try to use is. Thank you.
