### ISSUE TITLE
Add exists method

### ISSUE THREAD

**Issue by Nenrikido** [tortoise/tortoise-orm#385]
**Describe the solution you'd like**
I'd like a `Table.exists(field=value)` method that would return `True` or `False`

**Describe alternatives you've considered**
For now the best alternative is `get_or_none` which can be useful with Python 3.8's walrus operator, but i feel like it's only a workaround.

**Comment by long2ice** [comment]
I think this is useful when we only want to know whether exists in db, rather than select real record and convent to python object. What do you think? @grigi

**Comment by grigi** [comment]
Sounds like a good requirement. :+1:
