### ISSUE TITLE
PK indexing

### ISSUE THREAD

**Issue by Nenrikido** [tortoise/tortoise-orm#386]
**Describe the solution you'd like**
PonyORM features a way to get specific records really fast via indexing : 
`Table[pk_val]` gives you directly the record corresponding to the pk value.
That is especially useful when you have meaningful primary keys (and not just auto-increments)
Here's one way to code it (can be better, not working because it indexes the metaclass) :
```py
@classmethod
def __getitem__(cls, key):
    return cls.get(**{cls.describe()["pk_field"]["name"]:key})
```

**Describe alternatives you've considered**
`Table.get` or initializing `Table` with kwargs ofc, but it's a bit too long to me, i feel like having pk indexing would be a nice add

**PS :**
It might be finer to go with the standard `Table` init, with your code structure, i did it that way, and this works, not just an idea :
```py
# noinspection PyArgumentList
def init(self, val=None, **kwargs):
    if val:
        return oldinit(self, **{self.describe()["pk_field"]["name"]: val})
    else:
        return oldinit(self, **kwargs)


oldinit = Model.__init__
Model.__init__ = init
```

**Comment by grigi** [comment]
It could be done a lot simpler. we have a property ``pk`` that already does this.
So:
```py
@classmethod
def __getitem__(cls, key):
    return cls.get(pk=key)  # We will have translate errors to IndexError
```

And you would use it like:
```py
office_desk = await Desks['office']
```

**Comment by grigi** [comment]
This should be part of the 0.16.11 release. Please test :smile:
