### ISSUE TITLE
Missing ids in query that bulk_create produces.

### ISSUE THREAD

**Issue by madnesspie** [tortoise/tortoise-orm#387]
**Describe the bug**
Hi! `Model.bulk_create` excludes object ids from query that it produces. This leads the ids to an ascending order, even if otherwise specified. 

**To Reproduce**
```python
# models.py
class SomeModel(models.Model):
    id = fields.IntField(pk=True)
   field = fields.IntField()

# test_bulk_create.py
import models

async def test_bulk_create_ids():
    await models.SomeModel.bulk_create(
        [
            models.SomeModel(id=100, field=1),
            models.SomeModel(id=200, field=1)
        ]
    )
    objs = await models.SomeModel.all()
    assert objs[0].id == 1
    assert objs[1].id == 2
```

**Expected behavior**
The bulk_create creates the ids according to objects that it gets.

**Comment by lntuition** [comment]
@madnesspie Thank you for reporting! I'll make PR to support with specified `pk`

**Comment by grigi** [comment]
Hold on. That was by design, even documented?
Bulk create is a create and forget system.

**Comment by grigi** [comment]
The point of bulk_create is to ensure that the models are in the DB in the fastest way possible for a specific use case: https://tortoise-orm.readthedocs.io/en/latest/models.html?highlight=bulk#tortoise.models.Model.bulk_create

If you fetch the objects later on again they will be correct.

But db-generated PK's are not fetched.

Part of this comes from difficulty in getting results back for a db-generated pk.
PostgreSQL has syntax to return a value, so we could possibly get it working right there with minimal overhead (I don't know if `execute_many` will return any data), but getting it working right with SQLite or MySQL may require not doing an `execute_many` as we only get the rowid as a property of the cursor. Which means we will have to issue it one at a time and then read. Which won't be any faster than doing a transaction with inserts.

We might be able to get it working performant for SQLite as only a single writer is allowed (for bulk create we ensure we get a write lock) so we could possibly make the assumption that the rowid is sequential. :thinking: 

MySQL may require an exclusive table lock for that assumption to work, which would impact performance.

So, we can support this, it will likely come at a performance penalty, so I think we should only do so if explicitly instructed.

Possibly we have two different bulk create methods?

**Comment by grigi** [comment]
Oh, hold on. I missed the issue here. Blame lack of sleep. Apologies.

**Comment by grigi** [comment]
This should be fixed in the next release. You can test by doing a
```
pip install https://github.com/tortoise/tortoise-orm/archive/develop.zip
``
