### ISSUE TITLE
Create multilevel of menu

### ISSUE THREAD

**Issue by Huad2** [tortoise/tortoise-orm#394]
I would like to create multilevel button menu like in this picture. However, I do not know how to create it.

![multilevelmenu](https://user-images.githubusercontent.com/65090515/81484425-87777700-926f-11ea-94b2-c0dc746d8630.png)

Could you please suggest how to do it. 
ps. I am using FM Pro 15.

**Comment by lntuition** [comment]
Wrong way. closed (Looks trolling)
