### ISSUE TITLE
Using of django models

### ISSUE THREAD

**Issue by imbolc** [tortoise/tortoise-orm#398]
I often use an async framework together with django to handle websockets, streaming etc. So aready having django models, it hurts to repeat them for tortoise. What do you think about an automatic inference the models from django's once? Even people who don't pare tortoise with django would benefit from the feature in terms of using django's migrations.

**Comment by grigi** [comment]
I don't think we can ever support such a case fully.
We can enable you but won't consider and behaviour differences as a bug.
That is because we share no code with Django.

However, due to the syntax being so close, we can do a best effort so it will be 95% the same.

Is that adequate?

**Comment by imbolc** [comment]
Sure, I believe it's fine until edge cases are described and people can clarify them. Something like this maybe?
```python
class Foo(Model):
   # redefining some fields to resolve uncertainties
   bar = BarField()

   class Meta:
       django_model = 'foo.models.DjangoFoo'
```

**Comment by grigi** [comment]
The big question is: How do I ensure that the model that uses `django.models.Model` as a base will be picked up by Tortoise?
You would have to either monkey patch it (yuck) or request that the developer does a conditional import or copy/pastes the model?

If copy/paste is involved, then we can deal with small differences?
It's basically changing `fields.DatetimeField` to `model.DateTimeField` etc..?

**Comment by imbolc** [comment]
A decorator maybe? Something like this:

```python
from contextlib import suppress

import django
import django.db.models as dj
from django.conf import settings
from tortoise import Tortoise, fields, run_async
from tortoise.models import Model

settings.configure(
    DATABASES={
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
)
django.setup()


class DjangoModel(dj.Model):
    foo = dj.CharField(max_length=64)

    class Meta:
        app_label = "foo"


FIELDS_MAP = {
    dj.CharField: lambda x: (x.name, fields.CharField(max_length=x.max_length))
}


def from_django(dj_model):
    def decorator(cls):
        attrs = {
            "__module__": "__main__",
        }
        for dj_field in dj_model._meta.get_fields():
            dj_field_cls = dj_field.__class__
            if dj_field_cls in FIELDS_MAP:
                name, field = FIELDS_MAP[dj_field_cls](dj_field)
                attrs[name] = field

        new_cls = type(cls.__name__, (Model,), attrs,)
        return new_cls

    return decorator


@from_django(DjangoModel)
class TortoiseModel:
    pass


async def main():
    await Tortoise.init(
        db_url="sqlite::memory:", modules={"models": ["__main__"]}
    )
    await Tortoise.generate_schemas()

    await TortoiseModel.create(foo="fooval")
    obj = await TortoiseModel.first()
    assert obj.foo == "fooval"


run_async(main())
```

**Comment by imbolc** [comment]
Maybe it's better to be a separate project though, as it may not require any tortoise api changes, but will rely on particular versions of django and tortoise. So there won't be a need to release a new version of tortoise following changes in django api. From other side django api is pretty stable, excluding probably approaching async features. What do you think?

**Comment by abondar** [comment]
Don't think it should be part of this this repository and it seems that it will be hard to implement, as Tortoise is not django compatible and we can't guarantee that it will work good in most cases.

Could be another project, but don't think it will be implemented here
