### ISSUE TITLE
Add tortoise-orm tags in Stackoverflow

### ISSUE THREAD

**Issue by anindyamanna** [tortoise/tortoise-orm#402]
I am not able to ask a question about tortoise-orm in Stackoverflow as the tag doesn't exist and I don't have enough reputation to create a new tag. If someone can add one, it would really help the community. Thanks!

**Comment by Nenrikido** [comment]
If you have an issue, i'd advice you to ask it on the gitter, you would be answered faster i think : https://gitter.im/tortoise/community

**Comment by Vishnu-priyan** [comment]
Even I thought of the same, we need a tag for tortoise-orm in SO. I have enough reputation to create a tag. Note tags without question will be deleted automatically by SO. So let me go ahead and ask few questions and answer it myself.

**Comment by Vishnu-priyan** [comment]
> I am not able to ask a question about tortoise-orm in Stackoverflow as the tag doesn't exist and I don't have enough reputation to create a new tag. If someone can add one, it would really help the community. Thanks!

Here are few questions i asked for the tag to exist.
https://stackoverflow.com/questions/61785318/how-to-init-db-for-tortoise-orm-in-sanic-app
https://stackoverflow.com/questions/61785379/how-to-run-simple-scripts-using-tortoise-orm

Please add your question as well, might try to answer yours.

**Comment by grigi** [comment]
Thats awesome @Vishnu-priyan 
Thank you.

**Comment by anindyamanna** [comment]
@Vishnu-priyan Thanks a lot for this. I had actually already asked this [here](https://github.com/tortoise/tortoise-orm/issues/401)

**Comment by abondar** [comment]
Thank you!
