### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by eugenyProchan** [tortoise/tortoise-orm#405]
I do not have enough experience to help with the development, although if you direct me to some simple things, I will take for it. I just wanted to say thanks to everyone who develops a tortoise. I am delighted with the documentation and functionality :)

**Comment by abondar** [comment]
Even though I am not really active in contributing right now, for me real delight is that Tortoise grown to be so much more than just side-kick instrument developed for some of my projects. 

So while we are here, @grigi and all the contributors - thank you so much for carrying this on and making Tortoise what it is right now. Hope I will be able to contribute once more in near future

**Comment by grigi** [comment]
Thanks for the message @eugenyProchan 
It's greatly appreciated :-)

@abondar You know, I didn't think my first issue #4 would end up here. And the journey is not yet done :grin: :tada:

**Comment by Vishnu-priyan** [comment]
My issue is #404 and I wish to end up at wherever you are for tortoise-orm someday same as you @grigi :) saw #4 looks nice.

**Comment by Vishnu-priyan** [comment]
Agreed @eugenyProchan tortoise-orm shows a lot of potential after. We should really make this the default go to (imo the best option) for an async orm in the near future.

**Comment by grigi** [comment]
@eugenyProchan I thoguht about what low-dev work we need.
Mostly issue triaging (as I am starting to fall behind) and documentation fixes.

But good ideas are also very useful. Some questions or bug-reports actually make a marked difference with the final product.

**Comment by eugenyProchan** [comment]
@grigi Ok, I will definitely report if I meet unexpected behavior. Maby I could find some small bugfix from issues. I think we can close this issue :)
