### ISSUE TITLE
Install on Linux without ciso8601

### ISSUE THREAD

**Issue by usernein** [tortoise/tortoise-orm#414]
Is there a way of installing on Linux without having ciso8601 as a requirement?
I want to migrate my code from other lib but i need my code to work also on Termux (terminal emulator on Android) which doesn't come with C compiler installed by default

The Termux users (which doesn't have installed clang yet) need first to install clang then install tortoise-orm

**Comment by grigi** [comment]
And manylinux1 isn't available either. It skips ciso for windows or pypy automatically.

Will look into making it optional

**Comment by grigi** [comment]
You should be able to install with NO c dependencies for the next release.
To test, please do a `pip install https://github.com/tortoise/tortoise-orm/archive/develop.zip`

**Comment by usernein** [comment]
Thanks, it worked :)

**Comment by grigi** [comment]
Released 0.16.13 with fix :smile:
