### ISSUE TITLE
How can I get all registered models?

### ISSUE THREAD

**Issue by Chise1** [tortoise/tortoise-orm#422]
I want to create permission for all models,like this:
`
class Permission(Model):
    code = fields.CharField(max_length=16, unique=True)
    description = fields.CharField(max_length=32)
`

But I don't know how to get all registered models and insert its permission field.

**Comment by long2ice** [comment]
You can use ``Tortoise.apps.get('models')``, will return a dict with all registed models.

**Comment by Chise1** [comment]
thanks
