### ISSUE TITLE
`ON CONFLICT ...` statements (upserts)

### ISSUE THREAD

**Issue by Tmpod** [tortoise/tortoise-orm#428]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to make use of the `ON CONFLICT ...` statements (and equivalants for other db systems) to make stuff like upserts or silence duplicate key errors.

**Describe the solution you'd like**
Add a method to append these statements to `QuerySet`. Maybe add an `upsert` method.

**Describe alternatives you've considered**
Haven't really considered other alternatives.

**Additional context**
I've talked with Nickolas about this in Gitter and he suggested I opened an issue.

**Comment by grigi** [comment]
Yes, I was looking at using `ON CONFLICT` for an upsert statement.

So add `upsert` that doesn't break the transaction on PostgreSQL.

**Comment by neonardo1** [comment]
This would be a great feature!

**Comment by pavdwest** [comment]
This would be great. It would make 'bulk_create' significantly more useful.

Currently 'execute_many' (used by 'execute_bulk_insert' which is in turn used by 'bulk_create') generates a statement as follows:

```
INSERT INTO "instruments" ( 
"name",    -- unique constraint
"description"
) 
VALUES ($1,$2,$3,$4) 
RETURNING "id"
```

A poor man's workaround in the interim could be to allow inserting some text before 'RETURNING "id"', even if upserts are not fully supported, e.g.

```
INSERT INTO "instruments" ( 
"name",    -- unique constraint
"description"
) 
VALUES ($1,$2,$3,$4) 
< on conflict on constraint instruments_symbol_key do update set "name" = excluded.name >
RETURNING "id"
```
My use case will see significant performance improvements from using upserts.
