### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by srkama** [tortoise/tortoise-orm#449]
**Describe the bug**
on Tortoise ORM, we are logging the connection parameters with a password in the info level. It is potential issues exposing DB credentials directly. we can add this log in debug level or mask in password while logging. 

`logger.info(
            "Tortoise-ORM startup\n    connections: %s\n    apps: %s",
            str(connections_config),
            str(apps_config),
        )
`

**Comment by ghostzero192** [comment]
exact same issue and i second @srkama proposal

**Comment by Tmpod** [comment]
Adding it to debug level is not a good solution imo, it will still be a potential security issue... Either mask it or remove it entirely imo. The user is providing the password to tortoise and if they wish to log it they very well can, not sure why anyone would do that though.

**Comment by grigi** [comment]
What about sanitising the output?
We can replace any field `password` in the data we pass to the logger with `…` to show there was a password.

**Comment by srkama** [comment]
Yes @grigi, it makes sense to sanitizing the sensitive fields.
