### ISSUE TITLE
PydanticListModel.from_queryset() vs PydanticModel.from_queryset()

### ISSUE THREAD

**Issue by SnkMaster** [tortoise/tortoise-orm#456]
Which is recommended to use?

The [FastAPI Example](https://tortoise-orm.readthedocs.io/en/latest/examples/fastapi.html#main-py) 

uses the `PydanticModel.from_queryset()`

While the [Pydantic Example](https://tortoise-orm.readthedocs.io/en/latest/examples/pydantic.html#basic-pydantic) 

uses `PydanticListModel.from_queryset()`

---
Thank You

**Comment by Isaiah-Tran** [comment]
The `PydanticListModel.from_queryset()` returns a `PydanticListModel`, while the `PydanticModel.from_queryset()` returns `List[PydanticModel]`. Performance wise, I am not sure about that. Which has the fastest performance?

**Comment by SnkMaster** [comment]
Thank You @Isaiah-Tran for pointing out the difference between `PydanticListModel.from_queryset` and `PydanticModel.from_queryset()`
