### ISSUE TITLE
functions annotate feature

### ISSUE THREAD

**Issue by mylot-python** [tortoise/tortoise-orm#466]
Excuse me, tortoise-orm have like Django's (TruncMonth /TruncQuarter/someTrunc/ExtractDay/ExtractMonth/someExtract) functions?

**Comment by long2ice** [comment]
You can build it yourself, example:
```python
from pypika import CustomFunction
from tortoise.expressions import F
from tortoise.functions import Function

class TruncMonth(Function):
    database_func = CustomFunction("DATE_FORMAT", ["name", "dt_format"])

sql = Task.all().annotate(date=TruncMonth(F('created_at'), '%Y-%m-%d')).values('date').sql()
print(sql)
# SELECT DATE_FORMAT(`created_at`,'%Y-%m-%d') `date` FROM `task`
```
All of custom function just like that.

**Comment by Rhyanz46** [comment]
Hi, I need your help,

For `date_trunc` (Postgresql function) the value position is on the right side not on the left side like `DATE_FORMAT`  Mysql Function, 

how I can switch or select the position of value and field ?

Thanks. :)

**Comment by Rhyanz46** [comment]
Hi @long2ice , I need your help,

For `date_trunc` (Postgresql function) the value position is on the right side not on the left side like `DATE_FORMAT`  Mysql Function, 

how I can switch or select the position of value and field ?

Thanks. :)

**Comment by bhch** [comment]
@Rhyanz46 In case you're still looking for answer, you can do this:

```python
from tortoise.expressions import Function
from pypika_tortoise import CustomFunction
from pypika_tortoise.terms import Function as PypikaFunction

# create pypika specific function
class _TruncMonth(PypikaFunction):
    def __init__(self, field_name, dt_format, alias=None):
        # switch parameter position below
        super().__init__("DATE_FORMAT", dt_format, field_name, alias=alias)

# create tortoise specific function
class TruncMonth(Function):
    database_func = _TruncMonth
```

**Comment by Rhyanz46** [comment]
> [@Rhyanz46](https://github.com/Rhyanz46) In case you're still looking for answer, you can do this:
> 
> from tortoise.expressions import Function
> from pypika_tortoise import CustomFunction
> from pypika_tortoise.terms import Function as PypikaFunction
> 
> # create pypika specific function
> class _TruncMonth(PypikaFunction):
>     def __init__(self, field_name, dt_format, alias=None):
>         # switch parameter position below
>         super().__init__("DATE_FORMAT", dt_format, field_name, alias=alias)
> 
> # create tortoise specific function
> class TruncMonth(Function):
>     database_func = _TruncMonth

Thanks for the answer, I've even not touch code anymore, I let them all to the claude code bro, thanks for answer me 🤣 thanks bro 🔥
