### ISSUE TITLE
ULID support

### ISSUE THREAD

**Issue by nk521** [tortoise/tortoise-orm#468]
**Is your feature request related to a problem? Please describe.**
It's not exactly a problem. Many people prefer using ULID instead of UUID.

**Describe the solution you'd like**
Something similar to UUIDField. A new class which will be similar to [this UUIDField class](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/fields/data.py#L417).

**Describe alternatives you've considered**
None.

**Additional context**
More about ULID -> https://github.com/ulid/spec

**Comment by mirrorrim** [comment]
I think there is no need to include additional dependencies in Tortoise ORM, but you can do it yourself with package `ulid-py`.  I think I'll make a library with additional fields one day.

This code is mostly copied from `UUIDField`.

```python
from typing import Any, Optional, Type, Union

import ulid
from tortoise import Model
from tortoise.fields import Field


class ULIDField(Field, ulid.ULID):

    SQL_TYPE = "CHAR(36)"

    class _db_postgres:
        SQL_TYPE = "UUID"

    def __init__(self, **kwargs: Any) -> None:
        if kwargs.get("pk", False) and "default" not in kwargs:
            kwargs["default"] = ulid.new
        super().__init__(**kwargs)

    def to_db_value(self, value: Any, instance: "Union[Type[Model], Model]") -> Optional[str]:
        return value and str(ulid.parse(value).uuid)

    def to_python_value(self, value: Any) -> Optional[ulid.ULID]:
        if value is None or isinstance(value, ulid.ULID):
            return value
        return ulid.parse(value)

```

**Comment by nk521** [comment]
> I think I'll make a library with additional fields one day.

That'll be really good. :)
And thank you for explaining it.

I'll close this issue now.

**Comment by nk521** [comment]
Hey, I'll just leave an edit here which will fix weird bugs related to ULIDField. (Like `ValueError: [TypeError("'ULID' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]`)

```
class ULIDField(Field, str):

    SQL_TYPE = "CHAR(36)"

    def __init__(self, **kwargs: Any) -> None:
        if kwargs.get("pk", False) and "default" not in kwargs:
            kwargs["default"] = ulid.new
        super().__init__(**kwargs)

    def to_db_value(
        self, value: Any, instance: "Union[Type[Model], Model]"
    ) -> Optional[str]:
        return value and str(value)

    def to_python_value(self, value: Any) -> Optional[ulid.ULID]:
        if value is None or isinstance(value, ulid.ULID):
            return value
        return value
```

removing `ulid.parse` fixes those bugs related to ULIDField for me
