### ISSUE TITLE
Can I order by a formula

### ISSUE THREAD

**Issue by draklowell** [tortoise/tortoise-orm#475]
I want to order by formula between two columns. In sql query it look like SELECT * FROM places ORDER BY (latitude-1)+(longitude-1) in SQLite, but i need it in QuerySet. Sorry, my english is well

**Comment by harrisj** [comment]
To echo this request, it would be useful to be able to provide a raw string for the order declaration that doesn't lookup fields. This would allow me to do ordering based on summing different fields or doing an order by `RANDOM()`, both of which require me to construct a raw SQL query

**Comment by long2ice** [comment]
Yes, this is a good feature.

**Comment by long2ice** [comment]
Current support order by function already, like 
```python 
await model.annotate(a=Length('field')).order_by('-a')
```

but not for expression, like

 ```python
await model.annotate(idp=F("id") + 1).order_by("-idp").values_list("id", "idp")
```

And will support that in next release.
