### ISSUE TITLE
Need more maintainers for Tortoise

### ISSUE THREAD

**Issue by grigi** [tortoise/tortoise-orm#488]
Hi all

This may seem like an odd channel to request this, I unfortunately don't have enough time to properly provide maintenance, or even attend to the logged issues/PR's any more.
My available time shrunk significantly with the current Pandemic, and probably won't improve any time soon. I tried to make time to work as much as I used to on Tortoise, but this unfortunately led to burnout :disappointed: 

So, here's my request. Is there anybody that really **WANTS** to help maintain Tortoise ORM?

Please email me (my email is all over the commit history), or reply here if you want to help.

And thank you all for being awesome :slightly_smiling_face:

**Comment by reedjosh** [comment]
@grigi 

I would be willing to give ~5hrs/week. Will pm you on Gitter. Couldn't easily find your email. : /

**Comment by grigi** [comment]
Thanks @reedjosh I have added you.

Your Oracle work is in the `oracle` branch. I was thinking of just merging it in, even if it isn't entirely complete, and mark it as WIP in the docs.

I  would still want to get it in CI, but I can't even get hold of the installation myself as the 2G download is corrupted every time I try :-(
And I don't think we would be allowed that kind of disk space on Travis CI in any case :pensive:

**Comment by reedjosh** [comment]
Awesome!  Thanks @grigi.

I just accepted.

I really admire Tortoise as a project and all the people involved. I don't know how you found the time even pre-Pandemic. I'll start slowly ramping up on Maintainer responsibilities. 

Is help most needed addressing issues and reviewing PRs?

As for Oracle, I might look into this https://github.com/cbandy/travis-oracle. I'm not personally in a huge rush to get it into Tortoise as I'm using the Oracle branch in my work project with no issues. I do think it would be great to complete for other's use though. :)

I'm also not too sure that we want to agree to the Oracle-XE licence requirements as a project either--will research further. I wonder how the SQL Alchemy and Djangos of the world regress against Oracle?

As for Tortoise as a project my current perception of priorities:
1) Hit 1.0 for a stable release w/Bug fixes along the way. Not sure what features are missing.
2) Migrations (Does this make it into 1.0?)
  * Could you also help me understand the status and goals of the refactoring effort?
3) Enhancement requests?

I look forward to working with you all again.

**Comment by grigi** [comment]
Thank you :smile: 

I'm thinking we should merge the oracle branch in, as it would then get some maintenance, even though we can't test it against a real Oracle instance. That way we can get unofficial testing with it via your work (or something).

Yes, mostly help in support on issues, and reviewing PR's.

On outstanding feature work for v1.0, I have a board here: https://github.com/tortoise/tortoise-orm/projects/1 (It probably needs some cleaning up)

Summary of what important features are outstanding for v1.0:
* Basically fixing datetime to be timezone aware
* Any API changes that will break something (e.g. the init stuff, and the query extras)
* Ensure docs are "good enough"
* Basically aim for higher test coverage without mocking everything outstanding.
* Merging the oracle stuff.

On testing: Mocking should be light for this project, as it's our entire purpose to ensure that we deal with external system bugs and quirks. So we can't just mock all the difficult parts, only that where we control the spec. (or is 100% certain that it's set in stone).

On migrations, It's not really required for v1.0
It would impact how we initialise models, and @abondar branch https://github.com/tortoise/tortoise-orm/pull/406 looks like it would alter how stuff are initialised. (If we go that path).
So I feel we should try and get those kind of things in.
But that isn't strictly necessary.

**Comment by WisdomPill** [comment]
I am open to help but my time is limited, I started using tortoise and have it in production for a while now. I would love to finish the test case I started working on a while ago.

**Comment by KrunchMuffin** [comment]
This has me nervous. I am starting a big project. Will tortoise be around and maintained/updated for the foreseeable future?

**Comment by WisdomPill** [comment]
I am using the library in production for a few months now, the only thing that I would say is missing are migrations, the rest is pretty stable in my opinion. So I would say if you are willing to manage migrations for yourself go for it. It is an amazing library, very familiar for django people and asyncio friendly. I have to say it is also strange that there is no other library comparable, a plugin asyncio orm with an easy to use api.

**Comment by long2ice** [comment]
Hey guys, please don‘t be nervous for tortoise maintenance, I and other contributors will keep maintaining tortoise, grigi don't have enough time but will also focus on tortoise. And I use tortoise in my work, so I will fix bugs and make updates for tortoise all the time.

**Comment by SakuraSound** [comment]
My time is limited, but I am using it in production too. Any small things that I see I have time for I can try to help out on.

**Comment by deajan** [comment]
Looking for an sqlalchemy async replacement.
I thought about tortoise / pony / gino, but this announcement made it a bit scary, as for midterm  /longterm roadmap goals won't be achieved easily. Is tortoise in "maintenance mode" or is it still in "full feature developpment mode" ?
Thanks ;)
