### ISSUE TITLE
Tortoise model gives `.first()` classmethod, but why there is no `last()` one?

### ISSUE THREAD

**Issue by TrDex** [tortoise/tortoise-orm#489]
I'm just curios to know how to get the last record from the database.

**Comment by long2ice** [comment]
You can use `order_by().limit(1)`

**Comment by long2ice** [comment]
You can use `order_by().limit(1)`

**Comment by long2ice** [comment]
You can use `order_by().limit(1)`

**Comment by long2ice** [comment]
You can use `order_by().limit(1)`

**Comment by TrDex** [comment]
Thanks a lot!
