### ISSUE TITLE
[question] Why orm requires PostgreSQL 9.4 while asyncpg allows PostreSQL 9.2 ?

### ISSUE THREAD

**Issue by mathbeal** [tortoise/tortoise-orm#490]
Why tortoise-orm requires PostgreSQL >= 9.4 while asyncpg allows PostgreSQL 9.2 ?

[tortoise-orm databases](https://tortoise-orm.readthedocs.io/en/latest/databases.html#databases
)
_Tortoise currently supports the following databases:
PostgreSQL >= 9.4 (using asyncpg)_

[asyncpg](https://github.com/MagicStack/asyncpg)
_asyncpg requires Python 3.5 or later and is supported for PostgreSQL versions 9.2 to 12._

**Comment by abondar** [comment]
9.2 and 9.3 already hit their EOL and not recommended (also we should deprecate 9.4 in same kind of way)

Also asyncpg excluded them from their test matrix, so wouldn't recommend to use it for anyone
Still you can try use it with 9.2-9.4, as we are not making any explicit restrictions on postgres version
