### ISSUE TITLE
(0.16.14) Cyclic FK References

### ISSUE THREAD

**Issue by zikphil** [tortoise/tortoise-orm#506]
I have 2 models: User and FileAttachment.

User is John Doe
User uploads a random file, he becomes the owner of that FileAttachment using a 'created_by' field on the FileAttachment
I try to add a 'avatar' field on the User object that's a foreignkey reference to FileAttachment, I get the cyclic fk error.

```
class User(Model):
    first_name = fields.CharField(max_length=255, null=False)
    last_name = fields.CharField(max_length=255, null=False)
    picture = fields.ForeignKeyField('models.FileAttachment')
```

```
class FileAttachment(Model):
    created_by = fields.ForeignKeyField('models.User', related_name='files')
```

```
  File "py", line 46, in init_tortoise
    await Tortoise.generate_schemas()
  File "/Users/phil/.pyenv/versions/lib/python3.8/site-packages/tortoise/__init__.py", line 596, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "/Users/phil/.pyenv/versions/lib/python3.8/site-packages/tortoise/utils.py", line 29, in generate_schema_for_client
    schema = get_schema_sql(client, safe)
  File "/Users/phil/.pyenv/versions/lib/python3.8/site-packages/tortoise/utils.py", line 18, in get_schema_sql
    return generator.get_create_schema_sql(safe)
  File "/Users/phil/.pyenv/versions/lib/python3.8/site-packages/tortoise/backends/base/schema_generator.py", line 408, in get_create_schema_sql
    raise ConfigurationError("Can't create schema due to cyclic fk references")
tortoise.exceptions.ConfigurationError: Can't create schema due to cyclic fk references
```

If I make the changes directly in Postgres, it accepts them. It's only tortoise that seems to dislike it :)

**Comment by tba91** [comment]
Could this way help?

class User(Model):
    first_name = fields.CharField(max_length=255, null=False)
    last_name = fields.CharField(max_length=255, null=False)
    picture: fields.ReverseRelation['FileAttachment']


class FileAttachment(Model):
    created_by = fields.ForeignKeyField('models.User', related_name='files')



running:


    foobar = await User.create(first_name='foo', last_name='bar')
    await foobar.save()

    file = await FileAttachment.create(created_by=foobar)
    await file.save()

    foobar_files = await FileAttachment.filter(created_by=foobar)

**Comment by lqmanh** [comment]
@tba91, I don't think it solves the problem.

Another similar case of mine:
```py
class User(Model):
    username = CharField(32)
    primary_email = ForeignKeyField("models.Email", related_name="is_primary_of")

class Email(Model):
    user = ForeignKeyField("models.User", related_name="emails")
    email_address = CharField(255)
```

**Comment by long2ice** [comment]
I think there is problem in your model design.

**Comment by lqmanh** [comment]
@long2ice Can you elaborate?
I know we need to make that `primary_email` field _nullable_, and populate it by updating the user after inserting the email. Is Tortoise somehow able to flag a foreign key nullable?

**Comment by long2ice** [comment]
```python
class User(Model):
    username = CharField(32)

class Email(Model):
    user = ForeignKeyField("models.User", related_name="emails")
    email_address = CharField(255)
    is_primary = BooleanField(default = False)
```
If me, I will design your models like this.

**Comment by lqmanh** [comment]
@long2ice Nice, thank you

**Comment by WisdomPill** [comment]
@zikphil are you sure that all the databases supported by tortoise support cyclic FK?

**Comment by SlavaSkvortsov** [comment]
How can you solve @zikphil case by changing the models design? 
@WisdomPill I'm sorry, but what DBs w/o cyclic FKs tortoise-orm supports? If some of them do not support cyclic FK is it a good reason to not support cyclic FKs at all?

**Comment by zikphil** [comment]
Oh sorry I missed the thread here. I don't think it's a question of good or bad model design. Sounds more like a software limitation :P A user field on each model for `created_by` is pretty standard. To follow this logic I would have to create a new table/model for avatars instead of using my File object, which is what I ended up doing but It felt a big wrong to just duplicate objects to counter the limitation.

**Comment by lesywix** [comment]
I also meet this problem when I'm doing migration using [aerich](https://github.com/tortoise/aerich) (It'll use the tortoise generate schema to init db).

My solution is to remove Tortoise.generate_schemas() to make sure the FastAPI can works.
For the migration, I temporarily remove the cyclic FKs on one model to make sure the aerich can init-db successful, then add the cyclic FKs back manually to generate the FKs.

**Comment by Yelinz** [comment]
Would be useful if the check could be disabled or something similar, if implementing a more advanced check isnt possible. As this has been a problem for quite a while now https://github.com/tortoise/tortoise-orm/issues/379.
https://github.com/tortoise/tortoise-orm/blob/19e2824da318fc2966a32755085767a686a84848/tortoise/backends/base/schema_generator.py#L431-L438

A simple example of a cyclic relation which could be used as a test case.
https://docs.ponyorm.org/working_with_entity_instances.html#cyclic-chains-during-saving-objects

**Comment by jannyware-inc** [comment]
Can we revisit this issue? This standard DB functionality that is being explained away as "your models are designed incorrectly". Django and ormar handle these relationships just fine, and it's what kept me from migrating my django project to tortoise.
