### ISSUE TITLE
DatetimeField is not getting updated on save even though auto_now is set to True

### ISSUE THREAD

**Issue by karthikasasanka** [tortoise/tortoise-orm#507]
**Describe the bug**

Datetimefield is not getting updated on save even though auto_now is set to True

**To Reproduce**

model
```
class Note(Model):
    id = fields.IntField(pk=True)
    title = fields.CharField(max_length=1000)
    data = fields.CharField(max_length=10000)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    def __str__(self):
        return self.data
```
methods
```
async def add(data: str, title: str=None) -> Note:
    new_note = await Note.create(data=data, title=title)
    return new_note

async def update(note_to_update: Note, note_data: dict):
    for field_name in note_data:
        setattr(note_to_update, field_name, note_data.get(field_name))
    await note_to_update.save(update_fields=note_data.keys())
    return note_to_update

```
Steps to reproduce:

1. initialize tortoise orm with postgresql
2. create new note by using above model and add method
3. update the created note by using the above update method
4. after update is completed, you can see that created_at and updated_at still have same timestamp in database

Versions:

tortoise-orm = "^0.16.15"
asyncpg = "^0.21.0"

**Additional observation**

if we additionally specify "updated_at" field explicitly for "update_fields" parameter in save method, then the datetime is being updated correctly

```
async def update(note_to_update: Note, note_data: dict):
    for field_name in note_data:
        setattr(note_to_update, field_name, note_data.get(field_name))
    await note_to_update.save(update_fields= [*note_data.keys(),"updated_at"])
    return note_to_update
```

**Expected behavior**

Should "updated_at" field be updated on save of note?

Kindly let me know if I am missing anything or if there is a better way to update

**Comment by long2ice** [comment]
If you use `update_fields`, only params in that will be update.

**Comment by karthikasasanka** [comment]
Thank you, Got the expected behavior

```
async def update(note_to_update: Note, note_data: dict):
    for field_name in note_data:
        setattr(note_to_update, field_name, note_data.get(field_name))
    await note_to_update.save()
    return note_to_update
```
