### ISSUE TITLE
tortoise.exceptions.ConfigurationError: No DB associated to model  within unit test

### ISSUE THREAD

**Issue by sunset-developer** [tortoise/tortoise-orm#512]
I'm trying to create an async unit test, however I cant seem to get it to work 
https://pastebin.com/MMcgs59q

Below is my project directory.

![Screenshot from 2020-09-25 12-36-25](https://user-images.githubusercontent.com/39848845/94293076-c743b000-ff2b-11ea-82a9-8d56137efe6d.png)

**Comment by Fingel** [comment]
@sunset-developer Did you figure this out and close it? Or give up? Having the same issue.
