### ISSUE TITLE
why not support python3.6????? why  why why

### ISSUE THREAD

**Issue by stringk245** [tortoise/tortoise-orm#528]
**Is your feature request related to a problem? Please describe.**

why not support python3.6 !!!!!???
（Tortoise ORM is supported on CPython >= 3.7 for SQLite, MySQL and PostgreSQL）

**Describe the solution you'd like**

all linux( 80% )  install python is python3.6 ( apt install python3 or yum install python3)
but Tortoise ORM need python3.7 so i must  ./configure --prefix=/usr/local/python37 to install python3.7
it take time end  inconvenient

**Describe alternatives you've considered**

hope Tortoise ORM  is supported on CPython >= 3.6 , it will be perfect !!!!!!!!!!!!!!!!!!!!!!!!!!!

**Additional context**
Add any other context about the feature request here.

hope Tortoise ORM  is supported on CPython >= 3.6 , it will be perfect !!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by abondar** [comment]
Hi!

Python 3.6 was dropped because it doesn't have `ContextVars`, while tortoise relies on them to support transactions, while available backports had bugs.

You still can use older versions of Tortoise with 3.6, specifically you can set `tortoise-orm<0.16` in your requirements
