### ISSUE TITLE
Integrate Aerich into the install

### ISSUE THREAD

**Issue by enchance** [tortoise/tortoise-orm#530]
This is very minor seeing as the solution already exists but any plans of integrating [Aerich](https://github.com/tortoise/aerich) into the install any time soon? Apparently some people I know are using alternatives like [Gino](https://github.com/python-gino/gino) because they're assuming Tortoise ORM has no migration feature.

Again, not an immediate feature request but helpful for new users.

![FireShot Capture 090 - The integration of FastAPI and Django ORM __ map(learn, world) - kigawas me](https://user-images.githubusercontent.com/1474866/96949233-fe50b580-1519-11eb-8169-8fa5267fcbb4.png)

The context here was that we were discussing porting Django's ORM to work with FastAPI, I think.

**Comment by long2ice** [comment]
Yes, that's supportable, just need add aerich to tortoise requirements and update some docs. I will do it later. Thanks for your advice.

**Comment by enchance** [comment]
Looking forward to the update man.

**Comment by K900** [comment]
I'd reconsider this - you're introducing a dependency cycle between aerich and tortoise-orm with no obvious way to break it. I'm all for advertising aerich more, but this is just making things difficult for package management tools for no obvious reason.
