### ISSUE TITLE
[QUESTION] Many to many field insert

### ISSUE THREAD

**Issue by lvar** [tortoise/tortoise-orm#534]
I've been stuck for 2 days trying to solve this problem...please any help would be appreciated.

[Code](https://stackoverflow.com/questions/64503836/tortoise-orm-many-to-many-field-insert)

Thanks for your time

**Comment by long2ice** [comment]
Could you show full error log? otherwise, you need only call `init_models` once.

**Comment by lvar** [comment]
Here it is:

`Traceback (most recent call last): File "C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi result = await app(self.scope, self.receive,
self.send) File "C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__ return await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\applications.py", line 179, in __call__ await super().__call__(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\applications.py", line 111, in __call__ await self.middleware_stack(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__ raise exc from None File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__ await self.app(scope, receive, _send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__ await self.simple_response(scope, receive, send, request_headers=headers) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\exceptions.py", line 82, in __call__ raise exc from None File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 566, in __call__ await route.handle(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 227, in handle await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 41, in app response = await func(request) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\routing.py", line 182, in app raw_response = await run_endpoint_function( File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\routing.py", line 133, in run_endpoint_function return await dependant.call(**values) File
"C:\Users\el_sh\OneDrive\Escritorio\codes\admin_final\admin\app\routes\routes.py", line 125, in post_presupuesto insert_related = await insert_result.tratamiento.add(*tratamiento) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\tortoise\fields\relational.py", line 188, in add related_pk_formatting_func = type(instances[0])._meta.pk.to_db_value AttributeError: type object
'tuple' has no attribute '_meta' ERROR:uvicorn.error:Exception in ASGI application Traceback (most recent call last): File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi result = await app(self.scope, self.receive, self.send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__ return await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\applications.py", line 179, in __call__ await super().__call__(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\applications.py", line 111, in __call__ await self.middleware_stack(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__ raise exc from None File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__ await self.app(scope, receive, _send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__ await self.simple_response(scope, receive, send, request_headers=headers) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\exceptions.py", line 82, in __call__ raise exc from None File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 566, in __call__ await route.handle(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 227, in handle await self.app(scope, receive, send) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\starlette\routing.py", line 41, in app response = await func(request) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\routing.py", line 182, in app raw_response = await run_endpoint_function( File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\fastapi\routing.py", line 133, in run_endpoint_function return await dependant.call(**values) File
"C:\Users\el_sh\OneDrive\Escritorio\codes\admin_final\admin\app\routes\routes.py", line 125, in post_presupuesto insert_related = await insert_result.tratamiento.add(*tratamiento) File
"C:\Users\el_sh\AppData\Local\pypoetry\Cache\virtualenvs\app-uwxeHXiN-py3.8\lib\site-packages\tortoise\fields\relational.py", line 188, in add related_pk_formatting_func = type(instances[0])._meta.pk.to_db_value AttributeError: type object
'tuple' has no attribute '_meta'
`

**Comment by long2ice** [comment]
try replace 
```python
tratamiento = await tratamiento_out.from_queryset_single(Tratamiento.get(id=item.tratamiento_id))
```
to
```python
tratamiento = await Tratamiento.get(id=item.tratamiento_id)
```

**Comment by lvar** [comment]
Working now !!! thank you so much!!..
