### ISSUE TITLE
[QUESTION] Add fields to trough table

### ISSUE THREAD

**Issue by lvar** [tortoise/tortoise-orm#542]
How can I add some extra fields to an trough table in a many to many field ?
I've been reading [Docs](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html?highlight=through#relations) ,but the examples are not really clear...it only shows this code:

`participants: fields.ManyToManyRelation["Team"] = fields.ManyToManyField("models.Team", related_name="events", through="event_team"
    )
`

Could you please add an example of how can I add extra fields to "event_team"  ?

**Comment by abondar** [comment]
Hi!

Right now it is not possible to add new fields to M2M relation.

But instead of adding new fields, you could create new model like this

```
class Participant(Model):
    name = fields.TextField()
    event: fields.ForeignKeyRelation[Event] = fields.ForeignKeyField(
        "models.Event", related_name="participants"
    )
    team: fields.ManyToManyRelation["Team"] = fields.ForeignKeyField(
        "models.Team", related_name="participations"
    )

    def __str__(self):
        return self.name

```

**Comment by lvar** [comment]
@abondar aahh ok...I get it...thank you !
Anyway...I think this should be considered  in next release.

**Comment by abondar** [comment]
Will be glad to review PR with this changes. As of now we don't have it in our near plans
