### ISSUE TITLE
[QUESTION] Reverse relation doesnt appears in schema()

### ISSUE THREAD

**Issue by lvar** [tortoise/tortoise-orm#543]
I have the following models:

`     

    class Presupuesto(models.Model):

    id = fields.UUIDField(pk=True)
    paciente = fields.ForeignKeyField('models.Paciente', related_name="presupuesto_paciente", on_delete=fields.CASCADE)    
    tratamiento = fields.ManyToManyField('models.Tratamiento', related_name="presupuesto_tratamiento", on_delete=fields.CASCADE)
    estado_vigencia = fields.BooleanField(default=False)

    def total_descuento(self) -> int:
        return 0

    class PydanticMeta:
        computed = ("total_descuento",)

     Tortoise.init_models(["db.models"], "models")
     presupuesto_in = pydantic_model_creator(Presupuesto, name="PresupuestoIn", exclude_readonly=True)
     presupuesto_out = pydantic_model_creator(Presupuesto, name="PresupuestoOut")

    class Pago(models.Model, TimestampMixin):

    id = fields.UUIDField(pk=True)
    medio_pago = fields.CharField(max_length=500)
    tratamientos_pagados = fields.JSONField()
    presupuesto = fields.OneToOneField('models.Presupuesto', related_name="presupuesto_pago", on_delete=fields.CASCADE, null=True)

    Tortoise.init_models(["db.models"], "models")
    pago_in = pydantic_model_creator(Pago, name="PagoIn", exclude_readonly=True)
    pago_out = pydantic_model_creator(Pago, name="PagoOut")`

When I print presupuesto_out.schema() doesn't print the related name "presupuesto_pago" from Pago model...I try to find  solutions for 2 hours...so If you could help me I'd appreciate it. 

**ROUTE**
`

     @router.get("/presupuestos/{id}", response_model=presupuesto_out)
      async def get_presupuesto(id: str):
      print(presupuesto_out.schema())
      presupuesto = await presupuesto_out.from_queryset_single(Presupuesto.get(id=id))
      if presupuesto.paciente.convenio:
        porcentaje = presupuesto.total * (presupuesto.paciente.convenio.descuento/100)
        presupuesto.total_descuento = presupuesto.total - porcentaje
    
      return presupuesto`

**Comment by lvar** [comment]
Found the solution...the pattern is add: 



     Tortoise.init_models(["db.models"], "models")
     #and after that add every pydantic model you have on your app

**Comment by shuhaojie** [comment]
Appreciate. It works.
