### ISSUE TITLE
[QUESTION] Add same instance more than once to M2M field

### ISSUE THREAD

**Issue by lvar** [tortoise/tortoise-orm#545]
I have a M2M relation where a user can choose moren than once the same product and also differents products. But when I see my DB only appears 1 registry. Example:

     UserID     ProductID
        1           1     <---added
        1           2     <---added
        1           1     <--- not added
        1           1     <---not added

Any idea ?...this is the code, thanks for your help:

       insert_result = await Presupuesto.create(**presupuesto.dict(exclude_unset=True))
        for item in tratamientos:
        tratamiento = await Tratamiento.get(id=item.tratamiento_id)
        insert_related = await insert_result.tratamiento.add(tratamiento)

**Comment by abondar** [comment]
Hi!

This is intended behaviour, as adding same value several times and then returning several same instances on `tratamiento` fetch would be confusing
It is also in accordance with Django's behaviour, which we are trying to be in line with, so it won't be confusing for people switching to Tortoise

I would recommend deriving here a new explicit model for that M2M, that way you will overcome your problem and that approach also gives you ability to expand your relation

E.g. if relation you are talking about is some kind of `purchase` , you could add then a timestamp of when it was bough, and will be able to work with those `purchase` as separate entity, not limited by M2M relation concept

**Comment by lvar** [comment]
@abondar Any example of your suggestion in docs ? ..I don't understand when you said "I would recommend deriving here a new explicit model for that M2M"
