### ISSUE TITLE
F Expression directly on object causing weird behaviour

### ISSUE THREAD

**Issue by dstlny** [tortoise/tortoise-orm#549]
**Describe the bug**
Serialising a model-object after using a F Expression directly against a objects fields (as opposed to using .filter.update), causes the fields that the F expression is against, to return an object and not the actual value of the field.

**Reproduce**

Lets say we have the following model:
```python
class Post(models.Model):
	'''
		Represents a post
	'''

	id = fields.IntField(pk=True)
	title = fields.TextField(max_length=150)
	content = fields.TextField(max_length=1200)
	created = fields.DatetimeField(auto_now=True)
	likes = fields.BigIntField(
		default=0
	)
	dislikes = fields.BigIntField(
		default=0
	)

	def __str__(self) -> str:
		return f"{self.created} | {self.title}"
```

 And we try do some 'updates' to a 'post' object like below, causes undefined behaviour.

```python
post = await Post.get(id=post_id)

update_fields = []

if action_type == TypeEnum.LIKE:
	post.likes = F("likes") + 1
	update_fields.append("likes")
	if post.dislikes < 0:
		post.dislikes = F("dislikes") + 1
		update_fields.append("dislikes")
else:
	post.dislikes = F("dislikes") - 1
	update_fields.append("dislikes")
	if post.likes > 0:
		post.likes = F("likes") - 1
		update_fields.append("likes")
	
await post.save(update_fields=update_fields)
```

Serialising the above post, causes the 'likes' and 'dislikes' field to be replaced by a object, which looks something along the lines of:
```json
{
  "alias": null,
  "operator": "+",
  "left": {
    "alias": null,
    "value": null,
    "name": "likes",
    "table": null
  },
  "right": {
    "alias": null,
    "value": 1
  }
}
```

**Expected behavior**
Expecting the value of "likes" and "dislikes" to actually bt eh value of "likes" and "dislikes" on the object after being incremented/decremented, not a object

**Comment by long2ice** [comment]
We need a `refresh_from_db` like Django
