### ISSUE TITLE
How about RangeType field?

### ISSUE THREAD

**Issue by nacknime-official** [tortoise/tortoise-orm#554]
I needed Postgres's [Range types](https://www.postgresql.org/docs/current/rangetypes.html).

I see that as field called, for example, `IntRange` with params `min` and `max` at least.
This field should has method to convert it into `str`.
If `max` param is None, that'll be `infinity number`.
If `min` param is None, that'll be `0`

Alternative solution:
I can create two columns `min` and `max` and work with them, but it isn't comfortable.

**Comment by long2ice** [comment]
see https://tortoise-orm.readthedocs.io/en/latest/fields.html#extending-a-field

**Comment by long2ice** [comment]
And  implement a `RangeField`  is very simple:
```py
from tortoise.fields import Field
from asyncpg import Range

class Int4RangeField(Field, Range):
    SQL_TYPE = "int4range"

    def to_python_value(self, value: Any) -> Any: # need this because asyncpg convert it automatically
        return value


class CustomFieldModel(Model):
    range_field = Int4RangeField()

field = await CustomFieldModel.create(range_field=Range(1, 2))
field_get = await CustomFieldModel.get(pk=field.pk)
assert field.range_field == field_get.range_field
```
