### ISSUE TITLE
Unnecessary cyclic dependency on Aerich in 0.16.17

### ISSUE THREAD

**Issue by nckx** [tortoise/tortoise-orm#558]
Hi,

Please consider reverting [this new cyclic dependency on Aerich](https://github.com/tortoise/tortoise-orm/pull/531/commits/7f8e3b6d7b173fe6aa508249d2322e7dfd41dff8#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552).

Tortoise-orm doesn't need Aerich at all: it simply wants [to promote its existence](https://github.com/tortoise/tortoise-orm/issues/530).  `requirements.txt` is the wrong place to do so and creates needless distribution headaches.

This is a documentation problem.  The same commit also adds an excellent guide.  Perhaps promoting it earlier in the README, before the tutorial, would help?

I say perhaps, because people ‘unaware’ of Aerich never bothered to read it.

Thanks!

**Comment by long2ice** [comment]
Yes, cyclic dependency is a bad thing, I will revert that in next release.

**Comment by long2ice** [comment]
close since https://github.com/tortoise/tortoise-orm/releases/tag/0.16.18
