### ISSUE TITLE
Caching database support like django

### ISSUE THREAD

**Issue by FalseDev** [tortoise/tortoise-orm#580]
**Is your feature request related to a problem? Please describe.**
I'm working on a bot (using `discord.py`) that has a whole ton of features, every message sent in a server where the bot is present requires querying the database several times, most data is accessed over and over.

**Describe the solution you'd like**
I'd like to know if it is possible to inherit all my models from a different `Model` class which in turn inherits from the Model class, overriding the `get`, `get_or_none`, `get_or_create`, `create` methods to have some sort of serialization method to get only the value fields and cache them into redis.

**Describe alternatives you've considered**
Manually caching into redis is possible but that'd mean changing things in several (20+) models **or** changing so many other files

Can you provide an example to do this, or suggest a better solution. Any suggestions or reply is appreciated!

**Comment by long2ice** [comment]
Maybe you can cache it yourself, use redis or lru cache which python builtin etc.

**Comment by FalseDev** [comment]
> Maybe you can cache it yourself, use redis or lru cache which python builtin etc.

Manually caching all 20+ models in several files is not possible at this stage, is there anything like I've asked in the **Describe the solution you'd like** sections?

**Comment by FalseDev** [comment]
I've kinda found a solution by serializing objects using
```py
{k: getattr(instance, k) for k in instance._meta.db_fields if getattr(instance, k) != None}
```
and using hmset in redis through aioredis

I made a decorator to apply it to required models. Hence, I'm closing this issue.
