### ISSUE TITLE
Limit connections to database

### ISSUE THREAD

**Issue by SneakyBerry** [tortoise/tortoise-orm#582]
**Is your feature request related to a problem? Please describe.**
In some cases we need to limit connections to DBMS, now I don't see this parameter and key "limit" in "connections" does not make sense.

**Describe the solution you'd like**
Make a possibility to set connections count limit in init parameters/config/dict.

**Comment by abondar** [comment]
Hi!

Does `minsize` and `maxsize` params resolve your case?
https://tortoise-orm.readthedocs.io/en/latest/databases.html?highlight=maxsize#id6

**Comment by SneakyBerry** [comment]
I don't think so. Yesterday i look at my datadog dashboard and there was 88 connections, but maxsize set to 10. Only two replicas of service use database. Does tortoise keep unused connections active?

**Comment by abondar** [comment]
Tortoise does not manage connection pool itself, it just passes size params to underlying db driver, so can't be sure if it's tortoise issue

Which RDBMS do you use?

**Comment by SneakyBerry** [comment]
PostgreSQL 11

**Comment by abondar** [comment]
Well, in case of asyncpg we just pass size params to `create_pool` method. Don't think we recreate pool in any other places in code. 
I would advise you to explore it further to get more info about your issue

Good first step would be to log your actual pool size in services to see if it exceeds expected values

To get to `pool` variable and it's current size in your code you could do something like
`pool = Tortoise.get_connection("your connection name"). _pool`

To figure out current count of active connections you could go for something like this
`count = len(ch for ch in pool._holders if ch._con is not None)`

Not sure if it will work, compiled it based on this code https://magicstack.github.io/asyncpg/current/_modules/asyncpg/pool.html#Pool

Don't see better way to figure out actual amount of connections

**Comment by SneakyBerry** [comment]
Ok. Thanks for the answer.
