### ISSUE TITLE
Getting n levels of relations with no need

### ISSUE THREAD

**Issue by lsabi** [tortoise/tortoise-orm#583]
**Describe the bug**
I'm not sure if this is an actual bug, an intended behaviour or a feature that has not been implemented yet. I've looked on the documentation, stackoverflow and on the internet, with no success. Thus I'm posting here.

Basically, I've a quite more complex database structure with respect to the examples in the docs, with many relations (especially 1:M and 1:1).

The problem is, when I try to query a table, I also get the related rows from other tables, which is awesome, although tortoise orm starts also to query the relations of the relations. So, if I'm querying table A and would like to have also the reference values from table B, I also get those from table C.

Hereby I provide an example that is different from my context of usage, but it proposes the problem I'm encountering with a much bigger emphasis.

Consider the case of an online e-commerce. A user may want to view the products under a certain category. If I query the database with tortoise orm getting a category with a particular id, I get the category row with all the related products. This is awesome, but then, for each product, I also get those who have bought it, which is definitely not a good thing.

In my case, I do not have such security issues, at the moment, but this really slows down the queries, to the point where users have to wait approximately 5 seconds.

**To Reproduce**
Since I'm in a private context, I cannot provide details. Although I can say that I'm using reversed relations.

This behavior occurs when I'm both using code like `Category_Pydantic.from_queryset_single(Category.get(id=category_id))` and `Category_Pydantic.from_queryset(Category.all())`

**Expected behavior**
The expected behavior is to receive a response in a smaller amount of time, thanks to the fewer joins needed (I guess).

**Additional context**
It may be a feature request, although it looks strange to me that nobody raised questions about it.

Thanks

**Comment by dstlny** [comment]
This would be because Tortoise recursively fetches the relations on nested objects.

You can customise how deep it goes via adding a PydanticMeta class to your Model, and tweaking the "allow_cycles" and "max_recusion" flag: https://tortoise-orm.readthedocs.io/en/latest/examples/pydantic.html#recursive-models-computed-fields

**Comment by lsabi** [comment]
It worked. Now everything is much, much faster.

Thanks, it should be way more visible, I couldn't find it.

**Comment by lsabi** [comment]
I'm facing an odd issue now:

It seems like the `Pydantic_Meta` options do not apply to reversed relations. When fetching categories, I get back the related products, which is handy, although I also get who bought that item, due to the reversed relation. If it's an admin, that's a nice feature to have, but if it's a user, it's a data breach.

This is the code I have in the category model

### Category Model
```
class PydanticMeta:
        allow_cycles = False
        max_recursion = 0
```

### Function
`await Category_Pydantic.from_queryset(Category.all())`

How should one deal with such scenario? I would need to only get a list of categories, no other field (there's just one reverse relation field in my case, but Tortoise seems to extract also other fields related to the reversed relation table).

Thanks

**Comment by dstlny** [comment]
Yeah, this isn't currently possible - i believe a Pull Request is currently open to implement this: #536.

For now, as a work-around, you should be able to exclude these fields using the "exclude" attribute - this takes a Tuple of field-names.

**Comment by lsabi** [comment]
That could be an alternative, if only I didn't need in some cases and in some cases not, the reversed relation.

I'll keep an eye on it. In the meantime, thanks for the support!
