### ISSUE TITLE
AttributeError: type object 'Tortoise' has no attribute 'init'

### ISSUE THREAD

**Issue by markhulia** [tortoise/tortoise-orm#588]
**Describe the bug**
`AttributeError: type object 'Tortoise' has no attribute 'init'`
This error appears when installing `toirtoise-orm` from the `requirements.txt` file. If `tortoise-orm` is installed directly with `pip install tortoise-orm` then everything works fine
I've encountered this issue when packaging app in Docker container. It is reproducible every-time

**To Reproduce**
> Assuming you have a `main.py` with simple application
1. Create `requirements.txt`
    ```bash
    tortoise==0.1.1
    tortoise-orm==0.16.18
    ```
2. Create a smiple Dockefile:
    ```bash
    FROM python:3.8-slim
    ENV wd /workdir
    WORKDIR ${wd}
    COPY requirements.txt /tmp/
    RUN pip install -r /tmp/requirements.txt
    ADD main.pt ${wd}/
    ENTRYPOINT [ "python"]
    CMD ["main.py"]
    ```

3. Create docker image
   ```bash
    docker build . -t broken-tortoise-demo:dev
    ```

    and run an interactive shell in it

    ```bash
    docker run -it --entrypoint /bin/bash broken-tortoise-demo:dev
    ```
4. Run `python main.py`
5. Application fails with the following error:
    ```bash
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/sanic/app.py", line 1128, in run
        serve(**server_settings)
      File "/usr/local/lib/python3.8/site-packages/sanic/server.py", line 883, in serve
        trigger_events(before_start, loop)
      File "/usr/local/lib/python3.8/site-packages/sanic/server.py", line 693, in trigger_events
        loop.run_until_complete(result)
      File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
      File "main.py", line 33, in connect_to_db
        await Tortoise.init(
    AttributeError: type object 'Tortoise' has no attribute 'init'
    ```
6. Now, reinstall `tortoise` with removing it
    ```bash
    pip uninstall tortoise tortoise-orm
   ```
   and then installing
   ```bash
   pip install  tortoise-orm
   ```
 7. Run the application again with `main.py`

Result: Application does not fail anymore
   

**Expected behavior**
Installing tortoise from the `requirements.txt` file should have the same result as installing it with `pip`

**Comment by markhulia** [comment]
Ok, after some more digging it seems like the culprit is `pipreqs` pacakge.  When freezing packages with `pipreqs` it adds `tortoise` instead of `tortoise-orm` to the requirements file. The reason being that `pipreqs` parses python files for the potential imports, so when it hits `from tortoise import Tortoise` it  assumes it's a `tortoise` package. 
I've wasted quite some time on this and I hope this helps anyone 

You can close this issue 👍

**Comment by douyahu** [comment]
按照楼上说的，构建时应该改为：
`
RUN cd /app  \
    && pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ \
    && pip uninstall tortoise tortoise-orm  \
    && pip install tortoise-orm
`
