### ISSUE TITLE
Querying with field on related object doesn't work

### ISSUE THREAD

**Issue by FalseDev** [tortoise/tortoise-orm#590]
**Describe the bug**
When queried using `get_or_create` using a related model's field, tortoise raises `tortoise.exceptions.DoesNotExist: Object does not exist` instead of creating an object that's related to the query

**To Reproduce**
I ran this python code to confirm this:
```py
from tortoise import Tortoise, fields, Model, run_async

class ModelA(Model):
    id = fields.BigIntField(pk=True)

class ModelB(Model):
    relation = fields.ForeignKeyField('test.ModelA')

async def main():
    await Tortoise.init(TORTOISE_CONFIG)
    object1 = await ModelA.create(id=1)

    print(object1.id)
    object2, created = await ModelB.get_or_create(relation__id=object1.id)

TORTOISE_CONFIG = {
    "connections": {"default": 'DATABASE_URI'},
    "apps": {
        "test": {
            "models": [__name__, "aerich.models"],
            "default_connection": "default"
        }
    }
}

if __name__ == '__main__':
    run_async(main())
```

**Expected behavior**
The expected behaviour is tortoise-orm returning a newly created object that is related to `object1`

**Additional context**
The commands I used are
```sh
createdb test
aerich init -t tortoise_test.TORTOISE_CONFIG
aerich init-db
python3 tortoise_test
```

**Other info**
Tortoise version: tortoise-orm==0.16.18
Python version: Python 3.7.3
Dialect: PostgreSQL 11.9

**Comment by Abdeldjalil-H** [comment]
I just test it on version `0.21.6`. It is not giving `DoesNotExist` anymore, but it raises `IntegrityError`. This is because in the code above you're using `relation__id` (with dunder), so `relation_id` is not set. If you use `relation_id=object1.id` or `relation=object1` it will pass. I think this can be closed @abondar @henadzit
