### ISSUE TITLE
FastAPI POST/PUT Object with M2M relations

### ISSUE THREAD

**Issue by lsabi** [tortoise/tortoise-orm#592]
**Is your feature request related to a problem? Please describe.**
I'm using `FastAPI` in conjuction with `Tortoise-orm`, together with `Pydantic`.

With `ForeignKeyField` it's pretty easy to add (`POST`) a new object, since it is treated as a normal field (and this is documented in the generated OPENAPI schema). When it comes to adding an object that has an M2M relation, it gets troublesome. Considering the example of the official docs [https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html#relations](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html#relations), one may need to add a new `Team` participating to an already existing `Event`. For this case, the generated OPENAPI docs show that one has to first create a new `Team` and only then add the M2M relation.

The solution is to separately add the M2M relation in a second step, via another path (e.g. `/myapi/object/{id}/feature/`). This can be done, but it may not be fully executed, leaving, in the case of a connection failure, a half added information. Also, it is not documented how to properly do it (which model should I use?).

**Describe the solution you'd like**
A simple way to add a new object having an M2M relation in an ACID way. That is, all or nothing, especially since APIs rely on HTTP connections which are stateless and may be interrupted suddently.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

Thanks

**Comment by metakot** [comment]
This is clearly an issue to fastapi, not to orm. You can do it in a path operation function by yourself, just add one line of code.

**Comment by lsabi** [comment]
I don't think so. It could be related to `pydantic`.

My point is, to create a `pydantic` model that has an optional field `m2m_field` that accepts a list of ids (or whatever) and that it can be used to have only one transaction that writes into the database, instead of having two API calls on the same object.

**Comment by metakot** [comment]
And what stops you from just implementing that? Can you bring some examples to expand the question?

**Comment by lsabi** [comment]
What stops me from implementing it, is the fact that I do not know how to implement that, starting from a `tortoise.model` and extending it.

There are `fastapi` docs, but they do not show how to insert new records in tables along with M2M relations, via an all-or-nothing approach.

As an example, one could take the one in the official docs [https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html#relations](https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html#relations)

**Comment by metakot** [comment]
Well, you can do something like:

```python
class TeamIn(BaseModel):
    name: str


class CreateTeamParams(BaseModel):
    team: TeamIn
    events: List[int]


class TeamOut(TeamIn):
    id: int
    events: List[int]


@api.post('/api/team',
    response_model=TeamOut,
)
async def create_team(
    params: CreateTeamParams = Body(...),
):
    team = await Team.create(**params.team.dict())
    events = await Event.filter(id__in=params.events).only('id')
    await team.events.add(*events)
    return TeamOut(id=team.id, name=team.name, events=params.events)
```
