### ISSUE TITLE
Field add  extra kwargs.

### ISSUE THREAD

**Issue by Chise1** [tortoise/tortoise-orm#603]
I hope fields.Field can add extra attribute to save kwargs.
like this:
`
def __init__(self,...):
    ....
    this.kwargs=kwargs
`
Then I can add extra args like "verbose_name" or "help_text".

**Comment by Chise1** [comment]
`
class Field(metaclass=_FieldMeta):
    ...

    def __init__(self,...):

        ...
        this.kwargs=kwargs

`

**Comment by long2ice** [comment]
So where to use it?

**Comment by Chise1** [comment]
I'm writing a project.The project can add views for router,
like:

`
@router.post(
    "/message",
    view=DialogAction(
        label="create",
        dialog=Dialog(
            title="create",
            body=Form(
                name="message_create",
                controls=get_coulmns_from_pmc(message_schema, add_type=True),
                api="http://127.0.0.1:8000/amis/message",
            ),
        ),
    ),
    response_model=message_schema,
)
async def create_message(message: message_schema):

    return await Message.create(**message.dict())

`
When I create form's column,I need add extra info to column.I wish Field has extra args ,then I can create :
eg:
`
class  Column(BaseModel):
    label:str
    help_text:str
    type:str
    ...
`

**Comment by Chise1** [comment]
Maybe sqlalchemy is a better choice.
