### ISSUE TITLE
Allow function results in group by

### ISSUE THREAD

**Issue by MrAngry** [tortoise/tortoise-orm#608]
Allow grouping by function result. This is especially useful with datetime fields. A simple example from postgresql :

`SELECT  EXTRACT(YEAR from date_column) FROM sales group by EXTRACT(YEAR from date_column)`

You can see how this is useful when creating for example yearly, monthly or daily sales results. Without this functionality you need to denormalize your table so year , month and day stays in separate columns.

**Comment by long2ice** [comment]
try https://tortoise-orm.readthedocs.io/en/develop/functions.html#custom-functions with `group_by`

**Comment by MrAngry** [comment]
> try https://tortoise-orm.readthedocs.io/en/develop/functions.html#custom-functions with `group_by`

I am not exactly sure what this gives me. I already created a custom function for `EXTRACT` but the `group_by` function does not allow me plugin it in as it expects strings.

**Comment by long2ice** [comment]
Could you show your code with models  here? I can try it.

**Comment by MrAngry** [comment]
> Could you show your code with models here? I can try it.
Sure:

```
class Sales(Model):
    product_model = ForeignKeyField("models.ProductModel") 
    district = ForeignKeyField("models.District")
    count = DecimalField(max_digits=6, decimal_places=0)
    date = DateField()
```
My custom extract work well with `annotate`
 ```
    class Extract(Function):
    database_func = Extract

    def _get_function_field(
            self, field: "Union[ArithmeticExpression, Field, str]", *default_values
    ):
        return self.database_func(*default_values,field)
 ```
Usage example:
` sales = sales.annotate(year=Extract(F('date'), 'YEAR')).filter(year__in=request.year)`

**Comment by MrAngry** [comment]
I could also add code for `ProductModel` and `District` but I think it is not important as those fields do not play any role here.

**Comment by long2ice** [comment]
OK, this should be a new feature
