### ISSUE TITLE
Expectation on 0.16.20 Release Date

### ISSUE THREAD

**Issue by jbertman** [tortoise/tortoise-orm#617]
Loving the ORM so far. I'm looking to utilize the model validators functionality. I saw it was available on ReadTheDocs, but I see the 0.16.20 release is not yet available on PyPi or tagged on GitHub. Is there a typical release cadence? I'd rather not build from master if I can help it.

Thanks in advance!

**Comment by long2ice** [comment]
Yes, will release 0.16.20 recently with that

**Comment by long2ice** [comment]
released
