### ISSUE TITLE
JSONField calls validate before decode

### ISSUE THREAD

**Issue by gregbeech** [tortoise/tortoise-orm#621]
**Describe the bug**

Tortoise v0.16.20 included custom validations. However, if you use one of these on a `JSONField` then when retrieving data from the database then the validation is run against the encoded string version of the JSON rather than the decoded value. This means the validation function for JSON isn't symmetric as it runs against the decoded value when setting it.

**To Reproduce**

```python
import uuid

from tortoise import fields
from tortoise.exceptions import ValidationError
from tortoise.models import Model

def must_have_three_items(value: List[str]) -> None:
    if not len(value) == 3:
        raise ValidationError("List must have three items.")

class TestModel(Model):
    id = fields.UUIDField(pk=True, default=uuid.uuid4)
    data = fields.JSONField(validators=[must_have_three_items])

async def repro() -> None:
    m1 = await TestModel.create(data=["foo", "bar", "baz"]
    m2 = await TestModel.get(pk=m1.id)  # boom! value = '["foo", "bar", "baz"]'
```

**Expected behavior**

It ought to be possible to write the validation for JSON fields as a symmetric function, i.e. if it validates the Python value on the way into the database then it ought to validate the Python value on the way out, rather than the literal JSON string.

**Additional context**

I was using Postgres so this was a JSONB column, but I don't think this should matter.

The fix looks to be quite straightforward, moving [this line](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/fields/data.py#L470) after the conditional decode. I'm happy to put a PR together if you confirm the issue is valid.

**Comment by long2ice** [comment]
That's right, welcome to PR

**Comment by long2ice** [comment]
And `Makefile` is your friend, also please give unittest cover that bug, thanks.
