### ISSUE TITLE
`update_fields` not working with Model.save()

### ISSUE THREAD

**Issue by waydegg** [tortoise/tortoise-orm#627]
**Describe the bug**
Including the `update_fields` arg with Model.save() doesn't create the Model in the database if it doesn't exist yet. 

**To Reproduce**
Here's a basic example to test this: 
```
from tortoise import Tortoise, fields, run_async
from tortoise.models import Model

class TestModel(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()

    class Meta:
        table = "test_table"

    def __str__(self):
        return self.name

async def run():
    # Init Tortoise
    await Tortoise.init(
        db_url='[a valid db url]',
        modules={'models': ['__main__']})
    await Tortoise.generate_schemas(safe=True)
    
    # Try to create model that doesn't exist yet with `update_fields` specified
    await TestModel(id=1, name="Joe").save(update_fields=["name"])
    # Result: no exception thrown, but the model is never created in the DB

if __name__ == "__main__":
    run_async(run())
```

**Additional context**
- tortoise-orm  version 0.16.20
- asyncpg version 0.21.0
- Admin user on Postgres 12.4

**Comment by long2ice** [comment]
Becase you specifies the `id`, tortoise consider it exists in db and generate `update...` sql, in your example, just remove `id`, also you can pass `force_create` or `force_update` to `model.save()`
