### ISSUE TITLE
Get the ID from a ForeingKeyRelation field

### ISSUE THREAD

**Issue by BenoitPingris** [tortoise/tortoise-orm#634]
**Describe the bug**
Can't get the ID from a ForeignKeyRelation after I get a model that a field like that

**To Reproduce**
```py
class Fridge(Model):
    id = fields.UUIDField(pk=True)
    user = fields.ForeignKeyField('models.User', related_name='fridge')
    name = fields.CharField(50, unique=True)

async def get_fridge(id):
    fridge = await Fridge.get(id=id)
    print(fridge.user, fridge.user.id) # how can I get the ID of the user
```

**Expected behavior**
I believe there's an easy way to just extract the ID from the model I just fetched, but couldn't find any example, what am I missing here?

**Comment by long2ice** [comment]
use `fridge.user_id` or `fridge = await Fridge.filter(id=id).select_related('user').first()` then `fridge.user.id` or some other attrs in `user`

**Comment by BenoitPingris** [comment]
Thanks! `fridge.user_id` seems to be working pretty well for my case, however my linter (pyright) warns me about the field `user_id` and I have red squiggles:
```
[Pyright reportGeneralTypeIssues] [E] Cannot access member "user_id" for type "Fridge"
  Member "user_id" is unknown
```
Is there a way to "generate" the field `user_id` for the type `Fridge`? Or should I look for a setting with my linter to ignore that?

**Comment by long2ice** [comment]
just ignore it

**Comment by BenoitPingris** [comment]
ok I just found a way to do that, again, thanks for your help :+1:
