### ISSUE TITLE
Pytest failing - `ScopeMismatch: You tried to access the 'function' scoped fixture 'event_loop' with a 'session' scoped request object, involved factories`

### ISSUE THREAD

**Issue by b177y** [tortoise/tortoise-orm#638]
**Describe the bug**
Trying to add testing with pytest, getting `ScopeMismatch: You tried to access the 'function' scoped fixture 'event_loop' with a 'session' scoped request object, involved factories`.

I understand that I'm probably doing something wrong but the documentation only covers the initializer and not how to run tests with pytest, so if anyone could point me to an example that would be great!

**To Reproduce**

```
import pytest
import os
from tortoise.contrib import test
from tortoise.contrib.test import finalizer, initializer
from models import User


@pytest.fixture(scope="session", autouse=True)
@pytest.mark.asyncio
async def initialize_tests(request):
    db_url = os.environ.get("TORTOISE_TEST_DB", "sqlite://:memory:")
    initializer(["models"], db_url=db_url, app_label="models")
    request.addfinalizer(finalizer)
    await User.create(username="joebloggs",
                      firstname="Joe",
                      lastname="Bloggs",
                      admin=False,
                      email="joe@example.com",
                      pw_hash="test")


@pytest.mark.asyncio
async def test_something():
    u1 = await User.all().first()
    assert u1.username == "joebloggs"
```

**Expected behavior**
Test should run successfully

**Additional context**

I have tried using pytest with the 
```
from tortoise.contrib import test

class TestSomething(test.TestCase):
    def test_something(self):
```

which also failed.

Also getting warning 
```
asynctest/mock.py:434: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait(self, skip=0):
```
which i think has been mentioned in another issue and is not fatal (and not related to my issue but thought id mention it for full context)

**Comment by jrversteegh** [comment]
> ```python
> @pytest.fixture(scope="session")
> def event_loop():
>     return asyncio.get_event_loop()
> ```

This works but generates a warning, but the example in the pytest docs you linked to doesn't:
```python
@pytest.fixture(scope="session")
def event_loop():
    """Overrides pytest default function scoped event loop"""
    policy = asyncio.get_event_loop_policy()
    loop = policy.new_event_loop()
    yield loop
    loop.close()
```

**Comment by copdips** [comment]
```python
@pytest.fixture(scope="session")
def event_loop():
    """Overrides pytest default function scoped event loop"""
    policy = asyncio.get_event_loop_policy()
    loop = policy.new_event_loop()
    yield loop
    loop.close()
```

`asyncio.get_event_loop()` returns the running event loop or creates a new one if not exists, so it could be simplifed by:

```python
@pytest.fixture(scope="session")
def event_loop():
    loop = asyncio.get_event_loop()
    yield loop
    loop.close()
```

**Comment by ofer-pd** [comment]
2024-Oct:  New to async.  Encountered this error after adding the following to my root `confest.py`:

```python
@pytest.fixture( autouse=True, scope="session" )
async def test_database():
    ...  # code to create test DB
    yield
    ...  # code to delete test DB
```

It went away when I changed the decorator to:

```python
@pytest_asyncio.fixture( autouse=True, scope="session", loop_scope="session" )
```

Posting in case that's helpful to someone - or to be corrected if I'm doing this wrong.

**Comment by mzealey** [comment]
```
[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
```

in pyproject.toml fixes this now without any code changes.

**Comment by a9a4k** [comment]
I had a singleton postgres pool and had to mark all test to use loop session as described in [this article](https://pytest-asyncio.readthedocs.io/en/stable/how-to-guides/run_session_tests_in_same_loop.html)

**Comment by nicholas-leonard** [comment]
This is so confusing. Can someone make a simple guide already?

I have tried all the above snippets with no success. 

EDIT

Don't listen to any of the above. Check out these links:

- https://stackoverflow.com/a/79022712
- https://pytest-asyncio.readthedocs.io/en/latest/how-to-guides/migrate_from_0_23.html

Basically,
```
import pytest
import pytest_asyncio

@pytest_asyncio.fixture(loop_scope="session", scope="session")
[...fixture...]


@pytest.mark.asyncio(loop_scope="session")
[...test..]

```
