### ISSUE TITLE
Select_related not working

### ISSUE THREAD

**Issue by rossedwardsus** [tortoise/tortoise-orm#651]
Hello.  I don't know if this is a bug or if i am just not using the library correctly.  I am building a project management planning tool.  So each user has a project and each project has many tasks.  I am using this with FastApi

Here are the models:

class TortoiseUserProject(Model):
    project_id = fields.UUIDField(pk=True)
    user_id = fields.UUIDField()
    description = fields.CharField(max_length=100)
    tasks = fields.ForeignKeyField('models.TortoiseUserProjectTask', related_name='user_project_tasks', source_field='project_id')
    
    def __str__(self):
        pass

    class Meta:
        table="user_projects"

    class PydanticMeta:
        exclude = ["user_id", "created_datetime"]

class TortoiseUserProjectTask(Model):
    task_id = fields.UUIDField(pk=True)
    project_id = fields.UUIDField()
    user_id = fields.UUIDField()
    task_description = fields.CharField(max_length=50)
    start_date = fields.DatetimeField(auto_now_add=True)
    end_date = fields.DatetimeField(auto_now=True)
    progress = fields.CharField(max_length=50)
       
    def __str__(self):
        pass

    class Meta:
        table="user_project_tasks"

    class PydanticMeta:
        exclude = ["user_id"]

This is the query i am running against these models:
user_project = await TortoiseUserProject.get(
      project_id=project_id
  ).select_related('tasks')

Here is the sql that is produced:
SELECT "user_projects"."description","user_projects"."user_id","user_projects"."project_id","user_projects__tasks"."start_date" "user_projects__tasks.start_date","user_projects__tasks"."task_description" "user_projects__tasks.task_description","user_projects__tasks"."task_id" "user_projects__tasks.task_id","user_projects__tasks"."project_id" "user_projects__tasks.project_id","user_projects__tasks"."user_id" "user_projects__tasks.user_id","user_projects__tasks"."progress" "user_projects__tasks.progress","user_projects__tasks"."end_date" "user_projects__tasks.end_date" FROM "user_projects" LEFT OUTER JOIN "user_project_tasks" "user_projects__tasks" ON "user_projects__tasks"."task_id"="user_projects"."project_id" WHERE "user_projects"."project_id"='5ed82edc-574e-4af3-91df-92dd6ffb8bed' LIMIT 2

Why is it creating "user_projects__tasks"?  The name of the table is "user_project_tasks" which is defined in the table meta data for the tasks model.  So its getting the wrong table and returning empty data.

How do i go about fixing this?

Thanks.

**Comment by long2ice** [comment]
`select_related` is just for select one, you should use `prefetch_related`

**Comment by rossedwardsus** [comment]
That doesn't work either.  It just returns null.

Outputted sql, SELECT "description","user_id","project_id" FROM "user_projects" WHERE "project_id"='5ed82edc-574e-4af3-91df-92dd6ffb8bed' LIMIT 2

Json response, {"project":{"_partial":false,"description":"pd","user_id":"c4187e5e-50bb-4d4d-8c3b-dff470cb191e","tasks_id":null,"_tasks":null}

It doesn't seem like that even triggers at all.

Also even if it just selects one the sql query seemed wrong.

**Comment by rossedwardsus** [comment]
I believe i may have figured out the issue.  I followed the prefetching example on this screen, https://tortoise-orm.readthedocs.io/en/latest/examples/basic.html and it seems i had the definitions backwards.  When i made them mirror that example the prefetching seemed to work.  I am still not sure how the foreignkey works with respect to which it is connected to though.

Also is there a way to output the sql that is produced?
