### ISSUE TITLE
Foreign Key + source_field -> Error

### ISSUE THREAD

**Issue by MaxZayats** [tortoise/tortoise-orm#652]
**Describe the bug**
Have:
```python
class Questions(Model):
    id = fields.IntField(pk=True)
    text = fields.CharField(255)
    type = fields.ForeignKeyField(
        'models.QuestionsTypes',
        to_field='type',
        source_field='type_name' # <- set new column name
    )
    answer = fields.CharField(255)
    
class QuestionsTypes(Model):
    id = fields.IntField(pk=True)
    type = fields.CharField(255, unique=True)
    description = fields.TextField(default='')

    class Meta:
        table = 'questions_types'
```

**To Reproduce**
```python
await models.Questions.create(
    text='some text',
    type_name='default', # <- type_name is correct column name || 'default' contains in `QuestionsTypes`
    answer='some answer'
)
```

this code will raise the error:

```python
File "path_to_file", line 18, in start
    await models.Questions.create(
...
...
File "c:\users\max\appdata\local\programs\python\python38\lib\site-packages\tortoise\validators.py", line 43, in __call__
  raise ValidationError("Value must not be None")
  tortoise.exceptions.ValidationError: Value must not be None
```

but if i write the query like this:

```python
await models.Questions.create(
    text='some text',
    type_id='default', # <- The table hasn't a `type_id` column
    answer='some answer'
)
```

This code will not raise any errors and data will insert in Table

**This is a Bug ? Or my mistake ?**

**Comment by MaxZayats** [comment]
**Addition to the bug**

```python
await models.Questions.create(
    text='some text',
    type='default',
    answer='some answer'
)
```
This code will raise the error too:
```python
...
File "c:\users\max\appdata\local\programs\python\python38\lib\site-packages\tortoise\models.py", line 643, in __init__
  for key in meta.fields.difference(self._set_kwargs(kwargs)):
File "c:\users\max\appdata\local\programs\python\python38\lib\site-packages\tortoise\models.py", line 658, in _set_kwargs
  if value and not value._saved_in_db:
AttributeError: 'str' object has no attribute '_saved_in_db'
```

The column in the database is called `type_name`
![image](https://user-images.githubusercontent.com/49313691/109695828-70f33100-7b9d-11eb-9b69-bb733ccd754a.png)

**Comment by long2ice** [comment]
The `type` should be instance of QuestionsTypes, or `type_id` you tried before.

**Comment by MaxZayats** [comment]
Why I should write `type_id` ? If `type_id` not contains in table:
```python
await models.Questions.create(
    text='some text',
    type_id='default', # <- The table hasn't a `type_id` column
    answer='some answer'
)
```
If I set new column name: `source_field='type_name'`
I should write like this: `type_name='default'` not `type_id`
And this column has a str(varchar) type. It can't have a `_id` postfix

**Comment by long2ice** [comment]
The `type` is `ForeignKeyField`, which has a implicit field `*_id`

**Comment by MaxZayats** [comment]
But if I redefined the column name to `type_name` I still have to write `*_id`
Do you think that's right ?

**Comment by long2ice** [comment]
`source_field` provide a source_field name if the DB column name needs to be something specific instead of enerated off the field name, in python code you need use field name, in your case is `type`, so the right code is:
```py
    t = await QuestionsTypes.create(
        type='1'
    )
    await Questions.create(
        text='some text',
        type=t,
        answer='some answer'
    )
```
or
```py
    await Questions.create(
        text='some text',
        type_id='1',
        answer='some answer'
    )
```

**Comment by MaxZayats** [comment]
Ok, Thank You.
But I have one more question:
Why `.values()` returns a list of dicts? It would be better to return `namedtuple` with fields from the model.

**Comment by long2ice** [comment]
Current just have `value_list` and `values`

**Comment by MaxZayats** [comment]
Can we expect a namedtuple in the future ?

**Comment by long2ice** [comment]
No plan for that in the short term

**Comment by MaxZayats** [comment]
Why? It's much more convenient than a dict. You can see all the fields and explicitly access the fields with a dot: `.id`

**Comment by MaxZayats** [comment]
Sorry. I got the functions mixed up `.values()` and `.all()`
That's my mistake. Sorry
