### ISSUE TITLE
ValueError: cannot specify both default and default_factory

### ISSUE THREAD

**Issue by rossedwardsus** [tortoise/tortoise-orm#662]
Hello.  I am attempting to deploy a fastapi/tortoiseorm application to Digital Ocean App platform using docker and i am receiving that error.  Any ideas how to go about fixing it?

This line seems to throw the error:

User_Pydantic = pydantic_model_creator(TortoiseUser, name="User")

Thanks.

**Comment by mcdeoliveira** [comment]
I don't have a solution, but I remember having the same issue if an UUID field was used as primary key.

**Comment by rossedwardsus** [comment]
I am using UUID actually.

**Comment by long2ice** [comment]
see https://github.com/tortoise/tortoise-orm/issues/658

**Comment by rossedwardsus** [comment]
Sure. How am i supposed to apply that?

**Comment by long2ice** [comment]
Just install from latest dev branch, or wait next release

**Comment by rossedwardsus** [comment]
How do i do that via requirements.txt?  Or when will the next release be?

**Comment by long2ice** [comment]
see https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

**Comment by rossedwardsus** [comment]
So how would that look for this library on the dev branch?

**Comment by athanhat** [comment]
I have applied the patch by installing from the latest dev branch
`pip install git+https://github.com/tortoise/tortoise-orm`

But that is causing a dependency error for `aerich` in my requirements.txt

```txt
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aerich 0.5.0 requires tortoise-orm<0.17.0,>=0.16.21, but you have tortoise-orm 0.17.0 which is incompatible.
```

**Comment by rossedwardsus** [comment]
@athanhat  

You have to specify the branch name.

git+git://github.com/tortoise/tortoise-orm.git@develop#egg=tortoise-orm

**Comment by rossedwardsus** [comment]
Although your issue might be different than what i am inferring from your comment.

**Comment by athanhat** [comment]
Yes, thanks @rossedwardsus, you cannot avoid the dependency resolver ERROR if `aerich` Tortoise-ORM migrations tool is installed.

**Comment by rossedwardsus** [comment]
I just added aerich but i have not done a push and had to have the dependencies installed again.

So what is your solution?  To not use aerich and uninstall it?
