### ISSUE TITLE
Does aerich init -t settings.TORTOISE_ORM create a file?

### ISSUE THREAD

**Issue by rossedwardsus** [tortoise/tortoise-orm#663]
I am setting up migrations using aerich.  I am going through the documentation and ran that command but i don't see the file being created.  Also when i run aerich init-db.  It fails and says no config named settings?

I am wondering if that file is supposed to be manually created with this code added to it:

register_tortoise(
    app,
    db_url=DATABASE_URL,
    modules={"models": ["app.tortoise_models"]},
    generate_schemas=True,
    add_exception_handlers=True,
)

I currently have this in the main.py of the application.

Thank you.

**Comment by rossedwardsus** [comment]
Ok i see i missed the instruction about creating the settings file.  So i have done that now.  I created it at the root of my file.  In the documentation for aerich init-db, it says Success generate schema for app "models".  What does this mean?  I see an empty directory under the migrations folder called models but its empty.  Was something supposed to happen but didn't for some reason?  Also how do you run the initial database setup with all of the tables?

**Comment by long2ice** [comment]
No `settings.TORTOISE_ORM` is the tortoise config dictionary you set up before.

**Comment by rossedwardsus** [comment]
As i mention, i did set that up.  However what i ran aerich init-db nothing seem to happen?

**Comment by long2ice** [comment]
Could you show your config? And the file `aerich.ini`

**Comment by long2ice** [comment]
Looks no error

**Comment by rossedwardsus** [comment]
Sorry i don't understand what you mean.  When you run aerich init-db, was is supposed to happen?  Maybe something did happen but i missed it.  So i just want to make sure it is working correctly.

**Comment by long2ice** [comment]
`aerich init-db` will create all tables and show success log

**Comment by rossedwardsus** [comment]
My tables were already created beforehand so i didn't see the script did that.  Does the script use the classname to name the tables or the table name if its defined?

**Comment by bhch** [comment]
@rossedwardsus You also need to add `"aerich.models"` in the `models` list:

```python
"models": ["app.tortoise_models", "aerich.models"],
```

**Comment by saintlyzero** [comment]
> @rossedwardsus You also need to add `"aerich.models"` in the `models` list:
> 
> ```python
> "models": ["app.tortoise_models", "aerich.models"],
> ```

@rossedwardsus Did this work? If yes then please close the issue
