### ISSUE TITLE
`get_or_create` not working for sqlite/postgresql

### ISSUE THREAD

**Issue by ArtemBernatskyy** [tortoise/tortoise-orm#677]
**Describe the bug**
`user, _ = await User.get_or_create(id=ctx.author.id)` for sqlite/postgresql just awaits eternally, no user is created in database

**To Reproduce**
- can't create user via `User.get_or_create`
- code after `await` is never execute (aka awaited eternally)

**Expected behavior**
- user should be created

**Additional context**

    class User(Model):
        """User table"""

        id = fields.IntField(pk=True)
        balance = fields.data.DecimalField(max_digits=15, decimal_places=2, default=0)
        created_at = fields.DatetimeField(auto_now_add=True)
        modified_at = fields.DatetimeField(auto_now=True)

        def __str__(self):
            return f"#{self.id}"

**Comment by ArtemBernatskyy** [comment]
My bad, missed the logging statement

**Comment by Mindgate** [comment]
> My bad, missed the logging statement

Hi, Artem! Can you please describe what do you do to solve the issue? I have same problem, my code just hang on `get_or_create` call.

The issue happened after upgrading Tortoise to 0.17 and works fine with 0.16.21.

I tried this code:

```python
user = await User.filter(email=params.email).first()
if user is None:
    user = await User.create(email=params.email)
```

and it is works fine on both versions of Tortoise.reveal only with `get_or_create` and v.0.17

**Comment by ArtemBernatskyy** [comment]
Ah, let's reopen the issue,
I was using `0.17` and then installed `0.16.21` (after installing `aerich`),
there could be the problem with `0.17`

**Comment by shitangdama** [comment]
Hi,I had the same problem in pg.
`coin, created = await Coinkline.get_or_create(symbol=symbol, name=symbol[0:-4], time_id=item.id, period=interval)`
`DEBUG:db_client:SELECT "count","id","period","close","vol","time_id","symbol","name","open","low","high" FROM "coin_kline" WHERE "symbol"='ethusdt' AND "name"='eth' AND "time_id"=1616696400 AND "period"='5min' LIMIT 1: None
DEBUG:db_client:INSERT INTO "coin_kline" ("symbol","name","period","time_id","count","open","close","high","low","vol") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING "id": ['ethusdt', 'eth', '5min', 1616696400, 0, 0.0, 0.0, 0.0, 0.0, 0.0]
DEBUG:db_client:SELECT "count","id","period","close","vol","time_id","symbol","name","open","low","high" FROM "coin_kline" WHERE "symbol"='ethusdt' AND "name"='eth' AND "time_id"=1616696400 AND "period"='5min' LIMIT 2: None
ERROR:apscheduler.executors.default:Job "kline_job (trigger: cron[minute='*/1'], next run at: 2021-03-26 02:23:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\dev\haki\job.py", line 16, in kline_job
    coin, created = await Coinkline.get_or_create(symbol=symbol, name=symbol[0:-4], time_id=item.id, period=interval)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tortoise\models.py", line 1030, in get_or_create
    return await cls.get(**kwargs), False
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tortoise\queryset.py", line 848, in _execute
    raise DoesNotExist("Object does not exist")
tortoise.exceptions.DoesNotExist: Object does not exist`

**Comment by long2ice** [comment]
related https://github.com/tortoise/tortoise-orm/issues/678

**Comment by long2ice** [comment]
Fixed
