### ISSUE TITLE
Make QuerySet .delete() return a success indicator or counter

### ISSUE THREAD

**Issue by theblackturtle** [tortoise/tortoise-orm#68]
Hi, I want to check does the delete action is success, the `filter().delete()` response `NoneType`. Thanks.

**Comment by grigi** [comment]
Hi, you want to find out if `.delete()` returns any data?
No, it does not.

Is there some data you would need?

**Comment by sieunhando** [comment]
No, I mean if we use `.delete(), if the `.delete()` is success, it will return something like `id` or `success` message.

**Comment by grigi** [comment]
It is a good suggestion. Right now it only ever returns `None`, but returning a success/count would be better.
It doesn't make sense to return the deleted objects, as they now longer exist.

**Comment by grigi** [comment]
Hi, I released v0.15.7, please test if this issue is resolved :-)

**Comment by g3tl0st** [comment]
Is there a way to return ***Model Object*** instead of ***id***???
