### ISSUE TITLE
Not defining pk field ID when creating a record with .save()

### ISSUE THREAD

**Issue by amalkhamidov** [tortoise/tortoise-orm#681]
**Describe the bug**
I'm trying to create a new entry in the Tournaments table (for example) where `pk=True` is set, so the ID for that table is generated automatically in the Tortoise ORM.

```python
class Tournament(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
```

There are two ways to create a new record:
1. Method `.create(**kwargs)` where we specify fields for the record
2. A method to create a model object and then call `.save()`

And my task is to specify arbitrary ID
In the first method with `.create()` this is done correctly.

In the second way, Tortoise ignores the ID already set and inserts the generated

**To Reproduce**
```python
import asyncio
from pprint import pprint

from app.models.test import Tournament
from app.services.db import db_initialization


async def test():
    await db_initialization()
    await Tournament.filter().delete()

    first_tournament = Tournament()
    first_tournament.id = 2000
    first_tournament.name = "First One"
    await first_tournament.save()

    second_t = await Tournament.create(id=1337, name="Second one")
    pprint(first_tournament.__dict__)
    pprint(second_t.__dict__)


asyncio.run(test())
```

**Expected behavior**
We end up with two created entries:
The first will have ID == `4` (for example)
And the second one == `1337`

```json
{
    "_custom_generated_pk": true,
    "_partial": false,
    "_saved_in_db": true,
    "id": 4,
    "name": "First One"
}
{
    "_custom_generated_pk": true,
    "_partial": false,
    "_saved_in_db": true,
    "id": 1337,
    "name": "Second one"
}
```

**Additional context**
```python
first_tournament = Tournament(id=1)
first_tournament.id = 2000
first_tournament.name = "First One"
await first_tournament.save()
```
Interestingly, if we specify an arbitrary ID in the model object, the model will be created with the following ID (`2000`)

**Comment by long2ice** [comment]
Just use `await model.save(force_create=True)`

**Comment by amalkhamidov** [comment]
Thanks
