### ISSUE TITLE
In the data landing scenario, are there any good suggestions for combining with pandas?

### ISSUE THREAD

**Issue by lateautumn4lin** [tortoise/tortoise-orm#690]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by long2ice** [comment]
Just use `queryset.values` and `from_records`

**Comment by lateautumn4lin** [comment]
> Just use `queryset.values` and `from_records`

Thanks, I also use this now, but I also look forward to the official parameters
