### ISSUE TITLE
refresh_from_db raise AttributeError on ReverseRelation field

### ISSUE THREAD

**Issue by Mindgate** [tortoise/tortoise-orm#691]
**Describe the bug**
`Model.refresh_from_db` raises an `AttributeError: can't set attribute` on model that has a `ReverseRelation` field

**To Reproduce**
```python
class Company(Model):
    name = fields.CharField(255)
    users: fields.ReverseRelation['User']

class User(Model):
    company = fields.ForeignKeyField('models.Company', related_name='users')

async def run():
    company = await Company.create(name='test')
    await company.refresh_from_db()
```

**Expected behavior**
Code must run without raising the exception

**Additional context**
Issue does not exist if you exclude the field from call:
```python
await company.refresh_from_db(fields=['id', 'name'])
```

I have tried search in docs and issues for some hints if i use this method wrong, but failed.

**Comment by long2ice** [comment]
Maybe should exclude related fields default

**Comment by myusko** [comment]
@long2ice I can take a look at it.
