### ISSUE TITLE
Graphene Integration

### ISSUE THREAD

**Issue by ibrag8998** [tortoise/tortoise-orm#696]
In django, you just use `graphene_django.DjangoObjectType`, say what model you want to use as object type and that's all. Here is the example from [graphene docs](https://docs.graphene-python.org/projects/django/en/latest/queries/):

```python
class QuestionType(DjangoObjectType):
    class Meta:
        model = Question
        fields = ("id", "question_text")
```

What about doing something similar for tortoise models?

I would like the solution to be as similar to django as possible.

**Comment by long2ice** [comment]
A extention project instead of builtin support is better
