### ISSUE TITLE
Type annotation on QuerySetSingle

### ISSUE THREAD

**Issue by marcoaaguiar** [tortoise/tortoise-orm#701]
**Describe the bug**
When I try to use after a `Model.get(...).prefetch_related(...)` PyRight complains about not resolving the `MODEL` TypeVar.

Looking into the source code, I noticed that [QuerySetSingle](https://github.com/tortoise/tortoise-orm/blob/ea3a6f36e36add39800afce34ff154b74b2978c1/tortoise/queryset.py#L57) is annotated with both `T_co = TypeVar("T_co", covariant=True)` and `MODEL = TypeVar("MODEL", bound="Model")`.

It seems that the `MODEL` is not bound to any type in the annotations of a few methods (prefetch_related, annotate, only, ...).

Either changing all to `MODEL` or `T_co` seems to fix PyRight complaints.

**Comment by lovetoburnswhen** [comment]
I'm getting the same with PyRight for `host: ForeignKeyRelation["Host"]  = ForeignKeyField(models.Host)`
