### ISSUE TITLE
update_or_create not lock selected row

### ISSUE THREAD

**Issue by Ed-XCF** [tortoise/tortoise-orm#702]
django's update_or_create work with "select_for_update", but tortoise's update_or_create not lock selected row, why ?

**Comment by long2ice** [comment]
Could you give a link about that? Maybe we should update.

**Comment by Ed-XCF** [comment]
> Could you give a link about that? Maybe we should update.

https://github.com/django/django/blob/main/django/db/models/query.py#L606

**Comment by long2ice** [comment]
Thanks!

**Comment by long2ice** [comment]
Added
