### ISSUE TITLE
"update_or_create" never raise "MultipleObjectsReturned" exception

### ISSUE THREAD

**Issue by Ed-XCF** [tortoise/tortoise-orm#707]
in django, we will received an "MultipleObjectsReturned" exception when multiple rows exists, but tortoise not raise "MultipleObjectsReturned" because of tortoise use ".first()" not ".get()"

in tortoise:
https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/models.py#L1056

in django:
https://github.com/django/django/blob/main/django/db/models/query.py#L608
https://github.com/django/django/blob/3ae4344bbd3b5e8bcb039bf701f53b68b317f57b/django/db/models/query.py#L581

**Comment by long2ice** [comment]
Yes

**Comment by Ed-XCF** [comment]
This will cause users not realizing that they are using the wrong query conditions

**Comment by long2ice** [comment]
Sorry, I check the code again, tortoise will raise `MultipleObjectsReturned` in `get()`, `first()`,`get_or_none()` when more than one record, see https://github.com/tortoise/tortoise-orm/blob/825278341e38aa42eb23aa65ab9ab7797600d015/tortoise/queryset.py#L885

**Comment by long2ice** [comment]
So what about replace `first` to `get_or_none`?

**Comment by Ed-XCF** [comment]
maybe `get` is better. In fact, difference between `get` and `get_or_none` is the same as difference between `try...except` and `if...else`

**Comment by long2ice** [comment]
But we don't want it raise `DoesNotExist` but create new one, right?

**Comment by Ed-XCF** [comment]
Yes
