### ISSUE TITLE
JSONField not support string ?

### ISSUE THREAD

**Issue by Ed-XCF** [tortoise/tortoise-orm#718]
tortoise.exceptions.FieldError: Value wow is invalid json value.

**Comment by long2ice** [comment]
Yes

**Comment by Ed-XCF** [comment]
will fix it?

**Comment by long2ice** [comment]
Why fix?

**Comment by Ed-XCF** [comment]
https://en.wikipedia.org/wiki/JSON#Data_types
if JSONField is not support JSON standard then it is not JSONField

**Comment by long2ice** [comment]
That is json value data type, valid json should be `{...}` and `[...]`

**Comment by Ed-XCF** [comment]
JSON is not only `{...}` and `[...]`

**Comment by long2ice** [comment]
So funny, can your see https://www.json.org/json-en.html and understand it?

**Comment by Ed-XCF** [comment]
funny, can you read the doc first?
`A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. A character is represented as a single character string. A string is very much like a C or Java string.`

**Comment by long2ice** [comment]
You never understant it

**Comment by Ed-XCF** [comment]
you can try to run `JSON.stringify("wow")` in your Chrome

**Comment by long2ice** [comment]
Close with meaningless

**Comment by Ed-XCF** [comment]
you can try to run `JSON.stringify("wow")` in your Chrome

**Comment by Ed-XCF** [comment]
or `json.dumps("wow")` in python

**Comment by long2ice** [comment]
I don't want talk about that, if you think it is then it is.
