### ISSUE TITLE
[Feature Request] Healthcheck

### ISSUE THREAD

**Issue by lqmanh** [tortoise/tortoise-orm#720]
As the title says, I believe it's useful to have some kind of mechanism to check the availability of the connected database(s).
I've skimmed through the docs but couldn't find anything useful.

Could you please consider this feature, or in case it's simple enough, maybe a short snippet?
Thank you!

**Comment by long2ice** [comment]
What's the specific scene?

**Comment by lqmanh** [comment]
I just want to implement a feature that's like a simple version of https://www.githubstatus.com, which basically reports the status of connected databases, services,...

**Comment by long2ice** [comment]
Maybe that's not tortoise should do

**Comment by lqmanh** [comment]
You seem to misunderstand me. What I want, in the scope of an ORM, is to test the responsiveness of the database connections.

P/s: I somehow managed to find this dummy query `SELECT 1` some people use to achieve that. So nevermind.
