### ISSUE TITLE
Is there any way to add row numbers?

### ISSUE THREAD

**Issue by Wiper-R** [tortoise/tortoise-orm#723]
I am just wondering if tortoise orm can provide us a way to add row_number `ROW_NUMBER`.

**Comment by long2ice** [comment]
Which db?

**Comment by Wiper-R** [comment]
> Which db?

postgresql

**Comment by long2ice** [comment]
see https://tortoise-orm.readthedocs.io/en/latest/functions.html#custom-functions

**Comment by FIRDOUS-BHAT** [comment]
Couldn't find how to find the ROW_NUMBER by your provided link.
