### ISSUE TITLE
Add ability to use the field instead of it's name

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/tortoise-orm#725]
**Is your feature request related to a problem? Please describe.**
On updating some fields I often use option `update_fields` with `.save()` method.
Every time I need to manually enter the name of the field. 
E.g.:
```python
class User(Model):
    id = BigIntField(pk=True)
    nickname = CharField(max_length=255, null=True)

user = await User.get(id=12345)
user.nickname = "Some nickname"
await user.save(update_fields=["nickname"])
```

**Describe the solution you'd like**
To prevent typos I'd like to use it like this:
```python
user.nickname = "Some nickname"
await user.save(update_fields=[User.nickname])
```

Now it's answers with `AttributeError: type object 'User' has no attribute 'nickname'`

**Comment by long2ice** [comment]
No for that
