### ISSUE TITLE
tortoise.exceptions.OperationalError: (1052, "Column 'updated_at' in field list is ambiguous")

### ISSUE THREAD

**Issue by hu0514** [tortoise/tortoise-orm#728]
my sql:
 await table1.annotate(treat_time=F('updated_at')-F('created_at')).values('treat_time', 'member__name')

Check this error with two tables
tortoise.exceptions.OperationalError: (1052, "Column 'updated_at' in field list is ambiguous")

How do i modify this

**Comment by long2ice** [comment]
Could you show full model?

**Comment by hu0514** [comment]
class BaseModel(SerializableModel):
    id = fields.IntField(pk=True)
    created_at = fields.BigIntField(default=now, index=True, description='创建时间')
    updated_at = fields.BigIntField(null=True, description='更新时间')

class Feedback(BaseModel):

    class Meta:
        table =' feedback'
        app = __app__

    member = fields.ForeignKeyField('Member', related_name='feed_backs', null=True, index=True, db_constraint=False, source_field='uid', description='关联用户')

class Member(BaseModel):

    class Meta:
        table = 'member'
        app = __app__

    name = fields.CharField(64, unique=True, description='用户名')

This is related table data

**Comment by hu0514** [comment]
I have solved it
Add the get_table_name method to the table
class Feedback(Basemodel):
class Meta:
    table =' feedback'
    app = __app__
    @classmethod
    def get_table_name(cls):
        return cls.Meta.table

The sql statement is modified to this
rows = await Feedback.annotate(
        treat_time=F('updated_at', table=Feedback) - F('created_at', table=Feedback))

But it feels unreasonable. It should be the default table. Why do you have to specify it manually?

**Comment by long2ice** [comment]
try `await table1.annotate(treat_time=F('member__updated_at')-F('member__created_at')).values('treat_time', 'member__name')`

**Comment by hu0514** [comment]
I don’t want member’s created_at but kantai’s created_at
