### ISSUE TITLE
pydantic_model_creator datetime pydantic

### ISSUE THREAD

**Issue by panla** [tortoise/tortoise-orm#732]
### question

```python
class Order(Model):
    created_at = fields.DatetimeField(auto_now_add=True, null=False)
    updated_at = fields.DatetimeField(auto_now=True, null=False)

    @property
    def created_at_(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S')

OrderModelCreator = pydantic_model_creator(Order)
```

how to get created_at_ in OrderModelCreator or get created_at_ in pydantic Model or get property in pydantic_model_creator or pydantic Model

the aim is 

```json
{
  "created_at": "2021-04-21 14:53:13.43"
}
```

 not 

```json
{
  "created_at": "2021-04-21T14:53:13.439480+08:00"
}
```

**Comment by long2ice** [comment]
see https://tortoise-orm.readthedocs.io/en/latest/contrib/pydantic.html#pydanticmeta-callables

**Comment by panla** [comment]
thanks 

在整个异步生态方面还是有不少不方便的地方

1，Django Model 有 类似于 set value 和 get value 的比较底层的方法，不知道 tortoise-orm 有没有实现？
2，tortoise-orm 的 PydanticMeta 的 computed 应该还没有支持 async function
3，PydanticMeta 如果能够动态设置就很方便了(可能在接口a中想要某个属性，在接口b中又不想这个属性，想要另一个属性)

上面三个应该归于 属性(方法)/异步属性(方法)的问题，和pydantic关系比较大

**Comment by panla** [comment]
close
