### ISSUE TITLE
tortoise generates DELETE query with ORDER BY. And that throws Exception

### ISSUE THREAD

**Issue by acalcagno** [tortoise/tortoise-orm#739]
Hello all! I have started using this tool, which I think is great!
Last week I've arrived to an issue that I don't know how to workaround. If anyone could help me, it would be great!
Thanks in advance:

**Describe the bug**
I get an *OperationalError* when trying to remove all objects from database: 

when I try to run this python code:
`await Program..all().delete()`

where my Program class is something like:

```
class Program(Model):
    id = fields.UUIDField(pk=True, default=uuid.uuid4, editable=False)
    name = fields.CharField(max_length=64, blank=False, unique=True)
    description = fields.CharField(max_length=256, blank=False)
    ...
    class Meta:
        ordering = ("name",)
        table = "table_program"

```

This is the SQL sentence that it is trying to execute
`db_client    DEBUG    DELETE FROM "table_program" ORDER BY "name" ASC: None`

It throws this exception

```
/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/aiosqlite/core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: ORDER BY without LIMIT on DELETE
```

IMHO it doesn't make sense to try to ORDER BY any DELETE Instruction.
Any clue?

Thanks!

**Comment by long2ice** [comment]
Fixed in https://github.com/tortoise/tortoise-orm/pull/754
