### ISSUE TITLE
HELP - Return data from foreignkey with FastAPI and Tortoise

### ISSUE THREAD

**Issue by diegocgaona** [tortoise/tortoise-orm#746]
Hi,

I'm  trying it for some days, and can't do it myself (sorry for coming here for help).

I have some models, one is from FastAPI-Users: (this is the Tortoise model)
```
class UserModel(TortoiseBaseUserModel):
    items: fields.ReverseRelation["Item"]
```

And this is my created model:

```
class Item(tmodels.Model):
    """
    The Item model
    """
    id = fields.IntField(pk=True)
    title = fields.CharField(max_length=30, unique=True)
    description = fields.CharField(max_length=150, null=True)
    # owner = fields.ForeignKeyField("models.UserModel", related_name='owner')
    owner: fields.ForeignKeyRelation[UserModel] = fields.ForeignKeyField(
        "models.UserModel", related_name="items")
```

What I want get all users and all the items owned by then, like this:
```
{
                "email": "user@email.com",
                "id": "b8a3a2f7-ae27-4621-944a-3a658fa6869c",
                "is_active": True,
                "items": [{
                    "title": "Foo",
                    "description": "A very nice Item",
                    "id": 1,
                   "owner_id": "05c80783-7cd8-4a89-838f-b5f58cbe9f13"
            }]
            }
        }
```

With SQLAlchemy (from FastAPI tutorials) I did it this way:

```
# Create the table on the DB, inherit from Base (from database.py)
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
    is_superuser = Column(Boolean(), default=False)
    scope = Column(String, default="me")
    # attribute that will contain the values from other tables related to this one.
    items = relationship("Item", back_populates="owner")


class Item(Base):
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"))  # To determine which items are owned by a user.
    # "link" the tables, back_populates the items to their owners.
    owner = relationship("User", back_populates="items")
```

The problem is, with Tortoise I tried in many ways (I'm learning Python, I'm not a professional) and can't do it.
The response come like this:
```
{
                "email": "user@email.com",
                "id": "b8a3a2f7-ae27-4621-944a-3a658fa6869c",
                "is_active": True,
                "items": []
            }
        }
```

My route is like this:
```
# Get all items from the user
@router.get("/users/", response_model=List[schemas.UserPydantic])
async def read_all_user_items()):
    return await Users.all()
```

My schemas are created with Pydantic direct, because I need more flexibility in my responses and in other cases are working fine.

Thanks in advance!

**Comment by marcoaaguiar** [comment]
Hi Diego, make sure to init your models before creating the schemas.

For instance;
```python
Tortoise.init_models(["__main__"], "models")
# Now lets try again
UserPydantic = pydantic_model_creator(User)
```
This creates a Pydantic model that is aware of the User's relations.
Replace `__main__` with the module containing your models if it is not the file you are running (eg: `app.models`).

UserPydantic created by tortoise can _automatically_ fetch all the relations that it needs, if you its functions:
```python
# Get all items from the user
@router.get("/users", response_model=List[schemas.UserPydantic])
async def read_all_user_items()):
    return UserPydantic.from_queryset(Users.all())
```

You can find more about it in the [documentation about Pydantic](https://tortoise-orm.readthedocs.io/en/latest/contrib/pydantic.html#relations-early-init)

**Comment by diegocgaona** [comment]
I was using `Tortoise.init_models(["__main__"], "models")` , but I had put my  in the wrong place and it is not constructing the relationship.

And in some cases I was not using the schema created by `pydantic_model_creator()`, but it is needed to the relationship. I was using some schemas I made directly with Pydantic.

For reference to somebody working with FastAPI, one useful thing to not need to create Pydantic schemas/models is exclude fields in `pydantic_model_creator()` and not only in the Tortoise model, this way you can create different schemas for your response based on the same Tortoise model:
`User_Pydantic = pydantic_model_creator(UserModel, name="UserModel", exclude=("email", "hashed_password"))`

In the examples, I found only the cases  excluding from the Tortoise model like this:
```
class PydanticMeta:
     exclude = ["id"]
```

I found it is useful to print the schema and see if the relationship is there:
print(UserPydantic.schema())

The relation ship is show like:
`{'$ref': '#/definitions/database.models.Item.leaf'}}}`


Muito obrigado/Thanks @marcoaaguiar!!

**Comment by marcoaaguiar** [comment]
You can actually use
```
User_Pydantic = pydantic_model_creator(UserModel, name="UserModel", exclude=("email", "hashed_password"))
```
to exclude fields.

If you are creating multiple Pydantic models, just make sure to give a different name to your models (`name="UserModelIn"` for instance).

Also if you are making your own pydantic models, you can use PydanticModel (tortoise.contrib.pydantic) instead of BaseModel. Which have those extra functions.

**Comment by diegocgaona** [comment]
Thanks, the `PydanticModel (tortoise.contrib.pydantic)` is very useful and I didn't have idea!!

**Comment by marcoaaguiar** [comment]
BTW, if you are using Tortoise + Fastapi, this might be useful: https://github.com/awtkns/fastapi-crudrouter

**Comment by diegocgaona** [comment]
@marcoaaguiar , sorry to bother you, but maybe you know the answer, and it is simple to you, if not, no problem, don't need to answer.

I'm still learning and in an example very similar to the above. I was using the foreign key and the relations worked fine (thanks to you). But now I want some change (an improvement). I want each user to have their items, and after logged and access the endpoint (`@router.get("/me/onlyitems/", response_model=List[schemas.Card_Pydantic])`), it receives only their items.

It was working fine, I receive only the user items (using owner_id), but my item table uses an external unique ID (the item is a city and each city have an unique ID) and it is the primary key.
But, when another user try to add the same city, it gives an error because it cannot have the same city in the table, even with another owner. Well, it is how should be... but I want to have other users accessing the same cities (they have the same info, they are not customized).
Then, I want many users having access to the same item (and each user can access multiple items).

I don't think it is ideal to repeat the item info (using another ID) for each user, would be better different user access the same item.

I think it would be a Many To Many relation, but I don't know how to make the relationship and get it with FastAPI.

Well, let me show some code:

models.py
```
class UserModel(TortoiseBaseUserModel):
    cards: fields.ReverseRelation["Card"]


class OAuthAccountModel(TortoiseBaseOAuthAccountModel):
    user = fields.ForeignKeyField("models.UserModel", related_name="oauth_accounts")


class User(models.BaseUser, models.BaseOAuthAccountMixin):
    pass


class UserCreate(models.BaseUserCreate):
    pass


class UserUpdate(User, models.BaseUserUpdate):
    pass


class UserDB(User, models.BaseUserDB, PydanticModel):
    class Config:
        orm_mode = True
        orig_model = UserModel


user_db = TortoiseUserDatabase(UserDB, UserModel, OAuthAccountModel)


class Card(tmodels.Model):
    """
    The Card model, related to the user.
    """
    id = fields.IntField(pk=True)
    city_name = fields.CharField(max_length=30)
    temperature = fields.FloatField()
    state = fields.CharField(max_length=30, null=True)
    icon = fields.CharField(max_length=3, null=True)
    period = fields.CharField(max_length=20, null=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)
    owner: fields.ForeignKeyRelation[UserModel] = fields.ForeignKeyField(
        "models.UserModel", related_name="cards")

    class PydanticMeta:
        exclude = ["owner"]
```

I tried to change my owner field and the their relationship to UserModel:

```
class Card(tmodels.Model):
owner = fields.ManyToManyField("models.UserModel", related_name="cards")
```

```
class UserModel(TortoiseBaseUserModel):
    cards: fields.ManyToManyRelation["Card"]
```

I don't know if it is right, I couldn't make it works, but the problem could be in other places.

My endpoint for the user create a item:
```
@router.post("/", response_model=Card_Pydantic)
async def create_item_for_current_user(
        card: CardCreate, user: UserDB = Depends(fastapi_users.get_current_active_user)):
    card_obj = await crud.create_user_card(card=card, user=user)
    if card_obj is None:
        raise HTTPException(status_code=404, detail=f"City '{card.city_name}' not found")
    return await card_obj
```

The CRUD function used (to create an item) here:
```
async def create_user_card(
        card: schemas.CardCreate, user: UserDB = Depends(fastapi_users.get_current_active_user)):
    card_json = await weather_api.get_api_info_by_name(card.city_name)
    if card_json is None:
        return None
    card_obj = await Card.create(**card_json,
                                 owner_id=user.id)  # ** is used to pass the keys values as kwargs.
    return await card_obj
```

My endpoint to get the items owned by the user:
```
@router.get("/me/onlyitems/", response_model=List[schemas.Card_Pydantic])
async def read_current_user_items(user: UserDB = Depends(fastapi_users.get_current_active_user)):
    user_cards = await schemas.Card_Pydantic.from_queryset(Card.filter(owner_id=user.id).all())
    return await crud.update_only_card_for(user_cards, user.id)
```

My crud function is:

```
async def update_only_card_for(user_cards, owner_id):
    for city in user_cards:
        await update_card(city.id, owner_id)
    return await schemas.Card_Pydantic.from_queryset(Card.filter(owner_id=owner_id).all())

# The update function (it will check if it need to update or not)
async def update_card(city_id: int, owner_id: UUID = UserDB):
    card_obj = await Card.get(id=city_id)
    card_time = card_obj.updated_at
    timezone = card_time.tzinfo
    now = datetime.now(timezone)
    time_to_update = now - timedelta(minutes=15)

    if card_time < time_to_update:
        card_json = await weather_api.get_api_info_by_id(city_id)
        await card_obj.update_from_dict(card_json).save()  # with save will update the update_at field
    card_updated = await schemas.Card_Pydantic.from_queryset_single(Card.get(id=city_id))
    return card_updated
```

How I could change it to get the cards the user need to had access? I think I can't use the filter by owner_id... but can't think how to make the relation to link the user to the items he added and at same time, other users access the same items.

This code works fine (I'm using a nuxt.js front end), until there is a duplicated city...

**Comment by diegocgaona** [comment]
I solved it. I found how to create the relationships and retrieve the data.

The models: (simplified version)

```
class Card(tmodels.Model):
    id = fields.IntField(pk=True)
    city_name = fields.CharField(max_length=30)
    owners: fields.ManyToManyRelation["UserModel"] = fields.ManyToManyField(
        "models.UserModel", related_name="cards", through="card_usermodel")

class UserModel(TortoiseBaseUserModel):
    cards: fields.ManyToManyRelation[Card]
```
`through="card_usermodel"` will create an intermediary table with the Card id and the owner id, it will define the relationship.

To make the data operations:

```
async def create_user_card(
        card: schemas.CardCreate, user: UserDB = Depends(fastapi_users.get_current_active_user)):
    card_json = await weather_api.get_api_info_by_name(card.city_name)
    if card_json is None:
        return None
    owner = await UserModel.get_or_none(id=user.id)
    card_obj = await Card.update_or_create(**card_json)
    await card_obj[0].owners.add(owner)
    return await schemas.Card_Response_Pydantic.from_queryset_single(Card.get(id=card_json.get("id"), owners=user.id))
```
Basic is it. I changed some Pydantic models too, to validate the responses.
