### ISSUE TITLE
Adding multiple data in same field

### ISSUE THREAD

**Issue by sarzz2** [tortoise/tortoise-orm#763]
```py
class Order(Model):
    id = fields.IntField(pk=True)
    total_price = fields.FloatField()
    product: fields.ForeignKeyField(
        "models.Products", related_name="events"
    )
    address = fields.ForeignKeyField("models.Address")

    def __str__(self):
        return self.id


Tortoise.init_models(["app.models.orders"], "models")

Order_Pydantic = pydantic_model_creator(Order, name="Order")
OrderIn_Pydantic = pydantic_model_creator(Order, name="Order_In", exclude_readonly=True)
```
SO i have this model and i want multiple value in field products for eg
```json
{
product: [1,2,3],
address: 1
}
```
So the model order should be able to take multiple values for product field each relating to the product created in Products field

the endpoint Using fast api
```py
@router.post("/")
async def create_orders(order: OrderIn_Pydantic):
    obj = await Order.create(**order.dict(exclude_unset=True))
    return await OrderIn_Pydantic.from_tortoise_orm(obj)
   ```
I have tried using ManyToMany field referring from docs but for some reason that doesn't show up in pydantic_model_creator it's apparently a read only field.

**Comment by Wiper-R** [comment]
You might need, fields.ManyToManyField()

**Comment by sarzz2** [comment]
> You might need, fields.ManyToManyField()

Yes, i have tried that it the realtion doesnt get created when i do 
```py
product = fields.ManyToMany("models.Products")
```
i have done early init
