### ISSUE TITLE
Unable to use .create on non required relational fields.

### ISSUE THREAD

**Issue by Wiper-R** [tortoise/tortoise-orm#764]
I am trying to use `.create` method, on ForeignKeyRelation (Defaults to None). And it is raising a error
```
AttributeError: '_NoneAwaitable' object has no attribute 'create'
```

I could use `Model.create`, then update the parent model, But it looks a lot messier. Is their any other good way to do this?

**Comment by ZhymabekRoman** [comment]
Can u provide code example?

**Comment by Wiper-R** [comment]
> Can u provide code example?

Its been a year I forgot what I was talking about.

This issue can be closed now.
