### ISSUE TITLE
Is there any way to handle postgresql schemas?

### ISSUE THREAD

**Issue by Wiper-R** [tortoise/tortoise-orm#771]

**Comment by lsabi** [comment]
Can you be more explicit?

My guess is that you are looking for `A database migrations tool for TortoiseORM, ready to production.` 

See [https://github.com/tortoise/aerich](https://github.com/tortoise/aerich)

**Comment by long2ice** [comment]
Need more feedback

**Comment by Wiper-R** [comment]
> Need more feedback

As we can work with different databases, using `db_name.table` in asyncpg.. Is this possible with tortoise-orm?

**Comment by long2ice** [comment]
see https://tortoise-orm.readthedocs.io/en/latest/databases.html#postgresql, the optional parameters
