### ISSUE TITLE
db_index parameter?

### ISSUE THREAD

**Issue by monospacedmagic** [tortoise/tortoise-orm#78]
I miss the ability to mark fields as indexed. I don't know if this is a limitation of pypika. I need this feature to ensure that DB queries are decently fast. :)

**Comment by grigi** [comment]
I had a look at what would be required for this, and PyPika is not responsible for schema generation. Most of the work is in https://github.com/tortoise/tortoise-orm/blob/master/tortoise/backends/base/schema_generator.py and subclasses of it.

Do you want to have a go at it?

Add a index boolean to the base `Field` class, and then let the schema generator keep track of them and append indexes after generating the table.

**Comment by monospacedmagic** [comment]
If you want to do it, please do, I currently lack the time because of my current project's deadline. I'd be available for this in two weeks, possibly three. ^^'
