### ISSUE TITLE
pymysql.err.InternalError: Packet sequence number wrong - got X expected 1

### ISSUE THREAD

**Issue by osintegrator** [tortoise/tortoise-orm#784]
**Describe the bug**
I use aiohttp+tortoise-orm+mysql for simple API, which can only insert a row to a single mysql database table called "TableName" and read the rows from it. If my API is idle for some time, say, 3 hours, and I do API request which should return me table rows, it shows "pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1" (not necessarily 0, it could be other number) error and status 500 instead of returning rows.

It shows this error when run this piece of code:
`rows = await TableName.filter(some_field=some_field)`

**To Reproduce**
1. Create `models.py` file:
```
from tortoise import Model, fields


class TableName(Model):
    id = fields.IntField(pk=True)
    some_field = fields.CharField(250)
```

2. Create `main.py` file:
```
from aiohttp import web
from tortoise.contrib.aiohttp import register_tortoise

from models import TableName


async def list_rows(request):
    data = await request.json()
    try:
        some_field = data['some_field']
    except KeyError:
        return web.json_response({'message': f'Not all fields were specified'}, status=400)

    rows = await TableName.filter(some_field=some_field)

    rows_json = [row.__dict__ for row in rows]
    return web.json_response(rows_json)


app = web.Application()
app.add_routes([
    web.post("/rows", list_rows)
])

register_tortoise(
    app, db_url="mysql://user:password@mysql:3306/any-database-name", modules={"models": ["models"]},
    generate_schemas=True
)

if __name__ == "__main__":
    web.run_app(app, port=6000)
```

3. pack it into docker container with such Dockerfile:

```
FROM python:3.9.5
COPY requirements.txt . 
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "main.py"]
```
`docker build -t image-name:tag-name .`

4. Run API with command:

`docker run -d -p 6000:6000 image-name:tag-name`

5. After 3 hours of working, run curl query:

`curl -i -X POST --data '{"some_field": "blabla"}' http://localhost:6000/rows`

6. curl will return 500 error, inside container's logs you will see error:

```
pymysql.err.InternalError: Packet sequence number wrong - got 35 expected 1
```

**Expected behavior**
curl query should return json with rows' values in it.

**Additional context**
Full trace:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/mysql/client.py", line 44, in translate_exceptions_
    return await func(self, *args)
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/mysql/client.py", line 199, in execute_query
    await cursor.execute(query, values)
  File "/usr/local/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/aiomysql/connection.py", line 574, in _read_packet
    raise InternalError(
pymysql.err.InternalError: Packet sequence number wrong - got 0 expected 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "//main.py", line 37, in list_rowa
    rows = await TableName.filter(some_field=some_field)
  File "/usr/local/lib/python3.9/site-packages/tortoise/queryset.py", line 879, in _execute
    instance_list = await self._db.executor_class(
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/base/executor.py", line 124, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "/usr/local/lib/python3.9/site-packages/tortoise/backends/mysql/client.py", line 52, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: Packet sequence number wrong - got 0 expected 1
```

**Comment by long2ice** [comment]
Looks like problem of aiomysql

**Comment by Chise1** [comment]
It seems that this bug does not appear on Linux.

**Comment by ryanrain2016** [comment]
same problem. on linux(docker python:3.9-buster, docker: mysql 8.0.26)

**Comment by fainle** [comment]
same problem. on ubuntu 20.04 and mysql 8.0.26

**Comment by ryanrain2016** [comment]
> Looks like problem of aiomysql

the same problem met with your mysq driver asyncmy

**Comment by long2ice** [comment]
Can it be stabilized repetition?

**Comment by long2ice** [comment]
Maybe problem of protocol

**Comment by ryanrain2016** [comment]
After one day of reading the source code in aiomysql, pymysql, asyncmy and tortoise-orm,I've found the where the problem is.

**Comment by ryanrain2016** [comment]
> Can it be stabilized repetition?

yes

**Comment by long2ice** [comment]
Oh, that's good, could you make a pr?

**Comment by ryanrain2016** [comment]
mysql server will close the connection after a long idle time, default is 28800 seconds, that is 8 hours. aiomysql/asyncmy pool can recyle it by passing a `pool_recycle` parameter. Just config it(little than 28800) in `db_config['connections']['default']['credentials']`. that's ok. but It does't work with 'db_url', since pool_recycle will be str when passing though 'db_url'.
tortoise-orm document hidden a lot of paramenter to aiomysql/asyncmy pool.

**Comment by ryanrain2016** [comment]
aliternatively,config mysql a long recyle time:(eg one year)
```
[mysqld]
wait_timeout=31536000
interactive_timeout=31536000
```

**Comment by long2ice** [comment]
That's great, thanks for your share and solution!

**Comment by ryanrain2016** [comment]
客气，tortoise很棒

**Comment by fainle** [comment]
> 客气，tortoise很棒

这种配置 会不会一年以后还是会出现这个错误，以前我在flask的sqlalchemy上也遇到类似问题，但解决的方法是通过orm传递参数

**Comment by long2ice** [comment]
现在也可以通过配置传递

**Comment by fainle** [comment]
> 现在也可以通过配置传递

怎么操作的？

**Comment by long2ice** [comment]
credentials 里面设置 pool_recycle

**Comment by fainle** [comment]
> credentials 里面设置 pool_recycle

文档里面 没找到这个参数

**Comment by long2ice** [comment]
这属于驱动自定义参数，你直接透传就行

**Comment by fainle** [comment]
> 这属于驱动自定义参数，你直接透传就行

好的我试试

**Comment by ryanrain2016** [comment]
> 这属于驱动自定义参数，你直接透传就行

这个参数在处理回收的时候asyncmy不支持，貌似他的连接没有记录上次使用时间，上次用这个回收的时候会报last_usage属性不存在的错，aiohttp可以，不知道楼主有没有更新 @long2ice

**Comment by ryanrain2016** [comment]
```
        # pool.py: line 133
        elif self._recycle > -1 and self._loop.time() - conn.last_usage > self._recycle:
                self._free.pop()
                conn.close()
```

**Comment by long2ice** [comment]
你试试最新版本

**Comment by ryanrain2016** [comment]
> > 客气，tortoise很棒
> 
> 这种配置 会不会一年以后还是会出现这个错误，以前我在flask的sqlalchemy上也遇到类似问题，但解决的方法是通过orm传递参数

概率上可能会，这个连接池回收时，是比较的这个连接上次使用的时间，1年这个连接都没有使用过那就会发生，1年了连接池还没用个遍，那池子配置的太大了或者没必要用连接池了

**Comment by ryanrain2016** [comment]
> 你试试最新版本

这个ok， 棒

**Comment by long2ice** [comment]
嗯，这个issue先关了
