### ISSUE TITLE
BigIntField?

### ISSUE THREAD

**Issue by monospacedmagic** [tortoise/tortoise-orm#79]
It looks like there is no BigIntField. I need it because [Discord](https://discordapp.com) IDs have 19 digits and are thus too big for regular INTEGERs.

**Comment by grigi** [comment]
Yes, I wanted to do a round of completing the field types.
As a workaround you can use `DecimalField(20,0)` or `CharField(20)`?

**Comment by monospacedmagic** [comment]
I suppose I can. If possible I'd rather just submit a PR instead, though. Is there a chat for this project (Discord maybe?)? That would make it easier to communicate about this project. :)

**Comment by grigi** [comment]
Just released v0.11.2 and it should fix this issue :-)
