### ISSUE TITLE
Switch the databases using different binds

### ISSUE THREAD

**Issue by kaleming** [tortoise/tortoise-orm#795]
I am using fastapi, tortoise (with postgres) and keycloak (as IAM).

Currently I have multiple databases with identical Tables and Columns (but different data inside). Depending the users group, I need to get the data from the database which corresponds to this group.

Is there a way to switch the database keeping same query ? (using some argument like binds)

Example:

```
async def get_user(current_group: dict = Depends(get_user_group)):
    events = await team(bind='current_group').events.filter(name='First')
 
    return events

```

**Comment by long2ice** [comment]
What about `using_db`?

**Comment by kaleming** [comment]
My mistake, I didn't notice this parameter. I will try `using_db`.
Thank you very much @long2ice.
