### ISSUE TITLE
Tortoise orm not creating columns in postgres database in all tables

### ISSUE THREAD

**Issue by TierGamerpy** [tortoise/tortoise-orm#801]
Hi i am having a serious issue i have read all docs and searched for the solution but my code is correct, acctually what is happening i have mades models and when i am running my python file its creating those tables in database but its not creating some columns in most of the tables here is the code of my one of the table:
```py
class GuildData(models.Model):
    class Meta:
        table = "server_configs"
    guild_id = fields.BigIntField(pk=True)
    is_bot_setuped = fields.BooleanField(default=False)
    scrims_manager = fields.BooleanField(default=False)
    autorole_toggle = fields.BooleanField(default=False)
    autorole_bot_toggle = fields.BooleanField(default=False)
    autorole_human_toggle = fields.BooleanField(default=False)
    autorole_human = fields.BigIntField(null = True)
    autorole_bot = fields.BigIntField(null = True)
    automeme_toogle = fields.BooleanField(default=False) 
    automeme_channel_id = fields.BigIntField(null = True)
    is_guild_premium = fields.BooleanField(default = False)
```
and in this some of the columns are not getting created like i am naming the columns which have got created : `guild_id`,`scrims_manager`, `autorole_bot`, `autorole_human`, these columns are getting created but other columns dosen't get created here is the output logged bye toetoise logging:
```sql
CREATE TABLE IF NOT EXISTS "server_configs" (
    "guild_id" BIGSERIAL NOT NULL PRIMARY KEY,
    "scrims_manager" BOOL NOT NULL  DEFAULT False,
    "autorole_human" BIGINT,
    "autorole_bot" BIGINT
);
``` 
you can see that most of the tables are missing same thing is happening in other tables too here is image of table in `pg admin`
`https://cdn.discordapp.com/attachments/754690035319701545/856917612395102218/Screenshot_from_2021-06-22_20-54-04.png`.

Kindly solve the issue fast because i am getting late with my bots update because of this.

Thanks

**Comment by long2ice** [comment]
I tried but no problem, that's strange

**Comment by TierGamerpy** [comment]
> I tried but no problem, that's strange

I don't know why but it's happening with me only and with my freinds it's working fine.

**Comment by TierGamerpy** [comment]
please help what can be its solution

**Comment by long2ice** [comment]
What's the way you generate db?

**Comment by TierGamerpy** [comment]
> What's the way you generate db?

what? i did not get you?

**Comment by long2ice** [comment]
I mean did you use `Tortoise.init(generate_schemas=True)` or use aerich init-db?

**Comment by TierGamerpy** [comment]
> I mean did you use `Tortoise.init(generate_schemas=True)` or use aerich init-db?

i used this:
```py
async def init_db(self):
        self.session = aiohttp.ClientSession(loop=self.loop)
        await Tortoise.init(config.TORTOISE)
        await Tortoise.generate_schemas(safe=True)
```
and this function is called in a loop it will get close when my bot code closes or get off

**Comment by TierGamerpy** [comment]
should i try reinstalling orm and then running the code

**Comment by long2ice** [comment]
I'm not sure but you can try that

**Comment by TierGamerpy** [comment]
> I'm not sure but you can try that

ok let me try if it works then fine of not then i will tell here

**Comment by TierGamerpy** [comment]
i tried it but this time it created some more cloumns in comparison of previous columns but still some of the columns are missing.
why this thing is happening with me only

**Comment by long2ice** [comment]
I'm also wondering for that

**Comment by TierGamerpy** [comment]
> I'm also wondering for that

you are developer of tortoise-orm ?

**Comment by TierGamerpy** [comment]
did you find the solution

**Comment by TierGamerpy** [comment]
i have got the solution the problem was from my side only what i was doing i was making same function in class with the name of variable in that class and this thing my friend told me to not keep it same and the issue got solved

**Comment by TierGamerpy** [comment]
thanks for your time

**Comment by long2ice** [comment]
Glad to hear that

**Comment by long2ice** [comment]
Glad to hear that
