### ISSUE TITLE
Naming primary key field as pk breaks model creation

### ISSUE THREAD

**Issue by sasha00123** [tortoise/tortoise-orm#803]
**Describe the bug**
Naming primary key field as pk breaks model creation

**To Reproduce**
```
class MyModel(Model):
    pk = fields.IntField(pk=True)


await MyModel.create()
```
**Expected behavior**
Creating an object

**Additional context**
RecursionError: maximum recursion depth exceeded

**Comment by long2ice** [comment]
dup of https://github.com/tortoise/tortoise-orm/issues/800

**Comment by WisdomPill** [comment]
Maybe it can be closed as it is a duplicate?
