### ISSUE TITLE
Unknown `in` filter parameter 

### ISSUE THREAD

**Issue by FIRDOUS-BHAT** [tortoise/tortoise-orm#804]
My query is like,
uid = ["1", "2"]
`lectures = await CourseCategoryLectures.filter(category_topic__in=uid)`

I'm getting error like,

`tortoise.exceptions.FieldError: Unknown filter param 'in'. Allowed base values are ...
`

I'm unable to understand about the possible reason for getting such error.

**Comment by long2ice** [comment]
So what's the full error? `category_topic` is fk?

**Comment by FIRDOUS-BHAT** [comment]
> So what's the full error? `category_topic` is fk?

Oh yes, that's a FK

**Comment by FIRDOUS-BHAT** [comment]
Resolved.
My mistake, 
As it's a FK so i was supposed to write like,
`lectures = await CourseCategoryLectures.filter(category_topic__id__in=uid)
`

**Comment by WisdomPill** [comment]
Can this be closed?
