### ISSUE TITLE
Automatically integrate new fields

### ISSUE THREAD

**Issue by monospacedmagic** [tortoise/tortoise-orm#83]
**Is your feature request related to a problem? Please describe.**
There's currently no way to automate the synchronisation of the database's structure with the Models except for when there are only entirely new Models that need to be synced (`Tortoise.generate_schemas(safe=True)`).

**Describe the solution you'd like**
It would be nice if new fields that do **not** have `pk` set to `True` and have `default` set to something or `nullable` set to `True` could be integrated into the database as well when `Tortoise.generate_schemas` is called with `safe=True` as this is a safe operation as far as I'm aware.

**Describe alternatives you've considered**
Not having this feature makes it difficult to build highly modular applications/libraries such as the one I'm building. An alternative I have actually considered is to use Django's migration system for migrations, but that would be messy at best. Another alternative would be to port Django's migration system to tortoise so we have at least some migration system for now (it should be fine for the migration system to be sync I guess), but I don't really have the time to do that right now, unfortunately.

**Comment by abondar** [comment]
Hi

We are aware of issue regarding migrations, you could read discussion on it here #8 
Currently I am doing some work to implement basic migration system, but I don't have that much time right now, so I wouldn't expect it any time soon. 

I am closing this issue as duplicate for now, you can participate in discussion in main issue.
