### ISSUE TITLE
Question: how to reconnect to database?

### ISSUE THREAD

**Issue by dadyarri** [tortoise/tortoise-orm#835]
**Describe the bug**
`tortoise.run_async` automatically closes connection and `tortoise.transactions.in_transaction` doesn't open it again

**To Reproduce**
Function with `in_connection` calls after initialization of database with `run_async`. As result - getting error about non-existing connection (as I understood)
```python
File ..., line 14, in is_user
    async with in_transaction("default"):
  File "tortoise/backends/base/client.py", line 253, in __aenter__
    self.connection._connection = await self.connection._parent._pool.acquire()
AttributeError: 'NoneType' object has no attribute 'acquire'
```

**Additional context**
Python 3.9
Tortoise 0.17.5

**Comment by long2ice** [comment]
`run_async` is only meant for simple scripts, don't use that

**Comment by dadyarri** [comment]
Okay then, how to init connection and later use it not in simple scripts?

If i use `in_transaction` before `Tortoise.init` obviously there wouldn't any connections:
```python
  File "tortoise/transactions.py", line 21, in get_connection
    connection = transaction_map[connection_name].get()
KeyError: 'default'
```

And one more question: why the lib thinks i have more than one connection and require to specify connection's name but there is only one `Tortoise.init` with only one connection?
