### ISSUE TITLE
`.first()` does not apply, and updates all instead

### ISSUE THREAD

**Issue by TheoCoombes** [tortoise/tortoise-orm#836]
In my FastAPI app, the following code is ran:

```py
await Job.filter(pending=False, closed=False, gpu=True).order_by("number").first().update(completor=client.uuid, pending=True)
```
For some reason, this updates **all** the `Job` instances, instead of just the first one after ordering.

I've attempted replacing `.first()` with `.limit(1)` but it got the same results.

Is there a better way to do this, or is this an issue on the tortoise side of things?

p.s. it's important to mention the fact that this needs to do both filtering and updating at the same time, or there's a slight chance multiple people using the website may be given the same `Job`. Unless there's a way to call two methods at once with tortoise?

**Comment by panla** [comment]
### first

Unresolved attribute reference 'update' for class 'QuerySetSingle' 

### you also can

```python
job = await Job.filter(pending=False, closed=False, gpu=True).order_by("number").first()
job.completor = client.uuid
job.pending = True
await job.save()
```

**Comment by abondar** [comment]
Starting from 0.17.3 update query can be used with `.order_by` and `.limit` to apply them to limited set
using `.first` will not work
