### ISSUE TITLE
Error: You can't set m2m relations through init, use m2m_manager instead

### ISSUE THREAD

**Issue by diegocgaona** [tortoise/tortoise-orm#838]
**Describe the bug**
When I try to create a M2M relationship, I get the error:
`tortoise.exceptions.ConfigurationError: You can't set m2m relations through init, use m2m_manager instead`

I didn't found any reference in the documentation about "m2m_manager", in the [source code](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/models.py), I only found this same message, but it doesn't help me to understand how to solve it.

I'm  using the version 0.17.6 of Tortoise ORM.

**To Reproduce**
Basic I have two models (simplified here):

```
class Card(tmodels.Model):
    """
    The Card model, related to the user.
    """
    id = fields.IntField(pk=True)
    city_name = fields.CharField(max_length=30)
    owners: fields.ManyToManyRelation["UserModel"] = fields.ManyToManyField(
        "models.UserModel", related_name="cards", through="card_usermodel")

class UserModel(TortoiseBaseUserModel):
    # cards: fields.ReverseRelation[Card]  # Not certain if is the correct one
    cards: fields.ManyToManyRelation[Card]
```

And the operation I'm trying and give me the error is:
```
async def create_user_card(
        card: schemas.CardCreate, user: UserDB = Depends(fastapi_users.get_current_active_user)):   ​
   ​card_json = await weather_api.get_api_info_by_name(card.city_name)
   ​if card_json is None:
       ​return None
 ​owner = await UserModel.get_or_none(id=user.id)
   ​card_obj = await Card.create(**card_json, owners=owner)
  ​# card_obj = await Card(**card_json, usermodel_id=user.id, card_id=card_json.get('id')).save()
​ card_prefetch = Card.get_or_none(owners=owner).prefetch_related("owners")
   ​return card_obj
```
The error come from the line:
` ​card_obj = await Card.create(**card_json, owners=owner)`

**Expected behavior**
The creation of the M2M relation, with the owner_id and card_id on the table card_usermodel (which is blank).

**Additional context**
I'm using it with FastAPI, with FastAPI Users.
I'm  not certain about my model and operation, I tried to follow the examples in Tortoise documentation, but I didn't understood very well how to apply in my case. This function `create_user_card `is used in a POST endpoint.

To clarify, one user can have many cards and a card can have multiple owners (the data on the card is the same for all).

**Comment by long2ice** [comment]
try this:
```py
card_obj = await Card.create(**card_json)
await card_obj.owners.add(owner)
```

**Comment by diegocgaona** [comment]
Thanks!!!  Now the intermediary table have the data.

Maybe in the error, the message could be.
`tortoise.exceptions.ConfigurationError: You can't set m2m relations through init, use .add() instead`

Now I will try make the prefetch work.
