### ISSUE TITLE
How do I add functionality to all of my models without repeating myself?

### ISSUE THREAD

**Issue by monospacedmagic** [tortoise/tortoise-orm#85]
I want to add a `_d` attribute and a few `classmethod`s and some regular methods to models by creating a subclass of `tortoise.models.Model` that users of my framework can use. However, subclassing `Model` would create a new database model, which is not what I want. From what I've seen, the `Model` class contains a lot of logic, and it seems not feasible to create a new class with `metaclass=ModelMeta`. What are my options here? Am I missing something?

**Comment by abondar** [comment]
Hi

There is `abstract=True` option for models meta, it's mentioned there https://tortoise-orm.readthedocs.io/en/latest/models.html

Is it what are you looking for?

**Comment by monospacedmagic** [comment]
Ohhh! Thanks, I somehow completely skipped that. It's exactly what I was looking for. :)

**Comment by tcmal** [comment]
When using `abstract=True`, it seems like the child classes don't inherit fields, ie:

```
class Entity(Model):
    x = fields.IntField()
    y = fields.IntField()

class ChestEntity(Entity, Model):
    level = fields.IntField()
    opened = fields.BooleanField()
```

Just leaves the chestentity table as id, level & opened.

Am I misunderstanding this feature?

**Comment by grigi** [comment]
Try just inheriting from `Entity` instead of both `Enitity` and `Model`?

**Comment by grigi** [comment]
I realised we don't have a detailed example in the docs for this, nor is it part of the test suite... :disappointed:

**Comment by tcmal** [comment]
Still doesn't seem to work.

**Comment by grigi** [comment]
@tcmal Can you please check with release v0.12.4 ?
new docs: https://tortoise-orm.readthedocs.io/en/latest/models.html#inheritence
