### ISSUE TITLE
How to handle changes in models?

### ISSUE THREAD

**Issue by sunset-developer** [tortoise/tortoise-orm#854]
Does tortoise automatically add a column whenever an already generated model (database table) has been updated? Or do I have to write code to make the change myself and or state the change in my library documentation. Thanks!

**Comment by long2ice** [comment]
Sorry I don't understand

**Comment by panla** [comment]
@sunset-developer 

```python
class Company(Model):
    id = fields.BigIntField(pk=True)
    is_deleted = fields.BooleanField(default=False, null=False)
    created_at = fields.DatetimeField(auto_now_add=True, null=False)
    updated_at = fields.DatetimeField(auto_now=True, null=False)
    name = fields.CharField(max_length=100, null=False)
    
    class Meta:
        table = 'companies'
        unique_together = (('name',),)
```

companies.sql

```sql
CREATE TABLE `companies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid_companies_name_1b02af` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

if you want to modify the database table companies add column, you should add field into tortoise Model Company.
if you want to modify the tortoise Model Company, you should migrate.

**Comment by sunset-developer** [comment]
@panla I'm modifying the tortoise model. Can you specify the migration process? Why wouldn't I just add a column?

**Comment by panla** [comment]
@sunset-developer 

Let's sort things out

first, you have a tortoise Model, and you migrate, and you have a table in database,

second, **you modify table or modify Model**.

third, you want to make sure the tortoise Model and database`table are the same.

Is there anything wrong here？and what`s the second detail?

**Comment by sunset-developer** [comment]
@panla Yes everything you mentioned is correct :) now lets say that the table has already been generated. I however want to update the Tortoise model with another variable field. Would this update be made manually to the database or can tortoise handle this automatically in some form?

**Comment by dstlny** [comment]
> @panla Yes everything you mentioned is correct :) now lets say that the table has already been generated. I however want to update the Tortoise model with another variable field. Would this update be made manually to the database or can tortoise handle this automatically in some form?

This is exactly why Aerich exists, to handle this kind of situation: 
https://tortoise-orm.readthedocs.io/en/latest/migration.html

**Comment by panla** [comment]
aerich is a member of tortoise-orm's ecological environment, we use it to generate migration sql, and upgrade table.
