### ISSUE TITLE
Bug in nested QuerySet and Manager

### ISSUE THREAD

**Issue by maxcoredev** [tortoise/tortoise-orm#864]
I've tried to make an additional method .active() to queryset of some model to be able to use it like:

`Session.objects.filter(key='some_key').active().prefetch_related('user').first()`

So, I've created some some `BaseManager` and extended it to accept custom `queryset_cls` and not original QuerySet:

```
class BaseManager(Manager):
    def __init__(self, model=None, queryset_cls=None) -> None:
        super().__init__(model=model)
        self.queryset_cls = queryset_cls or QuerySet

    def get_queryset(self) -> QuerySet:
        # return QuerySet(self._model)  # old line
        return self.queryset_cls(self._model). # new line
```

And I've wrote SessionQuerySet:

```
class SessionQuerySet(QuerySet):
    def active(self):
        return self.filter(
            expires__gt=datetime.datetime.now(),
            status=Session.Statuses.ACTIVE
        )
```

So I can use it now:

```
class Session(models.Model):
    ... some fields
    objects = BaseManager(queryset_cls=SessionQuerySet)
```

And when I try to execute:

`Session.objects.filter(key='some_key').active().prefetch_related('user').first()`

I get:

`AttributeError: 'QuerySet' object has no attribute 'active'`

However it works if order of method calls is like this:

`Session.objects.active().filter(key='some_key').prefetch_related('user').first()`

So, in my project, I've just added a monkey patch, that changes:

**tortoise/queryset.py:QuerySet**

```
320:    def _clone(self) -> "QuerySet[MODEL]":
321:        # queryset = QuerySet.__new__(QuerySet)  # old line 
322:        queryset = __class__.__new__(__class__)  # new line
```

and everything is fine

---

Second problem is in nested Manager

Suppose we have an abstract model with custom manager and it's descendant

```
class BaseModel(models.Model):
    ... some fields ...
    objects = BaseManager()


class Session(BaseModel):
    ... some fields ...

```
And when I do simple:

`Session.objects.all()`

```
  File "/www/myproject/./base/views.py", line 9, in home
    print(await AuthUser.db.all())
  File "/env/myproject/lib/python3.9/site-packages/tortoise/manager.py", line 18, in __getattr__
    return getattr(self.get_queryset(), item)
  File "/www/gamout/./abyss/managers.py", line 18, in get_queryset
    return self.qs_cls(self._model)
  File "/env/gamout/lib/python3.9/site-packages/tortoise/queryset.py", line 293, in __init__
    super().__init__(model)
  File "/env/gamout/lib/python3.9/site-packages/tortoise/queryset.py", line 93, in __init__
    self.capabilities: Capabilities = model._meta.db.capabilities
  File "/env/gamout/lib/python3.9/site-packages/tortoise/models.py", line 276, in db
    raise ConfigurationError("No DB associated to model")
tortoise.exceptions.ConfigurationError: No DB associated to model
```

I've tried to figure out why, and `BaseManager().__init__` method triggered only once and when it was associated with BaseModel. So, its descendants do not really have "objects"

Everything works if `objects` added explicitly to nested models

```
class Session(models.Model):
    ... some fields ...
    objects = BaseManager()
```

**Comment by long2ice** [comment]
Yes, that should be fix

**Comment by maxcoredev** [comment]
Now it works if `manager` is defined like this:

```python
class ManagerModel(AbstractManagerModel):
    class Meta:
        manager = StatusManager(queryset_cls=StatusQuerySet)
```
(Thats from tests tests/testmodels.py)
However it will not work if `manager` is defined like this:
```
objects = StatusManager(queryset_cls=StatusQuerySet)
```
However it works, when in `tortoise/queryset.py:321`
- queryset = self.__class__.__new__(QuerySet)
+ queryset = self.__class__.__new__(self.__class__)

---

P.S. Nested managers work fine now!
