### ISSUE TITLE
Can i get single value from annotate with Sum function?

### ISSUE THREAD

**Issue by Chenger1** [tortoise/tortoise-orm#866]
Have a model:

     class Transaction(Model):
          number= fields.IntField()
          amount = fields.FloatField()

For example, i have 3 transaction with amount: 100, 200, 300. I want to get total sum, making something like:

    await Transaction.annotate(total_sum=Sum('amount')).values('total_sum')

And i get:

    [{'total_sum': 100}, {'total_sum': 200}, {'total_sum': 300}]

Can i get {'total_sum': 600}?
I tried to group query, but still dont understand how to implement this behavior.

**Comment by Masynchin** [comment]
Hello from non-contributor. I think this is what you need - https://tortoise.github.io/examples/basic.html#group-by

**Comment by Masynchin** [comment]
This little `.filter()` query method defines which entities should be include - https://tortoise.github.io/functions.html#functions--page-root
With `.all()` this query returns 600

`Transaction.all().annotate(total_sum=Sum("amount")).values("total_sum")`
