### ISSUE TITLE
does tortoise orm supprots polymorphic model

### ISSUE THREAD

**Issue by ksthakur** [tortoise/tortoise-orm#867]
i want to use tortoise orm and fastapi.
but all i need to create polymorphic model using tortoise orm.
it will be good if you explain with example

**Comment by long2ice** [comment]
Did you mean https://tortoise.github.io/models.html?highlight=abstract#tortoise.models.Model.Meta.abstract?

**Comment by ksthakur** [comment]
i want something like this, below is in sqlalchemy

class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(20))

    __mapper_args__ = {
        'polymorphic_on':type,
        'polymorphic_identity':'employee'
    }

class Manager(Employee):
    manager_data = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'manager'
    }

class Engineer(Employee):
    engineer_info = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'engineer'
    }

**Comment by long2ice** [comment]
That's similar

**Comment by ksthakur** [comment]
sorry i missed that part, thanks!!!
also if you can help me post route to create employee using tortoise orm
