### ISSUE TITLE
Auto-completion in IDE doesn't show fields of related models

### ISSUE THREAD

**Issue by jakubkazimierczak** [tortoise/tortoise-orm#868]
**Describe the bug**
The auto-completion for related models doesn't their fields.

**To Reproduce**
1. Get models from the docs: [Improving relational type hinting](https://tortoise-orm.readthedocs.io/en/latest/models.html#improving-relational-type-hinting).
2. Create a query:
```python
event = await Event.all().prefetch_related("tournament").first()
```
3. Try auto-completion for the `event` in the IDE:
```python
event.tournament  # autocompleting ".tournament" works
event.tournament.name  # autocompleting ".name" doesn't
```

**Expected behavior**
Auto-completion should show fields of the related models.

**Additional context**
Using auto-completion for the fields of the model works:

![image](https://user-images.githubusercontent.com/77862767/129805130-7cca90b1-1dc3-4143-a708-f27b4e115673.png)

It doesn't on the relational fields:

![image](https://user-images.githubusercontent.com/77862767/129805244-95c0d783-7918-452b-8f56-065d70f76f8d.png)

**Comment by panla** [comment]
vscode
![related](https://user-images.githubusercontent.com/41326348/129840243-52095568-2447-40a0-9472-6707ad6feaff.png)

**Comment by jakubkazimierczak** [comment]
Interesting. It doesn't work in latest PyCharm though.

**Comment by jakubkazimierczak** [comment]
I submitted the issue to the JetBrains, it's here: https://youtrack.jetbrains.com/issue/PY-50364
