### ISSUE TITLE
DatetimeField TZ？The generated time is not the same as the database time, the difference is 8 hours

### ISSUE THREAD

**Issue by vvanglro** [tortoise/tortoise-orm#872]
use in fastapi

### 
        class BaseModel(Model):
            id = fields.IntField(pk=True, index=True)
            created_at = fields.DatetimeField(auto_now_add=True, description='创建时间')
            updated_at = fields.DatetimeField(auto_now=True, description='更新时间')
        
            class Meta:
                abstract = True

**Comment by dstlny** [comment]
> use in fastapi
> 
> ```
>     class BaseModel(Model):
>         id = fields.IntField(pk=True, index=True)
>         created_at = fields.DatetimeField(auto_now_add=True, description='创建时间')
>         updated_at = fields.DatetimeField(auto_now=True, description='更新时间')
>     
>         class Meta:
>             abstract = True
> ```

https://tortoise-orm.readthedocs.io/en/latest/timezone.html

Probably because the time one, by default, is UTC.

**Comment by vvanglro** [comment]
> > use in fastapi
> > ```
> >     class BaseModel(Model):
> >         id = fields.IntField(pk=True, index=True)
> >         created_at = fields.DatetimeField(auto_now_add=True, description='创建时间')
> >         updated_at = fields.DatetimeField(auto_now=True, description='更新时间')
> >     
> >         class Meta:
> >             abstract = True
> > ```
> 
> https://tortoise-orm.readthedocs.io/en/latest/timezone.html
> 
> Probably because the time zone, by default, is UTC.

Yes, I see the default UTC in the source code，I can't seem to change the time zone with register Tortoise
In the end I use
![截屏2021-08-22 18 35 47](https://user-images.githubusercontent.com/43594924/130352061-280d0580-5caf-4442-822c-44f273433894.png)

**Comment by dstlny** [comment]
> > > use in fastapi
> > > ```
> > >     class BaseModel(Model):
> > >         id = fields.IntField(pk=True, index=True)
> > >         created_at = fields.DatetimeField(auto_now_add=True, description='创建时间')
> > >         updated_at = fields.DatetimeField(auto_now=True, description='更新时间')
> > >     
> > >         class Meta:
> > >             abstract = True
> > > ```
> > 
> > 
> > https://tortoise-orm.readthedocs.io/en/latest/timezone.html
> > Probably because the time zone, by default, is UTC.
> 
> Yes, I see the default UTC in the source code，I can't seem to change the time zone with register Tortoise
> In the end I use
> ![截屏2021-08-22 18 35 47](https://user-images.githubusercontent.com/43594924/130352061-280d0580-5caf-4442-822c-44f273433894.png)

Hey, you should be able to pass the timezone in with the 'config' object.

Something like:
```python
register_tortoise(
    app=app,
    config={
        'connections': {
            'default': DATABASE_URL
        },
        'apps': {
            'app': {
                'models': ['app.models'],
                'default_connection': 'default',
            }
        },
        'use_tz': True,
        'timezone': 'Asia/Shanghai'
    }

)
```
would work :)

**Comment by vvanglro** [comment]
> > > > use in fastapi
> > > > ```
> > > >     class BaseModel(Model):
> > > >         id = fields.IntField(pk=True, index=True)
> > > >         created_at = fields.DatetimeField(auto_now_add=True, description='创建时间')
> > > >         updated_at = fields.DatetimeField(auto_now=True, description='更新时间')
> > > >     
> > > >         class Meta:
> > > >             abstract = True
> > > > ```
> > > 
> > > 
> > > https://tortoise-orm.readthedocs.io/en/latest/timezone.html
> > > Probably because the time zone, by default, is UTC.
> > 
> > 
> > Yes, I see the default UTC in the source code，I can't seem to change the time zone with register Tortoise
> > In the end I use
> > ![截屏2021-08-22 18 35 47](https://user-images.githubusercontent.com/43594924/130352061-280d0580-5caf-4442-822c-44f273433894.png)
> 
> Hey, you should be able to pass the timezone in with the 'config' object.
> 
> Something like:
> 
> ```python
> register_tortoise(
>     app=app,
>     config={
>         'connections': {
>             'default': DATABASE_URL
>         },
>         'apps': {
>             'app': {
>                 'models': ['app.models'],
>                 'default_connection': 'default',
>             }
>         },
>         'use_tz': True,
>         'timezone': 'Asia/Shanghai'
>     },
>     generate_schemas=False,
>     add_execptio_handlers=True
> )
> ```
> 
> would work :)

All right, I configured it like this and it worked，thx 
https://github.com/vvanglro/docker-fastapi-sqlalchemy-tortoise-orm/blob/13860f2740f1815f6d2ffd7b7d83a216d8c7dc4a/run.py#L141

> ```python
> register_tortoise(
>     app,
>     config={
>         'connections': {
>             'default': DATABASE_URL
>         },
>         "apps": {
>             "models": {
>                 "models": ["coronavirus.models"],
>                 "default_connection": "default",
>             }
>         },
>         'use_tz': False,
>         'timezone': 'Asia/Shanghai'
>     },
>     generate_schemas=False,
>     add_exception_handlers=True,
> )
>```
