### ISSUE TITLE
Why foreign keys created with `_id` suffix?

### ISSUE THREAD

**Issue by dadyarri** [tortoise/tortoise-orm#903]
It doesn't obvious, because in some places I should use field name with `_id`, in some - without. Why is it happened, or am I doing something wrong?

Model's part:
```python
state: int = fields.ForeignKeyField(
    "models.State",
    "state's id",
)
```

Database:
![image](https://user-images.githubusercontent.com/51821039/132064056-9c0f734c-c774-4e30-a8c4-c14e9097ccb8.png)

Usage:
```python
async with in_transaction():
    query = await models.StateStorage.get_or_none(user_id=user_id)
    try:
        return query.state_id
    except AttributeError:
        return None
```

And worse, it broke linters because of missing attribute:
![image](https://user-images.githubusercontent.com/51821039/132064287-94913f7c-71fd-4fe6-a138-df006d48dbe9.png)

**Comment by dstlny** [comment]
> It doesn't obvious, because in some places I should use field name with `_id`, in some - without. Why is it happened, or am I doing something wrong?
> 
> Model's part:
> 
> ```python
> state: int = fields.ForeignKeyField(
>     "models.State",
>     "state's id",
> )
> ```
> 
> Database:
> ![image](https://user-images.githubusercontent.com/51821039/132064056-9c0f734c-c774-4e30-a8c4-c14e9097ccb8.png)
> 
> Usage:
> 
> ```python
> async with in_transaction():
>     query = await models.StateStorage.get_or_none(user_id=user_id)
>     try:
>         return query.state_id
>     except AttributeError:
>         return None
> ```
> 
> And worse, it broke linters because of missing attribute:
> ![image](https://user-images.githubusercontent.com/51821039/132064287-94913f7c-71fd-4fe6-a138-df006d48dbe9.png)

"state_id" is the database-backed field. In this case, "state_id" represents the databases column name which is the ID of that particular State object. 

Django does the exact same thing and literally every other ORM does too.

**Comment by dstlny** [comment]
> It doesn't obvious, because in some places I should use field name with `_id`, in some - without. Why is it happened, or am I doing something wrong?
> 
> Model's part:
> 
> ```python
> state: int = fields.ForeignKeyField(
>     "models.State",
>     "state's id",
> )
> ```
> 
> Database:
> ![image](https://user-images.githubusercontent.com/51821039/132064056-9c0f734c-c774-4e30-a8c4-c14e9097ccb8.png)
> 
> Usage:
> 
> ```python
> async with in_transaction():
>     query = await models.StateStorage.get_or_none(user_id=user_id)
>     try:
>         return query.state_id
>     except AttributeError:
>         return None
> ```
> 
> And worse, it broke linters because of missing attribute:
> ![image](https://user-images.githubusercontent.com/51821039/132064287-94913f7c-71fd-4fe6-a138-df006d48dbe9.png)

This is normal behaviour. 

Tortoise takes heavy influence from Django, and Django (and... like... every other ORM) uses the same technique to map the columns of the ORM Class to the database table. It's called a "Database backed field".

Django explains it here: https://docs.djangoproject.com/en/3.2/ref/models/fields/#database-representation

Tortoise also explains it here: 
https://tortoise-orm.readthedocs.io/en/latest/models.html?highlight=_id#the-db-backing-field

**Comment by dadyarri** [comment]
Thanks for the answer

> if you want the actual object use `fieldname`. Else if you just want the ID, use`fieldname_id` or alternatively `fieldname.id`

For some reason `fieldname` returns `tortoise.queryset.QuerySet`, therefore `fieldname.id` does not exist

**Comment by dstlny** [comment]
> Thanks for the answer
> 
> > if you want the actual object use `fieldname`. Else if you just want the ID, use`fieldname_id` or alternatively `fieldname.id`
> 
> For some reason `fieldname` returns `tortoise.queryset.QuerySet`, therefore `fieldname.id` does not exist

This is probably because you'd need to await `fieldname` before accessing it - so Tortoise can pull the object from the database. Tortoise is pretty smart about that - it will only pull objects into memory when you specifically ask for it to via `select_related` or by manually awaiting `fieldname` :)

**Comment by dadyarri** [comment]
Thanks a lot, now it's working good!

Sorry for off-topic, but can you answer why get_or_create can create new record, even if it already exist?

**Comment by dstlny** [comment]
> Thanks a lot, now it's working good!
> 
> Sorry for off-topic, but can you answer why `get_or_create` can create new record, even if it already exists?
> 
> ```python
> user = await models.User.get_or_create(vk_id=vk_id)  # this is not creating again
> await models.StateStorage.get_or_create(  # and this can
>         user_id=user[0].id,
>         state_id=state_id,
> )
> ```

Good question. Not too sure about that one. Internally Tortoise tries to get the object first before creating when using that method - so, the only way that should fail is if a object doesn't exist in the database with those two exact id's.

Hope that helps :)

**Comment by dadyarri** [comment]
I understood. Searching the row made by all arguments (`user_id` and `state_id` in my case). If user have other state than `state_id` then row will be created. Thanks for help.
