### ISSUE TITLE
Is there any plan to replace asynctest ?

### ISSUE THREAD

**Issue by yoann9344** [tortoise/tortoise-orm#920]
Hello,

I would like to know if you have any perspective to replace asynctest, because it won't be maintained anymore and it has not received any update last 2 years ?

[Référence.](https://github.com/Martiusweb/asynctest/issues/158)

**Comment by long2ice** [comment]
That's good but is a big work

**Comment by yoann9344** [comment]
I up to help, but I need some directions, to follow the project goals and the good practices !

**Comment by long2ice** [comment]
Just remove asynctest and make all tests pass, you can run `make style ci` in local.

**Comment by long2ice** [comment]
see https://github.com/tortoise/tortoise-orm/pull/977
