### ISSUE TITLE
Is there a batch update of this interface?

### ISSUE THREAD

**Issue by Skyonelu** [tortoise/tortoise-orm#924]
Is there a batch update of this interface? I see that django has bulk_update

**Comment by long2ice** [comment]
Current no

**Comment by Skyonelu** [comment]
> Current no

thank you , I mainly hope that the author can come up with such a method

**Comment by long2ice** [comment]
What's the raw sql like? Or just a method wrapper for one by one update

**Comment by dstlny** [comment]
> What's the raw sql like? Or just a method wrapper for one by one update

Django currently does this with CASE/WHEN statements. 

https://github.com/django/django/blob/06c50cee0fb1fd23248518334eabb2fbf61b2cbc/django/db/models/query.py#L534

So, something like:
```
UPDATE SomeTable
	SET 
	x = CASE WHEN id = 0 THEN x + 100 ELSE x END
```

**Comment by long2ice** [comment]
Awesome!
