### ISSUE TITLE
tortoise.exceptions.OperationalError: Packet sequence number wrong - got 0 expected 1

### ISSUE THREAD

**Issue by Vang-z** [tortoise/tortoise-orm#925]
**Describe the bug**
I ran into a similar problem with [https://github.com/tortoise/tortoise-orm/issues/784](https://github.com/tortoise/tortoise-orm/issues/784), I try this solution [https://github.com/tortoise/tortoise-orm/issues/784#issuecomment-898402711](https://github.com/tortoise/tortoise-orm/issues/784#issuecomment-898402711), but I never kown how to set the `pool_recycle`. Could you please tell me how to solve this problem.

**To Reproduce**
I use `fastapi` and `tortoise-orm` together, my server is running on `Ubuntu Server 20.04 LTS x64`. Here is my code:
```
DATABASE_URL = f'mysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB_NAME}?charset={CHARSET}'

def init_db(app: FastAPI):
    register_tortoise(
        app,
        add_exception_handlers=True,
        config={
            'connections': {
                'default': DATABASE_URL
            },
            'apps': {
                'models': {
                    'models': ['app.db.models'],
                    'default_connection': 'default',
                }
            },
            "use_tz": True,
            "timezone": "Asia/Shanghai",
        }
    )
```

**Comment by long2ice** [comment]
There are two methods, one is `mysql://...?pool_recycle=3600`, another is in `credentials`
```py
{
    'connections': {
        'default': {
            'engine': 'tortoise.backends.mysql',
            'credentials': {
                ....
                'pool_recycle': 3600 # <- add in here
            }
        },
    }
}
```

**Comment by Vang-z** [comment]
Okay, thank you very much. Hope tortoise-orm will be better and better :)

**Comment by Vang-z** [comment]
I try to the both solutions, only last one has correct use, fisrt one has error of aiomysql `TypeError: '>' not supported between instances of 'str' and 'int'`, because of it's source code not convert `str` to `int`: 
`self._recycle = pool_recycle -> aiomysql/pool.py line: 52`

**Comment by bigquant** [comment]
> I try to the both solutions, only last one has correct use, fisrt one has error of aiomysql `TypeError: '>' not supported between instances of 'str' and 'int'`, because of it's source code not convert `str` to `int`: `self._recycle = pool_recycle -> aiomysql/pool.py line: 52`

Any update for this error (TypeError)?
