### ISSUE TITLE
iso8601.iso8601.ParseError: Unable to parse date string ''

### ISSUE THREAD

**Issue by apan-git** [tortoise/tortoise-orm#949]
I use tortoise ORM to get the object of firs (). This error occurs when the time field in the database is None
![image](https://user-images.githubusercontent.com/59251803/136746665-30456bf7-3b0d-4abf-bfa0-334982f15859.png)

However, when I check the source code according to the error information, I find the judgment of time type, but what will become a string when entering

![image](https://user-images.githubusercontent.com/59251803/136747403-652da0bf-2675-49aa-acae-207e37bd483b.png)

Oh, my God, who can help me

**Comment by apan-git** [comment]
However, without modifying the database data, I modified the dependency package, and this problem will not occur
I don't understand what's going on here

**Comment by long2ice** [comment]
What dependency?

**Comment by long2ice** [comment]
So the `value` should be `None`

**Comment by apan-git** [comment]
OK, I use 0.17.7

**Comment by apan-git** [comment]
Thank you. I tried and succeeded
