### ISSUE TITLE
Allow to retrieve the raw SQL of a queryset

### ISSUE THREAD

**Issue by florimondmanca** [tortoise/tortoise-orm#95]
**Is your feature request related to a problem? Please describe.**
There's at the moment no way to inspect the actual SQL query that a QuerySet would execute when evaluated. This can however be very useful for debugging.

**Describe the solution you'd like**
Add an `.sql` property to `QuerySet` that could be used like this:

```python
>>> print(Book.all().sql)
SELECT * FROM "books";
```

Implementation-wise, I believe `return self._make_query().get_sql()` should work.

**Describe alternatives you've considered**
We could have named this `.query`, but it would be unclear whether this returns a plain string (as this issue suggests) or the actual `Query` object from pypika. I don't think the second option is a good idea, because using pypika should an implementation detail to our users.

**Additional context**
Follow-up on @abondar 's suggestion in #91

**Comment by Priestch** [comment]
@florimondmanca This feature was added in version 0.16.12, you can give it a try!
