### ISSUE TITLE
Field's schema customising

### ISSUE THREAD

**Issue by abondar** [tortoise/tortoise-orm#97]
Currently information on how to generate schema from field is stored in `schema_generator` and in order to make custom field for some DB type, that is not covered by us, user would have to create custom  SchemaGenerator and DBClient pointing to it, which is quite hard deal.

We could simplify SchemaGenerator by delegating description of schema to models and fields themselves. So fields would have method `get_sql_type` where it would return just string that would go in schema generating sql. Also there is advantage with this approach, that this way fields like `DecimalField` would be generated much more elegantly, than it does now.

Problem with that approach is how to alter that string depending on dialect. I think we could pass dialect (or capabilities) down to `get_sql_type` functions, so that they can alter behaviour based on dialect.

Also I think it should be developed alongside with #39

**Comment by grigi** [comment]
We should be able to override the default Field type for a db type, and replace it transparently if provided.

E.g. Using the native functionality of PostgreSQL for JSON and UUID:
```py
from typing import Optional, Union
from uuid import UUID

from tortoise.fields import JSONField as GenericJSONField
from tortoise.fields import UUIDField as GenericUUIDField


class JSONField(GenericJSONField):
    def to_db_value(self, value: Optional[Union[dict, list]], instance):
        return value

    def to_python_value(self, value: Optional[Union[str, dict, list]]):
        return value


class UUIDField(GenericUUIDField):
    def to_db_value(self, value: Optional[UUID], instance):
        return value

    def to_python_value(self, value: Optional[UUID]):
        return value
```

**Comment by grigi** [comment]
Related issue #55

**Comment by grigi** [comment]
FWIW, currently all the DB-specific field logic sits in the executor (and DDL in schema_generator). There is a few places in the code I noticed where we DON'T use the executor. We need to move it all in.
Also, we currently re-create the executor for every operation, and I have a cacheing system to make construction cheaper. If we make it required and created on first use of DB-MODEL combo to support complicated Field-DB logic, we can then avoid the cacheing infrastructure for a simpler solution.

One of the ideas could be:
when one defines a Field, one could define many getters/setters and field info depending on dialects?

e.g:
```py
class CharField(Field):
    __slots__ = ("max_length", "case_sensitive")
    DB_NATIVE_TYPE = True

    def __init__(self, max_length: int, case_sensitive=True, **kwargs) -> None:
        if int(max_length) < 1:
            raise ConfigurationError("'max_length' must be >= 1")
        self.max_length = int(max_length)
        self.case_sensitive = int(case_sensitive)
        super().__init__(str, **kwargs)

    def _gen_field(self) -> str:
        return f"VARCHAR({self.max_length})"

    def _gen_index(self, requested: bool, key:str, field_name:str) -> List[str]:
        if requested:
            return [f"CREATE INDEX {key} on {field_name}"]
        return []

    class _dialect_postgres:

        def _gen_index(self, requested: bool, key:str, field_name:str) -> str:
            indexes = []
            if requested:
                indexes.append(f"CREATE INDEX {key} on {field_name}")
            if not self.case_sensitive:
                indexes.append(f"CREATE INDEX {key}_ci on LOWER({field_name})")
            return indexes
```

@abondar  What do you think? This way one could optionally override any func/constant? (except for the constructor)

**Comment by grigi** [comment]
# Update:
This should cover the following:
* Refactor fields to know all about DB overrides
* Refactor fields to use https://github.com/tortoise/tortoise-orm/issues/196#issuecomment-536012779
* Update `Tortise.describe_model()` to use it.
* Use model description to generate DDL schemas (ensure that all non-formatting info is in described model.)
* Allow DDL generation to generate a DDL without a DB being configured.

Plans is to get this as the main feature with v0.14

**Comment by grigi** [comment]
## Still outstanding

* Have fields define "native level" for DB.
* Have fields define index types per field
* Have fields define collation per field
* Use model description to generate DDL schemas (ensure that all non-formatting info is in described model.)
* Allow DDL generation to generate a DDL without a DB being configured.

**Comment by grigi** [comment]
Actully, all that is strictly outstanding for this to be closed is:
* Migrate "native" type-check to use data in Field.
* Overrideable to_db and from_db on a per dialect level.

**Comment by grigi** [comment]
After inpementing overrideable to_db per field, I found it had very minimal impact, so I'm marking this as not needed.
Also, there is nothing to buy from migrating the per-db "native" type check right now. Or rather, it should not be done in this way, but more explicit.

So both outstanding items are not really relevant at this stage. I'm happy to close this right now.
