### ISSUE TITLE
How do I skip a value when I execute insert?

### ISSUE THREAD

**Issue by jetwolf** [tortoise/tortoise-orm#971]
Hello! How do I skip a value when I execute insert

My class:

`
class BaseModel(models.Model):
    uuid = fields.UUIDField(pk=True, default=uuid4)
    created_at = fields.DatetimeField(auto_now_add=True)
    modified_at = fields.DatetimeField(auto_now=True)

    class Meta:
        abstract = True

    class PydanticMeta:
        exclude = ("created_at", "modified_at")

class Workspace(BaseModel):
    index = AutoFiled(unique=True, index=True)
    title = fields.CharField(max_length=255, unique=True)
    description = fields.CharField(max_length=1024, null=True)
    city_id = fields.IntField(null=True)

    class Meta:
        table = "workspaces"
`
Request body:
`
{
	"title": "Test"
}
`

Generated sql:
`
INSERT INTO "workspaces" ("uuid","created_at","modified_at","index","title","description","city_id") VALUES ($1,$2,$3,$4,$5,$6,$7): ['07188f72-1d7f-4b7d-90df-790289841372', datetime.datetime(2021, 11, 3, 12, 5, 0, 660732, tzinfo=<UTC>), datetime.datetime(2021, 11, 3, 12, 5, 0, 660753, tzinfo=<UTC>), None, 'Test', None, None]
`

What I want:
`
INSERT INTO "workspaces" ("uuid","created_at","modified_at","title","description","city_id") VALUES ($1,$2,$3,$4,$5,$6,$7): ['07188f72-1d7f-4b7d-90df-790289841372', datetime.datetime(2021, 11, 3, 12, 5, 0, 660732, tzinfo=<UTC>), datetime.datetime(2021, 11, 3, 12, 5, 0, 660753, tzinfo=<UTC>), 'Test', None, None]
`
Remove index from sql.

**Comment by jetvolkov** [comment]
class AutoFiled(fields.IntField, int):
    SQL_TYPE = "SERIAL"

**Comment by BobDotCom** [comment]
Try the `update_fields` parameter on `Model.save()`
